permit(
  principal,
  action == Action::"qbgdzpvrdifc",
  resource
) when {
  true
};permit(
  principal == Principal::"goqggbpdxgwr",
  action,
  resource == Resource::"timjwovtulzb"
) when {
  true
};forbid(
  principal,
  action == Action::"zfblempubvmb",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"aotmndqkhxbk",
  resource
) when {
  true
};permit(
  principal == Principal::"jxllzskqzgeg",
  action == Action::"nyyuklxqscqt",
  resource == Resource::"eajajckkdxin"
) when {
  true
};permit(
  principal,
  action == Action::"ldmgzzpzipmi",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"oagdepjjxjve",
  resource == Resource::"kgybmrzghtfr"
) when {
  true
};forbid(
  principal == Principal::"cmgfuqqdhwty",
  action == Action::"fxgbdocejcpz",
  resource
) when {
  true
};permit(
  principal == Principal::"usbbiwzqcjvy",
  action == Action::"oiecogmdhjvl",
  resource == Resource::"timjwovtulzb"
) when {
  true
};permit(
  principal,
  action == Action::"nyyuklxqscqt",
  resource == Resource::"wekhcuisedqi"
) when {
  true
};permit(
  principal,
  action == Action::"clqrbfdultrg",
  resource == Resource::"jatfkrdpwncj"
) when {
  true
};permit(
  principal == Principal::"gvuneigzswar",
  action == Action::"qyzmaofvxkkl",
  resource == Resource::"fuoeuskbfreh"
) when {
  true
};permit(
  principal,
  action == Action::"setzbweiskyx",
  resource
) when {
  true
};permit(
  principal == Principal::"wndviveimpbr",
  action == Action::"kuttpqzfseyj",
  resource
) when {
  true
};permit(
  principal == Principal::"hwnfhkfeiukw",
  action == Action::"kuttpqzfseyj",
  resource == Resource::"owwfzchghvfa"
) when {
  true
};permit(
  principal == Principal::"request",
  action == Action::"request",
  resource == Resource::"request"
) when {
  true
};permit(
  principal,
  action == Action::"ufqfrlljkqcl",
  resource
) when {
  true
};permit(
  principal == Principal::"vdtsvkdkqihb",
  action == Action::"oiecogmdhjvl",
  resource == Resource::"cmvnvhxnjcre"
) when {
  true
};forbid(
  principal == Principal::"hwnfhkfeiukw",
  action,
  resource == Resource::"phekdjazwudc"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"depowqxevkka"
) when {
  true
};forbid(
  principal,
  action == Action::"ufqfrlljkqcl",
  resource
) when {
  true
};permit(
  principal == Principal::"zrkmnqwsntpb",
  action == Action::"ufqfrlljkqcl",
  resource == Resource::"xynxydjfrefz"
) when {
  true
};forbid(
  principal,
  action == Action::"chslwbirccwq",
  resource == Resource::"ujtdbctcpkjo"
) when {
  true
};forbid(
  principal == Principal::"xdwmtbmfxllq",
  action == Action::"zfblempubvmb",
  resource
) when {
  true
};permit(
  principal == Principal::"rwwvlryrtaey",
  action,
  resource == Resource::"vwmuidgixuio"
) when {
  true
};permit(
  principal == Principal::"mczpzegikypi",
  action == Action::"ldmgzzpzipmi",
  resource == Resource::"cmvnvhxnjcre"
) when {
  true
};forbid(
  principal == Principal::"mczpzegikypi",
  action == Action::"aotmndqkhxbk",
  resource == Resource::"hlzqekwxnhbv"
) when {
  true
};forbid(
  principal == Principal::"goqggbpdxgwr",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"dccmtlgchohx",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"dhpeuxcwblll",
  action,
  resource == Resource::"eajajckkdxin"
) when {
  true
};forbid(
  principal == Principal::"dccmtlgchohx",
  action == Action::"oiecogmdhjvl",
  resource
) when {
  true
};forbid(
  principal == Principal::"qhlzedyisueq",
  action == Action::"ldmgzzpzipmi",
  resource == Resource::"rgtrgxjlpelh"
) when {
  true
};permit(
  principal,
  action == Action::"clqrbfdultrg",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"phekdjazwudc"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"hzikjyynquoo"
) when {
  true
};permit(
  principal == Principal::"tlbpdobfcpde",
  action == Action::"kuttpqzfseyj",
  resource
) when {
  true
};permit(
  principal == Principal::"tdnnooehpovy",
  action,
  resource == Resource::"cmvnvhxnjcre"
) when {
  true
};permit(
  principal == Principal::"tlbpdobfcpde",
  action,
  resource == Resource::"uvlsccagxvin"
) when {
  true
};permit(
  principal == Principal::"mczpzegikypi",
  action == Action::"oiecogmdhjvl",
  resource
) when {
  true
};forbid(
  principal == Principal::"dhpeuxcwblll",
  action == Action::"fvvbofxrftct",
  resource == Resource::"ldllqnyoeuqb"
) when {
  true
};forbid(
  principal == Principal::"ugzbdubqzemq",
  action == Action::"zfblempubvmb",
  resource == Resource::"timjwovtulzb"
) when {
  true
};forbid(
  principal == Principal::"xmjtixuhswyc",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"ciakcuigiebb",
  resource == Resource::"wexesvymyzoa"
) when {
  true
};forbid(
  principal == Principal::"kvckksaqgkya",
  action == Action::"xcupxigmbtre",
  resource
) when {
  true
};permit(
  principal == Principal::"ugzbdubqzemq",
  action == Action::"pbgwsbsuirld",
  resource
) when {
  true
};permit(
  principal == Principal::"cmgfuqqdhwty",
  action,
  resource == Resource::"timjwovtulzb"
) when {
  true
};forbid(
  principal == Principal::"goqggbpdxgwr",
  action == Action::"zbloogbpmluc",
  resource
) when {
  true
};permit(
  principal == Principal::"spmvlqjxmwhz",
  action,
  resource == Resource::"phekdjazwudc"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ldllqnyoeuqb"
) when {
  true
};permit(
  principal == Principal::"gvuneigzswar",
  action,
  resource == Resource::"cqigzdkkpcck"
) when {
  true
};permit(
  principal == Principal::"btasiqiadyir",
  action,
  resource == Resource::"cqigzdkkpcck"
) when {
  true
};permit(
  principal == Principal::"kvckksaqgkya",
  action == Action::"kuttpqzfseyj",
  resource
) when {
  true
};permit(
  principal == Principal::"btillujglrzj",
  action,
  resource == Resource::"hlzqekwxnhbv"
) when {
  true
};permit(
  principal,
  action == Action::"ciakcuigiebb",
  resource
) when {
  true
};forbid(
  principal == Principal::"tdnnooehpovy",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"btillujglrzj",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"dhpeuxcwblll",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"usbbiwzqcjvy",
  action,
  resource == Resource::"kikynybljxpi"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"cathalgliwhy"
) when {
  true
};permit(
  principal == Principal::"hwnfhkfeiukw",
  action,
  resource == Resource::"maqwqpgscxfn"
) when {
  true
};forbid(
  principal == Principal::"kvckksaqgkya",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"cmgfuqqdhwty",
  action == Action::"khgapvaopjdu",
  resource == Resource::"kotuibzhjttp"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"cehqfxvryghx"
) when {
  true
};forbid(
  principal == Principal::"jxllzskqzgeg",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"xstlzaqwowlx"
) when {
  true
};forbid(
  principal == Principal::"vdtsvkdkqihb",
  action == Action::"xulhymhzhwnu",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"qyzmaofvxkkl",
  resource == Resource::"nvdpcvrmlkis"
) when {
  true
};permit(
  principal == Principal::"kvckksaqgkya",
  action == Action::"xhgjazzhbkct",
  resource
) when {
  true
};permit(
  principal == Principal::"alhnuueeqhdm",
  action == Action::"ktjezhzefuyz",
  resource
) when {
  true
};forbid(
  principal == Principal::"btillujglrzj",
  action == Action::"ktjezhzefuyz",
  resource
) when {
  true
};forbid(
  principal == Principal::"xdwmtbmfxllq",
  action == Action::"yypveiuvklfl",
  resource
) when {
  true
};forbid(
  principal == Principal::"tlbpdobfcpde",
  action == Action::"aotmndqkhxbk",
  resource == Resource::"lopvrcawypfz"
) when {
  true
};permit(
  principal,
  action == Action::"ciakcuigiebb",
  resource == Resource::"hbwmkwqhjgnk"
) when {
  true
};forbid(
  principal,
  action == Action::"aotmndqkhxbk",
  resource == Resource::"znesszqchvyk"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ldllqnyoeuqb"
) when {
  true
};forbid(
  principal == Principal::"goqggbpdxgwr",
  action == Action::"qbgdzpvrdifc",
  resource == Resource::"ldllqnyoeuqb"
) when {
  true
};permit(
  principal == Principal::"jxllzskqzgeg",
  action == Action::"chslwbirccwq",
  resource == Resource::"cathalgliwhy"
) when {
  true
};permit(
  principal == Principal::"uclaurwvgzdb",
  action,
  resource == Resource::"hzikjyynquoo"
) when {
  true
};forbid(
  principal == Principal::"kvckksaqgkya",
  action == Action::"hchowjfppreq",
  resource == Resource::"cqigzdkkpcck"
) when {
  true
};permit(
  principal == Principal::"hwnfhkfeiukw",
  action == Action::"clqrbfdultrg",
  resource
) when {
  true
};forbid(
  principal == Principal::"aawckmrvbpcq",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"tdnnooehpovy",
  action == Action::"xulhymhzhwnu",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"ldmgzzpzipmi",
  resource == Resource::"eajajckkdxin"
) when {
  true
};permit(
  principal == Principal::"rwwvlryrtaey",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"yypveiuvklfl",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"hlzqekwxnhbv"
) when {
  true
};permit(
  principal == Principal::"tlbpdobfcpde",
  action == Action::"qyzmaofvxkkl",
  resource
) when {
  true
};permit(
  principal == Principal::"mczpzegikypi",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"qhlzedyisueq",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"rgtrgxjlpelh"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"hbwmkwqhjgnk"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"owwfzchghvfa"
) when {
  true
};forbid(
  principal,
  action == Action::"lvpoajpqvyoq",
  resource == Resource::"wekhcuisedqi"
) when {
  true
};permit(
  principal,
  action == Action::"xcupxigmbtre",
  resource == Resource::"xstlzaqwowlx"
) when {
  true
};forbid(
  principal == Principal::"ertafyxoxdtj",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"uclaurwvgzdb",
  action == Action::"clqrbfdultrg",
  resource
) when {
  true
};forbid(
  principal == Principal::"btillujglrzj",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"qyzmaofvxkkl",
  resource
) when {
  true
};forbid(
  principal == Principal::"ertafyxoxdtj",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"ewqnqkkyoywo",
  action == Action::"ktjezhzefuyz",
  resource
) when {
  true
};