forbid(
  principal,
  action,
  resource == Resource::"heztdwpmufsm"
) when {
  true
};forbid(
  principal == Principal::"vdmoqnubphoz",
  action,
  resource == Resource::"hhxsdpyivfhm"
) when {
  true
};forbid(
  principal == Principal::"syzxbcwzqvcw",
  action == Action::"ibdmikowfplh",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"awnljuztvpam",
  resource == Resource::"heztdwpmufsm"
) when {
  true
};forbid(
  principal,
  action == Action::"smczxdsimeck",
  resource == Resource::"blijilenxjen"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"fvvopcjccbyk"
) when {
  true
};forbid(
  principal,
  action == Action::"sjhweuifdqve",
  resource == Resource::"fymqejvihnck"
) when {
  true
};forbid(
  principal == Principal::"huxvaiyucofb",
  action,
  resource == Resource::"blijilenxjen"
) when {
  true
};permit(
  principal == Principal::"gcjsbxixrzfs",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"request",
  action == Action::"request",
  resource == Resource::"request"
) when {
  true
};