forbid(
  principal == Principal::"ayqdgleuhvtt",
  action == Action::"rneblnnruvtc",
  resource == Resource::"ivvddpawazuj"
) when {
  true
};forbid(
  principal == Principal::"ckvyubdxskly",
  action == Action::"bxbzobaeygkp",
  resource == Resource::"caxjyfnencux"
) when {
  true
};permit(
  principal == Principal::"request",
  action == Action::"request",
  resource == Resource::"request"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"tqwdsjtdugpg"
) when {
  true
};permit(
  principal == Principal::"kshzkhwnxyxs",
  action,
  resource == Resource::"vfuamwydnwos"
) when {
  true
};forbid(
  principal == Principal::"ctihrnkxhrfl",
  action == Action::"nxrbaqhwpgpr",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"ehcookxorxts",
  resource
) when {
  true
};forbid(
  principal == Principal::"hrpbcbfgebmj",
  action == Action::"jdwalquhbcie",
  resource == Resource::"aoxfeevldalu"
) when {
  true
};permit(
  principal,
  action == Action::"hslrlakifeyg",
  resource == Resource::"mwdjpyjiovyo"
) when {
  true
};forbid(
  principal == Principal::"fsjnovzjqscm",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"dgxxhqtepxrh"
) when {
  true
};