permit(
  principal,
  action == Action::"ghihlhdluigw",
  resource == Resource::"qhzwkxmbaapi"
) when {
  true
};permit(
  principal == Principal::"esjqlfptglke",
  action,
  resource == Resource::"vzzmbsnbulkj"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"ifexyeszgfru"
) when {
  true
};permit(
  principal == Principal::"nzmhpiijyqgc",
  action == Action::"jxquuptatzpv",
  resource == Resource::"gluixahwqhsa"
) when {
  true
};permit(
  principal == Principal::"npxdnvuxefcj",
  action,
  resource == Resource::"picvrddcwolz"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"dvvacnqjjkev"
) when {
  true
};forbid(
  principal == Principal::"jvyqsroaqmsp",
  action == Action::"rpzvjuqnlrqc",
  resource == Resource::"ossfsmggcpua"
) when {
  true
};forbid(
  principal,
  action == Action::"nracctrvdoax",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"vwedmvcfufxr",
  resource == Resource::"csxgwejjfmtd"
) when {
  true
};forbid(
  principal == Principal::"mqnvxmhkkybg",
  action == Action::"rftufoyrblii",
  resource == Resource::"gluixahwqhsa"
) when {
  true
};permit(
  principal == Principal::"oqtjbgetscby",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"ghihlhdluigw",
  resource == Resource::"csxgwejjfmtd"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"tmflejujpxgy"
) when {
  true
};permit(
  principal == Principal::"krtcxoelqigx",
  action == Action::"gywhlyjwvlsm",
  resource == Resource::"xxspcbffjlim"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"idmufcmpqszm"
) when {
  true
};permit(
  principal == Principal::"mqnvxmhkkybg",
  action,
  resource == Resource::"csxgwejjfmtd"
) when {
  true
};permit(
  principal == Principal::"wbkavkcmrjxi",
  action == Action::"pmbgzlpqhwtt",
  resource == Resource::"pmbkoicrppvz"
) when {
  true
};forbid(
  principal,
  action == Action::"vwedmvcfufxr",
  resource == Resource::"tmflejujpxgy"
) when {
  true
};permit(
  principal,
  action == Action::"jxquuptatzpv",
  resource == Resource::"rztvfpgexbyo"
) when {
  true
};permit(
  principal == Principal::"ouznuhipyrde",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"tuejactfyjvq",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"hkzemtizuffk",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"hkzemtizuffk",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"pmbgzlpqhwtt",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"tmflejujpxgy"
) when {
  true
};forbid(
  principal,
  action == Action::"pmbgzlpqhwtt",
  resource == Resource::"csxgwejjfmtd"
) when {
  true
};permit(
  principal == Principal::"upmbapjjzlqg",
  action,
  resource == Resource::"lrphelnbfngz"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"jhclfobmdwpf"
) when {
  true
};permit(
  principal == Principal::"wnrshhgczenb",
  action == Action::"zvmjlaycwsic",
  resource == Resource::"odyfpogljjnv"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"csxgwejjfmtd"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"wklzlcpofspa"
) when {
  true
};permit(
  principal == Principal::"oplfajvsfhum",
  action == Action::"dfxkgkzvvgjj",
  resource
) when {
  true
};permit(
  principal == Principal::"nzmhpiijyqgc",
  action == Action::"hxgvouhigrtg",
  resource == Resource::"mywmelxqqfuv"
) when {
  true
};permit(
  principal == Principal::"ydfpudehdevu",
  action == Action::"hkzemtizuffk",
  resource == Resource::"wklzlcpofspa"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"qhzwkxmbaapi"
) when {
  true
};forbid(
  principal == Principal::"llgjczrllofa",
  action == Action::"rpzvjuqnlrqc",
  resource == Resource::"iyiqaaijwmza"
) when {
  true
};permit(
  principal == Principal::"llgjczrllofa",
  action == Action::"kdauwrdmrleu",
  resource
) when {
  true
};permit(
  principal == Principal::"ydfpudehdevu",
  action,
  resource == Resource::"tvrrfxcopnub"
) when {
  true
};permit(
  principal,
  action == Action::"jvdddloawjbw",
  resource == Resource::"hpjrwoimghfc"
) when {
  true
};forbid(
  principal == Principal::"thqnjxlaoecw",
  action == Action::"jvdddloawjbw",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"grmmnuaphkzu",
  resource
) when {
  true
};forbid(
  principal == Principal::"llgjczrllofa",
  action == Action::"jxquuptatzpv",
  resource
) when {
  true
};forbid(
  principal == Principal::"ctaqtgzsothe",
  action == Action::"jvdddloawjbw",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"nracctrvdoax",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"nracctrvdoax",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"gcxlbrbdjria",
  resource
) when {
  true
};permit(
  principal == Principal::"esjqlfptglke",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"oiplgknnrivn",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"odyfpogljjnv"
) when {
  true
};forbid(
  principal == Principal::"dxtpbwjminto",
  action == Action::"hxgvouhigrtg",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"gcxlbrbdjria",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"pmbgzlpqhwtt",
  resource == Resource::"tmflejujpxgy"
) when {
  true
};forbid(
  principal == Principal::"exxuksxawydq",
  action == Action::"aolugamlrdtr",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"wklzlcpofspa"
) when {
  true
};permit(
  principal == Principal::"hlefznmhyehb",
  action == Action::"qtrsqesmdarr",
  resource == Resource::"dvvacnqjjkev"
) when {
  true
};permit(
  principal == Principal::"exxuksxawydq",
  action == Action::"rpzvjuqnlrqc",
  resource
) when {
  true
};permit(
  principal == Principal::"request",
  action == Action::"request",
  resource == Resource::"request"
) when {
  true
};permit(
  principal == Principal::"ymtinnmmouik",
  action == Action::"aswutawaetwu",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"pmbgzlpqhwtt",
  resource == Resource::"qhzwkxmbaapi"
) when {
  true
};forbid(
  principal == Principal::"hlefznmhyehb",
  action == Action::"rftufoyrblii",
  resource == Resource::"rztvfpgexbyo"
) when {
  true
};forbid(
  principal == Principal::"ehpigjrlpcyh",
  action == Action::"kdauwrdmrleu",
  resource
) when {
  true
};permit(
  principal == Principal::"srlvvfsggbij",
  action,
  resource == Resource::"tvrrfxcopnub"
) when {
  true
};forbid(
  principal == Principal::"oplfajvsfhum",
  action,
  resource == Resource::"qhzwkxmbaapi"
) when {
  true
};forbid(
  principal == Principal::"oiplgknnrivn",
  action,
  resource == Resource::"jmcgzxzxmcst"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"qhzwkxmbaapi"
) when {
  true
};permit(
  principal == Principal::"wbkavkcmrjxi",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"hinhocbgarpz",
  action,
  resource == Resource::"vzzmbsnbulkj"
) when {
  true
};forbid(
  principal == Principal::"kgoodiztambd",
  action,
  resource == Resource::"dvvacnqjjkev"
) when {
  true
};forbid(
  principal,
  action == Action::"jrhudharjvrw",
  resource == Resource::"odyfpogljjnv"
) when {
  true
};permit(
  principal == Principal::"wbkavkcmrjxi",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"llgjczrllofa",
  action,
  resource == Resource::"odyfpogljjnv"
) when {
  true
};forbid(
  principal == Principal::"npxdnvuxefcj",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"thqnjxlaoecw",
  action == Action::"jxquuptatzpv",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"idmufcmpqszm"
) when {
  true
};permit(
  principal,
  action == Action::"tuejactfyjvq",
  resource == Resource::"yayibaaplcjj"
) when {
  true
};permit(
  principal == Principal::"oiplgknnrivn",
  action == Action::"gywhlyjwvlsm",
  resource == Resource::"qhzwkxmbaapi"
) when {
  true
};forbid(
  principal == Principal::"renbzooexuzm",
  action == Action::"qtrsqesmdarr",
  resource
) when {
  true
};forbid(
  principal == Principal::"tvfarvxxoaka",
  action == Action::"gcxlbrbdjria",
  resource == Resource::"eodbgltheiii"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"hpjrwoimghfc"
) when {
  true
};forbid(
  principal == Principal::"oplfajvsfhum",
  action == Action::"gcxlbrbdjria",
  resource
) when {
  true
};forbid(
  principal == Principal::"wbkavkcmrjxi",
  action,
  resource == Resource::"xxspcbffjlim"
) when {
  true
};permit(
  principal,
  action == Action::"kftxzwnrlldb",
  resource == Resource::"odyfpogljjnv"
) when {
  true
};forbid(
  principal,
  action == Action::"gywhlyjwvlsm",
  resource == Resource::"dvvacnqjjkev"
) when {
  true
};permit(
  principal == Principal::"fgcazjyngaxd",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"nzmhpiijyqgc",
  action == Action::"ghihlhdluigw",
  resource == Resource::"knebrvyyiuxk"
) when {
  true
};permit(
  principal == Principal::"oplfajvsfhum",
  action,
  resource == Resource::"vzzmbsnbulkj"
) when {
  true
};permit(
  principal,
  action == Action::"rftufoyrblii",
  resource == Resource::"yayibaaplcjj"
) when {
  true
};permit(
  principal,
  action == Action::"zusnvrjasagx",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"aswutawaetwu",
  resource == Resource::"csxgwejjfmtd"
) when {
  true
};permit(
  principal,
  action == Action::"ghihlhdluigw",
  resource == Resource::"picvrddcwolz"
) when {
  true
};forbid(
  principal,
  action == Action::"dfxkgkzvvgjj",
  resource == Resource::"ifexyeszgfru"
) when {
  true
};forbid(
  principal == Principal::"igzldnmwpgpe",
  action == Action::"vwedmvcfufxr",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"yqbutptmsvxp",
  resource == Resource::"eduesuifatqx"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"wklzlcpofspa"
) when {
  true
};permit(
  principal == Principal::"ydfpudehdevu",
  action == Action::"kdauwrdmrleu",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"vwedmvcfufxr",
  resource == Resource::"mywmelxqqfuv"
) when {
  true
};forbid(
  principal == Principal::"thqnjxlaoecw",
  action == Action::"jxquuptatzpv",
  resource
) when {
  true
};forbid(
  principal == Principal::"srlvvfsggbij",
  action == Action::"rpzvjuqnlrqc",
  resource == Resource::"eodbgltheiii"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"revnqysbvwxh"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"csxgwejjfmtd"
) when {
  true
};