permit(
  principal,
  action,
  resource == Resource::"ufxehwwylhqj"
) when {
  true
};forbid(
  principal,
  action == Action::"xyhentdazroo",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"gxhvdqrhanus",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"mkduuefsqjin",
  resource
) when {
  true
};forbid(
  principal == Principal::"avamxqxapusi",
  action == Action::"xogtugtufpio",
  resource
) when {
  true
};forbid(
  principal == Principal::"sludhqqsebhq",
  action == Action::"kmmdmzawbtmn",
  resource
) when {
  true
};forbid(
  principal == Principal::"aclbryxsxfyj",
  action == Action::"dkjucoyvvejj",
  resource == Resource::"xpwesblvpcem"
) when {
  true
};permit(
  principal == Principal::"zqgyoamnrwxe",
  action,
  resource == Resource::"vfxvwffixfvl"
) when {
  true
};permit(
  principal == Principal::"spblinmqzsnj",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"dkjucoyvvejj",
  resource == Resource::"pxqidkvuyeyk"
) when {
  true
};permit(
  principal == Principal::"muykyaetdjil",
  action,
  resource == Resource::"vfxvwffixfvl"
) when {
  true
};forbid(
  principal,
  action == Action::"xthpxtcycvtw",
  resource == Resource::"pkclsknhcitg"
) when {
  true
};permit(
  principal == Principal::"vosagpuhytnn",
  action,
  resource == Resource::"zzpeuyoffyyl"
) when {
  true
};permit(
  principal,
  action == Action::"oiwehxgdmsoz",
  resource == Resource::"lxloxqchsiit"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ngleaghkkqkl"
) when {
  true
};forbid(
  principal,
  action == Action::"xthpxtcycvtw",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"uzkypsepnfkq"
) when {
  true
};permit(
  principal == Principal::"evifnurgfxmq",
  action,
  resource == Resource::"vfxvwffixfvl"
) when {
  true
};permit(
  principal == Principal::"sludhqqsebhq",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"kkpqckuwovts",
  action == Action::"ffpyzsuhqpma",
  resource
) when {
  true
};permit(
  principal == Principal::"cbkxrhvjfknq",
  action,
  resource == Resource::"ngleaghkkqkl"
) when {
  true
};permit(
  principal == Principal::"aclbryxsxfyj",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"vosagpuhytnn",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"avamxqxapusi",
  action == Action::"kpenccwxxdhk",
  resource == Resource::"xpwesblvpcem"
) when {
  true
};permit(
  principal == Principal::"kkpqckuwovts",
  action == Action::"kmmdmzawbtmn",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"swgiaedlfmeq",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"gxhvdqrhanus",
  resource == Resource::"jzdlzsqiyudi"
) when {
  true
};forbid(
  principal == Principal::"oftjhoubcnpb",
  action == Action::"ffpyzsuhqpma",
  resource
) when {
  true
};forbid(
  principal == Principal::"townrmqglgjp",
  action == Action::"jqcbehdrxfmk",
  resource
) when {
  true
};permit(
  principal == Principal::"zqgyoamnrwxe",
  action,
  resource == Resource::"pkclsknhcitg"
) when {
  true
};permit(
  principal,
  action == Action::"jyjinrnskgwb",
  resource == Resource::"aegithqouyox"
) when {
  true
};forbid(
  principal,
  action == Action::"qpzmyotjzmun",
  resource == Resource::"kijpfkkbtjkz"
) when {
  true
};permit(
  principal == Principal::"xzyebkaqeifw",
  action,
  resource == Resource::"hinqilloqzfk"
) when {
  true
};forbid(
  principal == Principal::"wlqwqvonlboa",
  action,
  resource == Resource::"ufxehwwylhqj"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"exmqsycewxyj"
) when {
  true
};permit(
  principal == Principal::"townrmqglgjp",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"townrmqglgjp",
  action,
  resource == Resource::"pqlhtcnkvoaf"
) when {
  true
};forbid(
  principal == Principal::"ashigbletiat",
  action,
  resource == Resource::"aegithqouyox"
) when {
  true
};permit(
  principal == Principal::"uspeawwrmjoe",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"bhvvwydkjbkr",
  resource == Resource::"pkclsknhcitg"
) when {
  true
};forbid(
  principal,
  action == Action::"xyhentdazroo",
  resource == Resource::"jxowagxgdpzc"
) when {
  true
};forbid(
  principal == Principal::"pymoshlkpumz",
  action == Action::"oiwehxgdmsoz",
  resource == Resource::"wmytlvfdtwqh"
) when {
  true
};permit(
  principal == Principal::"aclbryxsxfyj",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"zqgyoamnrwxe",
  action,
  resource == Resource::"kijpfkkbtjkz"
) when {
  true
};permit(
  principal == Principal::"sludhqqsebhq",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"axiumvhamdms"
) when {
  true
};permit(
  principal,
  action == Action::"kmmdmzawbtmn",
  resource == Resource::"aegithqouyox"
) when {
  true
};forbid(
  principal == Principal::"kkpqckuwovts",
  action,
  resource == Resource::"pqlhtcnkvoaf"
) when {
  true
};permit(
  principal == Principal::"xzyebkaqeifw",
  action,
  resource == Resource::"exmqsycewxyj"
) when {
  true
};permit(
  principal == Principal::"avamxqxapusi",
  action == Action::"pkpmsrgqiicn",
  resource
) when {
  true
};permit(
  principal == Principal::"ashigbletiat",
  action,
  resource == Resource::"wmytlvfdtwqh"
) when {
  true
};permit(
  principal,
  action == Action::"osknoogelxye",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"yuxabgxhzxxi",
  resource
) when {
  true
};forbid(
  principal == Principal::"dfcjvuduqjbp",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"yuxabgxhzxxi",
  resource == Resource::"lzrlgwouqbwk"
) when {
  true
};permit(
  principal == Principal::"qtpcsxoezpyr",
  action == Action::"pkpmsrgqiicn",
  resource
) when {
  true
};permit(
  principal == Principal::"mqhxabirwodw",
  action == Action::"ffpyzsuhqpma",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"kpenccwxxdhk",
  resource
) when {
  true
};forbid(
  principal == Principal::"rriiyxabvpqx",
  action == Action::"kpenccwxxdhk",
  resource == Resource::"ufxehwwylhqj"
) when {
  true
};permit(
  principal,
  action == Action::"xyhentdazroo",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"swgiaedlfmeq",
  resource
) when {
  true
};permit(
  principal == Principal::"request",
  action == Action::"request",
  resource == Resource::"request"
) when {
  true
};forbid(
  principal == Principal::"uspeawwrmjoe",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"rpctraapneky"
) when {
  true
};forbid(
  principal == Principal::"evifnurgfxmq",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"rriiyxabvpqx",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"ybdutoiozfrb",
  action == Action::"pvacelurcpvn",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"zzpeuyoffyyl"
) when {
  true
};permit(
  principal == Principal::"townrmqglgjp",
  action == Action::"yuxabgxhzxxi",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"aegithqouyox"
) when {
  true
};forbid(
  principal,
  action == Action::"munaoyzabpue",
  resource
) when {
  true
};forbid(
  principal == Principal::"xzyebkaqeifw",
  action,
  resource == Resource::"exiabhgwfljy"
) when {
  true
};forbid(
  principal,
  action == Action::"kmmdmzawbtmn",
  resource == Resource::"lxloxqchsiit"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"wmytlvfdtwqh"
) when {
  true
};permit(
  principal == Principal::"sxsgvsdccnzv",
  action == Action::"munaoyzabpue",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"rpctraapneky"
) when {
  true
};forbid(
  principal == Principal::"townrmqglgjp",
  action == Action::"kmmdmzawbtmn",
  resource == Resource::"jxowagxgdpzc"
) when {
  true
};forbid(
  principal == Principal::"sxsgvsdccnzv",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"pxqidkvuyeyk"
) when {
  true
};permit(
  principal == Principal::"oftjhoubcnpb",
  action == Action::"yrpxvuxdkzop",
  resource
) when {
  true
};forbid(
  principal == Principal::"qtpcsxoezpyr",
  action == Action::"kumnrtfhfpgr",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"fskqnkzqmtow",
  resource
) when {
  true
};permit(
  principal == Principal::"ashigbletiat",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"rriiyxabvpqx",
  action == Action::"cnsyzechuqlt",
  resource == Resource::"wmytlvfdtwqh"
) when {
  true
};forbid(
  principal == Principal::"mpgqeyqtgcad",
  action == Action::"pvacelurcpvn",
  resource
) when {
  true
};permit(
  principal == Principal::"tzxkhatenpaq",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"lexzhkcxvzwl",
  action == Action::"oiwehxgdmsoz",
  resource
) when {
  true
};forbid(
  principal == Principal::"mylxwtwvqkhd",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"ybdutoiozfrb",
  action == Action::"xogtugtufpio",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"cnsyzechuqlt",
  resource
) when {
  true
};forbid(
  principal == Principal::"lqxizinmmdiw",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"wlqwqvonlboa",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"xxpqcnpxpfpi"
) when {
  true
};permit(
  principal == Principal::"oftjhoubcnpb",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"eujzntcqwwkd",
  action,
  resource == Resource::"pkclsknhcitg"
) when {
  true
};permit(
  principal == Principal::"qtpcsxoezpyr",
  action == Action::"bhvvwydkjbkr",
  resource == Resource::"rpctraapneky"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"cagxhwhndvwu"
) when {
  true
};forbid(
  principal == Principal::"oftjhoubcnpb",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"ashigbletiat",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"kijpfkkbtjkz"
) when {
  true
};forbid(
  principal == Principal::"kkpqckuwovts",
  action,
  resource
) when {
  true
};