permit(
  principal == Principal::"dispcfnvmsbk",
  action,
  resource == Resource::"wthwwbztubhr"
) when {
  true
};permit(
  principal == Principal::"jqocyhrsmqjt",
  action,
  resource == Resource::"ulznxoseohpu"
) when {
  true
};permit(
  principal,
  action == Action::"cylquarfmrwe",
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal,
  action == Action::"drklrhusxiix",
  resource == Resource::"jglopfkzivcy"
) when {
  true
};forbid(
  principal == Principal::"rgzdhgznrmmx",
  action == Action::"dqfvsmwvnxlj",
  resource
) when {
  true
};permit(
  principal == Principal::"zecopqcenfgq",
  action == Action::"wegbeghgfeps",
  resource == Resource::"jglopfkzivcy"
) when {
  true
};forbid(
  principal,
  action == Action::"kmbdwspkvtfg",
  resource
) when {
  true
};permit(
  principal == Principal::"chrumrstfrtw",
  action == Action::"gbzjaithkydf",
  resource
) when {
  true
};permit(
  principal == Principal::"kwvjsetpsmlt",
  action == Action::"yysewqkamtqj",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"gisdxyeyrolr"
) when {
  true
};forbid(
  principal == Principal::"clpwwnowcfxq",
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};permit(
  principal == Principal::"dflbksifozhy",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"nzvgzgtjqjen",
  resource
) when {
  true
};forbid(
  principal == Principal::"pdqaqryvzlsq",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"uadsypfdkadt",
  resource
) when {
  true
};permit(
  principal == Principal::"mrlwamjjaiwr",
  action == Action::"pbklvwalhytz",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"inchvedkmfon"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"wthwwbztubhr"
) when {
  true
};forbid(
  principal == Principal::"xbuqbeudwgxh",
  action,
  resource == Resource::"jglopfkzivcy"
) when {
  true
};permit(
  principal == Principal::"vhsewusivvyz",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};permit(
  principal,
  action == Action::"doqfseeyzrpi",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"nwztsonbjwas"
) when {
  true
};forbid(
  principal == Principal::"vhsewusivvyz",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};forbid(
  principal,
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"yysewqkamtqj",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"yypwsijfobaw",
  resource
) when {
  true
};permit(
  principal == Principal::"ofgyatrijmgo",
  action == Action::"ykpsxanrepau",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"yypwsijfobaw",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"zyxdtvryguyl",
  resource == Resource::"elxkfuidmbqq"
) when {
  true
};permit(
  principal == Principal::"dispcfnvmsbk",
  action == Action::"wegbeghgfeps",
  resource
) when {
  true
};permit(
  principal == Principal::"dflbksifozhy",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"pyhrmdcufcqx",
  action,
  resource == Resource::"pqwnanlakjop"
) when {
  true
};permit(
  principal == Principal::"whavzicbxxlv",
  action == Action::"kejhfvxakgif",
  resource
) when {
  true
};permit(
  principal == Principal::"rpsvssietntf",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"xokttubgjsye"
) when {
  true
};permit(
  principal == Principal::"kogrqztpluqo",
  action == Action::"dqfvsmwvnxlj",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"yypwsijfobaw",
  resource
) when {
  true
};forbid(
  principal == Principal::"zjyrhpjscbbp",
  action == Action::"pfjozsmouwdr",
  resource
) when {
  true
};forbid(
  principal == Principal::"rpsvssietntf",
  action == Action::"wjsugdswubof",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal,
  action == Action::"llnqeaclsamg",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"xenqqlcueghi",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"pqwnanlakjop"
) when {
  true
};forbid(
  principal == Principal::"kwvjsetpsmlt",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"uifdrmilqkbk",
  action,
  resource == Resource::"qwttuibrbbgr"
) when {
  true
};permit(
  principal == Principal::"xzdnnodrqapi",
  action,
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};forbid(
  principal == Principal::"kwvjsetpsmlt",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"chrumrstfrtw",
  action,
  resource == Resource::"gqffhvppakdw"
) when {
  true
};permit(
  principal == Principal::"zecopqcenfgq",
  action,
  resource == Resource::"czrozycfjskx"
) when {
  true
};forbid(
  principal,
  action == Action::"yysewqkamtqj",
  resource
) when {
  true
};permit(
  principal == Principal::"ssjclvttqfxe",
  action,
  resource == Resource::"xwhjixkfjnxs"
) when {
  true
};permit(
  principal == Principal::"ofgyatrijmgo",
  action,
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};forbid(
  principal == Principal::"yvmdixfqccis",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"pbklvwalhytz",
  resource
) when {
  true
};permit(
  principal == Principal::"qrpzhkydumww",
  action == Action::"pbklvwalhytz",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"czrozycfjskx"
) when {
  true
};permit(
  principal,
  action == Action::"nzvgzgtjqjen",
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};permit(
  principal == Principal::"velciusvmoxg",
  action,
  resource == Resource::"xtgcvhtqyjuf"
) when {
  true
};forbid(
  principal == Principal::"ssjclvttqfxe",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"amvmeibzxmsx",
  action == Action::"yecncgfardrl",
  resource == Resource::"qwttuibrbbgr"
) when {
  true
};permit(
  principal,
  action == Action::"dqfvsmwvnxlj",
  resource == Resource::"dwftjhqwiake"
) when {
  true
};forbid(
  principal == Principal::"uifdrmilqkbk",
  action == Action::"yysewqkamtqj",
  resource == Resource::"nwztsonbjwas"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"jglopfkzivcy"
) when {
  true
};forbid(
  principal == Principal::"uifdrmilqkbk",
  action == Action::"gbzjaithkydf",
  resource == Resource::"oldrrovawflz"
) when {
  true
};forbid(
  principal == Principal::"wmddwgyhrjgx",
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};forbid(
  principal == Principal::"mziqzwabfbrh",
  action,
  resource == Resource::"wthwwbztubhr"
) when {
  true
};permit(
  principal == Principal::"vhsewusivvyz",
  action == Action::"wjsugdswubof",
  resource
) when {
  true
};forbid(
  principal == Principal::"chrumrstfrtw",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"pyhrmdcufcqx",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"yvjjzrpmacol",
  action == Action::"eznkoftfugqe",
  resource == Resource::"biwuwymeckvq"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ajbutxryzsra"
) when {
  true
};permit(
  principal == Principal::"velciusvmoxg",
  action == Action::"kmbdwspkvtfg",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"adseqgfmvjbb",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"wegbeghgfeps",
  resource == Resource::"gqffhvppakdw"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};forbid(
  principal == Principal::"bgtjiynturjo",
  action == Action::"xapzhjcbzdlc",
  resource == Resource::"elxkfuidmbqq"
) when {
  true
};permit(
  principal,
  action == Action::"ykpsxanrepau",
  resource == Resource::"pqwnanlakjop"
) when {
  true
};forbid(
  principal,
  action == Action::"llnqeaclsamg",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"bmsqxkwwmxbd",
  resource == Resource::"elxkfuidmbqq"
) when {
  true
};forbid(
  principal == Principal::"vhsewusivvyz",
  action == Action::"yecncgfardrl",
  resource
) when {
  true
};forbid(
  principal == Principal::"pyhrmdcufcqx",
  action == Action::"gbzjaithkydf",
  resource
) when {
  true
};forbid(
  principal == Principal::"jqocyhrsmqjt",
  action == Action::"pbklvwalhytz",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};forbid(
  principal == Principal::"vhsewusivvyz",
  action == Action::"dqfvsmwvnxlj",
  resource == Resource::"qwttuibrbbgr"
) when {
  true
};permit(
  principal == Principal::"dflbksifozhy",
  action == Action::"bmsqxkwwmxbd",
  resource == Resource::"czrozycfjskx"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"gisdxyeyrolr"
) when {
  true
};permit(
  principal == Principal::"ssjclvttqfxe",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"xapzhjcbzdlc",
  resource
) when {
  true
};permit(
  principal == Principal::"whavzicbxxlv",
  action == Action::"eznkoftfugqe",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"ajbutxryzsra"
) when {
  true
};forbid(
  principal == Principal::"pyhrmdcufcqx",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"dqfvsmwvnxlj",
  resource
) when {
  true
};permit(
  principal == Principal::"dispcfnvmsbk",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"ykpsxanrepau",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"wegbeghgfeps",
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};permit(
  principal == Principal::"yvjjzrpmacol",
  action,
  resource == Resource::"dwftjhqwiake"
) when {
  true
};forbid(
  principal == Principal::"kogrqztpluqo",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"vhsewusivvyz",
  action,
  resource == Resource::"gqffhvppakdw"
) when {
  true
};permit(
  principal,
  action == Action::"uggkhcwckerj",
  resource
) when {
  true
};forbid(
  principal == Principal::"ssjclvttqfxe",
  action == Action::"oxehxgadwqvr",
  resource
) when {
  true
};forbid(
  principal == Principal::"jneydhxtsaoc",
  action == Action::"yypwsijfobaw",
  resource == Resource::"xtgcvhtqyjuf"
) when {
  true
};permit(
  principal == Principal::"xbuqbeudwgxh",
  action == Action::"ykpsxanrepau",
  resource
) when {
  true
};permit(
  principal == Principal::"ssjclvttqfxe",
  action,
  resource == Resource::"elxkfuidmbqq"
) when {
  true
};permit(
  principal,
  action == Action::"ykpsxanrepau",
  resource == Resource::"elxkfuidmbqq"
) when {
  true
};permit(
  principal == Principal::"amvmeibzxmsx",
  action == Action::"kmbdwspkvtfg",
  resource == Resource::"forqvcikcjnd"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"dwftjhqwiake"
) when {
  true
};permit(
  principal,
  action == Action::"wjsugdswubof",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"gisdxyeyrolr"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"srxwbjqzxrgh"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};permit(
  principal == Principal::"whavzicbxxlv",
  action,
  resource == Resource::"xokttubgjsye"
) when {
  true
};permit(
  principal,
  action == Action::"yimrpeazjxlz",
  resource
) when {
  true
};forbid(
  principal == Principal::"kogrqztpluqo",
  action,
  resource == Resource::"gisdxyeyrolr"
) when {
  true
};forbid(
  principal,
  action == Action::"eznkoftfugqe",
  resource
) when {
  true
};forbid(
  principal == Principal::"bgtjiynturjo",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"jneydhxtsaoc",
  action,
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};permit(
  principal,
  action == Action::"yysewqkamtqj",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"xapzhjcbzdlc",
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"gqffhvppakdw"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"xwhjixkfjnxs"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"ajbutxryzsra"
) when {
  true
};permit(
  principal,
  action == Action::"sdqpabgkumia",
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};permit(
  principal == Principal::"kchpgcobubqo",
  action,
  resource == Resource::"dwftjhqwiake"
) when {
  true
};forbid(
  principal == Principal::"vqpwqtnuabqh",
  action == Action::"cylquarfmrwe",
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};forbid(
  principal == Principal::"kchpgcobubqo",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"wmddwgyhrjgx",
  action == Action::"sdqpabgkumia",
  resource
) when {
  true
};permit(
  principal == Principal::"kwvjsetpsmlt",
  action,
  resource == Resource::"biwuwymeckvq"
) when {
  true
};permit(
  principal == Principal::"jneydhxtsaoc",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"yypwsijfobaw",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"oxehxgadwqvr",
  resource
) when {
  true
};forbid(
  principal == Principal::"kwvjsetpsmlt",
  action == Action::"xapzhjcbzdlc",
  resource
) when {
  true
};permit(
  principal == Principal::"amvmeibzxmsx",
  action == Action::"pfjozsmouwdr",
  resource == Resource::"vavxdjglsofu"
) when {
  true
};forbid(
  principal == Principal::"kogrqztpluqo",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"request",
  action == Action::"request",
  resource == Resource::"request"
) when {
  true
};permit(
  principal == Principal::"ofgyatrijmgo",
  action == Action::"eznkoftfugqe",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"wjsugdswubof",
  resource
) when {
  true
};permit(
  principal == Principal::"yvjjzrpmacol",
  action == Action::"xapzhjcbzdlc",
  resource == Resource::"drwyrjwaheeo"
) when {
  true
};permit(
  principal,
  action == Action::"kmbdwspkvtfg",
  resource == Resource::"nwztsonbjwas"
) when {
  true
};forbid(
  principal == Principal::"vqpwqtnuabqh",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"adseqgfmvjbb",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"wlsuxufpqtmr",
  resource == Resource::"nwztsonbjwas"
) when {
  true
};permit(
  principal == Principal::"wmddwgyhrjgx",
  action == Action::"yysewqkamtqj",
  resource == Resource::"ajbutxryzsra"
) when {
  true
};forbid(
  principal == Principal::"bgtjiynturjo",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"yvjjzrpmacol",
  action,
  resource == Resource::"elxkfuidmbqq"
) when {
  true
};forbid(
  principal,
  action == Action::"llnqeaclsamg",
  resource
) when {
  true
};forbid(
  principal == Principal::"jneydhxtsaoc",
  action == Action::"wlsuxufpqtmr",
  resource
) when {
  true
};permit(
  principal == Principal::"ofgyatrijmgo",
  action == Action::"doqfseeyzrpi",
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};forbid(
  principal == Principal::"vhsewusivvyz",
  action,
  resource == Resource::"xokttubgjsye"
) when {
  true
};permit(
  principal,
  action == Action::"xapzhjcbzdlc",
  resource
) when {
  true
};forbid(
  principal == Principal::"zjyrhpjscbbp",
  action == Action::"llnqeaclsamg",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"inchvedkmfon"
) when {
  true
};forbid(
  principal == Principal::"zecopqcenfgq",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"zjyrhpjscbbp",
  action == Action::"yecncgfardrl",
  resource == Resource::"dwftjhqwiake"
) when {
  true
};forbid(
  principal,
  action == Action::"eznkoftfugqe",
  resource
) when {
  true
};forbid(
  principal == Principal::"bgtjiynturjo",
  action == Action::"drklrhusxiix",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"dqfvsmwvnxlj",
  resource
) when {
  true
};permit(
  principal == Principal::"rgzdhgznrmmx",
  action == Action::"adseqgfmvjbb",
  resource
) when {
  true
};forbid(
  principal == Principal::"yvjjzrpmacol",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"clpwwnowcfxq",
  action == Action::"wegbeghgfeps",
  resource == Resource::"dwftjhqwiake"
) when {
  true
};forbid(
  principal == Principal::"bgtjiynturjo",
  action == Action::"wegbeghgfeps",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"gecxhbsbcexd",
  resource == Resource::"ulznxoseohpu"
) when {
  true
};permit(
  principal == Principal::"velciusvmoxg",
  action,
  resource == Resource::"elxkfuidmbqq"
) when {
  true
};permit(
  principal == Principal::"amvmeibzxmsx",
  action == Action::"yimrpeazjxlz",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"sdqpabgkumia",
  resource
) when {
  true
};forbid(
  principal == Principal::"rgzdhgznrmmx",
  action,
  resource == Resource::"wthwwbztubhr"
) when {
  true
};forbid(
  principal == Principal::"vhsewusivvyz",
  action == Action::"bmsqxkwwmxbd",
  resource == Resource::"czrozycfjskx"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"gisdxyeyrolr"
) when {
  true
};forbid(
  principal == Principal::"xzdnnodrqapi",
  action,
  resource == Resource::"ikpbtpdgplxh"
) when {
  true
};forbid(
  principal == Principal::"ofgyatrijmgo",
  action == Action::"pbklvwalhytz",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"ykpsxanrepau",
  resource == Resource::"jbxgvzkebjva"
) when {
  true
};permit(
  principal == Principal::"zecopqcenfgq",
  action == Action::"wegbeghgfeps",
  resource
) when {
  true
};forbid(
  principal == Principal::"kwvjsetpsmlt",
  action == Action::"doqfseeyzrpi",
  resource
) when {
  true
};permit(
  principal == Principal::"wmddwgyhrjgx",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"bmsqxkwwmxbd",
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};forbid(
  principal == Principal::"pyhrmdcufcqx",
  action == Action::"pbklvwalhytz",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"dwftjhqwiake"
) when {
  true
};permit(
  principal,
  action == Action::"eznkoftfugqe",
  resource == Resource::"oqrbyaozcasi"
) when {
  true
};forbid(
  principal == Principal::"qrpzhkydumww",
  action,
  resource == Resource::"xokttubgjsye"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"vavxdjglsofu"
) when {
  true
};forbid(
  principal == Principal::"ofgyatrijmgo",
  action == Action::"sdqpabgkumia",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"eznkoftfugqe",
  resource
) when {
  true
};permit(
  principal == Principal::"ssjclvttqfxe",
  action == Action::"kmbdwspkvtfg",
  resource
) when {
  true
};permit(
  principal == Principal::"yvmdixfqccis",
  action,
  resource == Resource::"dwftjhqwiake"
) when {
  true
};forbid(
  principal == Principal::"kchpgcobubqo",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"oxehxgadwqvr",
  resource
) when {
  true
};forbid(
  principal == Principal::"vhsewusivvyz",
  action == Action::"llnqeaclsamg",
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};forbid(
  principal == Principal::"velciusvmoxg",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"clpwwnowcfxq",
  action == Action::"yimrpeazjxlz",
  resource
) when {
  true
};permit(
  principal == Principal::"kogrqztpluqo",
  action,
  resource == Resource::"vavxdjglsofu"
) when {
  true
};forbid(
  principal,
  action == Action::"wjsugdswubof",
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};forbid(
  principal == Principal::"wmddwgyhrjgx",
  action,
  resource == Resource::"forqvcikcjnd"
) when {
  true
};forbid(
  principal == Principal::"rpsvssietntf",
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};forbid(
  principal == Principal::"pyhrmdcufcqx",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"zjyrhpjscbbp",
  action == Action::"bmsqxkwwmxbd",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"nwztsonbjwas"
) when {
  true
};forbid(
  principal == Principal::"wmddwgyhrjgx",
  action == Action::"zyxdtvryguyl",
  resource
) when {
  true
};permit(
  principal == Principal::"clpwwnowcfxq",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"uifdrmilqkbk",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"kogrqztpluqo",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"rgzdhgznrmmx",
  action,
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};permit(
  principal,
  action == Action::"yecncgfardrl",
  resource == Resource::"pqwnanlakjop"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};permit(
  principal == Principal::"bgtjiynturjo",
  action == Action::"uadsypfdkadt",
  resource
) when {
  true
};permit(
  principal == Principal::"xzdnnodrqapi",
  action == Action::"sdqpabgkumia",
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};permit(
  principal,
  action == Action::"nzvgzgtjqjen",
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};permit(
  principal,
  action == Action::"xenqqlcueghi",
  resource
) when {
  true
};permit(
  principal == Principal::"kwvjsetpsmlt",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"kmbdwspkvtfg",
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};forbid(
  principal == Principal::"bgtjiynturjo",
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};permit(
  principal == Principal::"xbuqbeudwgxh",
  action == Action::"wlsuxufpqtmr",
  resource
) when {
  true
};permit(
  principal == Principal::"whavzicbxxlv",
  action == Action::"gbzjaithkydf",
  resource == Resource::"dwftjhqwiake"
) when {
  true
};permit(
  principal == Principal::"dflbksifozhy",
  action == Action::"bmsqxkwwmxbd",
  resource
) when {
  true
};forbid(
  principal == Principal::"rpsvssietntf",
  action,
  resource == Resource::"inchvedkmfon"
) when {
  true
};permit(
  principal,
  action == Action::"ykpsxanrepau",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"wjsugdswubof",
  resource == Resource::"wthwwbztubhr"
) when {
  true
};forbid(
  principal == Principal::"yvjjzrpmacol",
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};forbid(
  principal == Principal::"ssjclvttqfxe",
  action == Action::"kmbdwspkvtfg",
  resource == Resource::"vavxdjglsofu"
) when {
  true
};forbid(
  principal == Principal::"kchpgcobubqo",
  action == Action::"cylquarfmrwe",
  resource == Resource::"inchvedkmfon"
) when {
  true
};permit(
  principal,
  action == Action::"pbklvwalhytz",
  resource
) when {
  true
};permit(
  principal == Principal::"yvjjzrpmacol",
  action == Action::"kmbdwspkvtfg",
  resource == Resource::"ikpbtpdgplxh"
) when {
  true
};permit(
  principal,
  action == Action::"dqfvsmwvnxlj",
  resource == Resource::"biwuwymeckvq"
) when {
  true
};forbid(
  principal == Principal::"whavzicbxxlv",
  action == Action::"xapzhjcbzdlc",
  resource == Resource::"inchvedkmfon"
) when {
  true
};forbid(
  principal == Principal::"amvmeibzxmsx",
  action == Action::"yimrpeazjxlz",
  resource
) when {
  true
};forbid(
  principal == Principal::"jqocyhrsmqjt",
  action == Action::"zyxdtvryguyl",
  resource == Resource::"czrozycfjskx"
) when {
  true
};permit(
  principal == Principal::"yvjjzrpmacol",
  action,
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"styepjegwuco"
) when {
  true
};permit(
  principal == Principal::"xbuqbeudwgxh",
  action == Action::"xapzhjcbzdlc",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal == Principal::"yvmdixfqccis",
  action,
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};forbid(
  principal == Principal::"velciusvmoxg",
  action == Action::"dqfvsmwvnxlj",
  resource
) when {
  true
};forbid(
  principal == Principal::"wmddwgyhrjgx",
  action,
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};permit(
  principal == Principal::"bgtjiynturjo",
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};permit(
  principal == Principal::"whavzicbxxlv",
  action == Action::"doqfseeyzrpi",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"gkmzlzkyizur",
  resource == Resource::"gisdxyeyrolr"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"wthwwbztubhr"
) when {
  true
};forbid(
  principal == Principal::"rpsvssietntf",
  action,
  resource == Resource::"jglopfkzivcy"
) when {
  true
};permit(
  principal,
  action == Action::"kejhfvxakgif",
  resource
) when {
  true
};forbid(
  principal == Principal::"yvmdixfqccis",
  action == Action::"gbzjaithkydf",
  resource == Resource::"wthwwbztubhr"
) when {
  true
};forbid(
  principal,
  action == Action::"wegbeghgfeps",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal == Principal::"clpwwnowcfxq",
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};permit(
  principal == Principal::"jneydhxtsaoc",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"kejhfvxakgif",
  resource == Resource::"xtgcvhtqyjuf"
) when {
  true
};permit(
  principal == Principal::"kogrqztpluqo",
  action,
  resource == Resource::"vavxdjglsofu"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"vavxdjglsofu"
) when {
  true
};forbid(
  principal,
  action == Action::"kmbdwspkvtfg",
  resource
) when {
  true
};forbid(
  principal == Principal::"ofgyatrijmgo",
  action == Action::"eznkoftfugqe",
  resource
) when {
  true
};permit(
  principal == Principal::"zecopqcenfgq",
  action == Action::"cylquarfmrwe",
  resource == Resource::"ulznxoseohpu"
) when {
  true
};forbid(
  principal == Principal::"zecopqcenfgq",
  action,
  resource == Resource::"gqffhvppakdw"
) when {
  true
};permit(
  principal,
  action == Action::"bmsqxkwwmxbd",
  resource
) when {
  true
};permit(
  principal == Principal::"qrpzhkydumww",
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"nwztsonbjwas"
) when {
  true
};permit(
  principal,
  action == Action::"gecxhbsbcexd",
  resource
) when {
  true
};forbid(
  principal == Principal::"zecopqcenfgq",
  action == Action::"yecncgfardrl",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"wlsuxufpqtmr",
  resource
) when {
  true
};forbid(
  principal == Principal::"yvmdixfqccis",
  action == Action::"bmsqxkwwmxbd",
  resource
) when {
  true
};forbid(
  principal == Principal::"dispcfnvmsbk",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"uggkhcwckerj",
  resource
) when {
  true
};permit(
  principal == Principal::"zecopqcenfgq",
  action,
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};permit(
  principal,
  action == Action::"uadsypfdkadt",
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};permit(
  principal == Principal::"kogrqztpluqo",
  action == Action::"kejhfvxakgif",
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};permit(
  principal == Principal::"mziqzwabfbrh",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"drklrhusxiix",
  resource == Resource::"srxwbjqzxrgh"
) when {
  true
};forbid(
  principal == Principal::"yvjjzrpmacol",
  action == Action::"yimrpeazjxlz",
  resource == Resource::"oldrrovawflz"
) when {
  true
};permit(
  principal,
  action == Action::"yypwsijfobaw",
  resource
) when {
  true
};forbid(
  principal == Principal::"pdqaqryvzlsq",
  action == Action::"yecncgfardrl",
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};permit(
  principal,
  action == Action::"dqfvsmwvnxlj",
  resource
) when {
  true
};forbid(
  principal == Principal::"uifdrmilqkbk",
  action,
  resource == Resource::"vavxdjglsofu"
) when {
  true
};permit(
  principal == Principal::"pyhrmdcufcqx",
  action == Action::"wjsugdswubof",
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};forbid(
  principal == Principal::"zecopqcenfgq",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"pqwnanlakjop"
) when {
  true
};forbid(
  principal,
  action == Action::"dqfvsmwvnxlj",
  resource == Resource::"oqrbyaozcasi"
) when {
  true
};forbid(
  principal,
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};forbid(
  principal == Principal::"dispcfnvmsbk",
  action == Action::"wlsuxufpqtmr",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"adseqgfmvjbb",
  resource == Resource::"qwttuibrbbgr"
) when {
  true
};permit(
  principal,
  action == Action::"ykpsxanrepau",
  resource == Resource::"ikpbtpdgplxh"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"vavxdjglsofu"
) when {
  true
};forbid(
  principal,
  action == Action::"adseqgfmvjbb",
  resource
) when {
  true
};permit(
  principal == Principal::"yvmdixfqccis",
  action == Action::"oxehxgadwqvr",
  resource == Resource::"biwuwymeckvq"
) when {
  true
};forbid(
  principal == Principal::"mrlwamjjaiwr",
  action,
  resource == Resource::"vavxdjglsofu"
) when {
  true
};forbid(
  principal,
  action == Action::"pbklvwalhytz",
  resource
) when {
  true
};permit(
  principal == Principal::"chrumrstfrtw",
  action,
  resource == Resource::"srxwbjqzxrgh"
) when {
  true
};permit(
  principal == Principal::"vhsewusivvyz",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"uifdrmilqkbk",
  action == Action::"yypwsijfobaw",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"uggkhcwckerj",
  resource == Resource::"ulznxoseohpu"
) when {
  true
};forbid(
  principal,
  action == Action::"yimrpeazjxlz",
  resource == Resource::"dwftjhqwiake"
) when {
  true
};forbid(
  principal,
  action == Action::"xapzhjcbzdlc",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"sdqpabgkumia",
  resource == Resource::"drwyrjwaheeo"
) when {
  true
};permit(
  principal == Principal::"mrlwamjjaiwr",
  action == Action::"xenqqlcueghi",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"forqvcikcjnd"
) when {
  true
};forbid(
  principal,
  action == Action::"uadsypfdkadt",
  resource == Resource::"wthwwbztubhr"
) when {
  true
};forbid(
  principal == Principal::"qrpzhkydumww",
  action == Action::"kejhfvxakgif",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"eznkoftfugqe",
  resource == Resource::"czrozycfjskx"
) when {
  true
};forbid(
  principal,
  action == Action::"drklrhusxiix",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"pbklvwalhytz",
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};permit(
  principal == Principal::"rpsvssietntf",
  action,
  resource == Resource::"ulznxoseohpu"
) when {
  true
};forbid(
  principal == Principal::"amvmeibzxmsx",
  action == Action::"doqfseeyzrpi",
  resource == Resource::"dwftjhqwiake"
) when {
  true
};forbid(
  principal,
  action == Action::"xapzhjcbzdlc",
  resource == Resource::"gqffhvppakdw"
) when {
  true
};forbid(
  principal,
  action == Action::"yimrpeazjxlz",
  resource == Resource::"oldrrovawflz"
) when {
  true
};permit(
  principal == Principal::"chrumrstfrtw",
  action == Action::"llnqeaclsamg",
  resource == Resource::"jglopfkzivcy"
) when {
  true
};forbid(
  principal == Principal::"amvmeibzxmsx",
  action == Action::"gecxhbsbcexd",
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"ulznxoseohpu"
) when {
  true
};permit(
  principal == Principal::"zjyrhpjscbbp",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"xenqqlcueghi",
  resource
) when {
  true
};forbid(
  principal == Principal::"mrlwamjjaiwr",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"dispcfnvmsbk",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"vqpwqtnuabqh",
  action,
  resource == Resource::"ajbutxryzsra"
) when {
  true
};forbid(
  principal == Principal::"xbuqbeudwgxh",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"bgtjiynturjo",
  action == Action::"oxehxgadwqvr",
  resource
) when {
  true
};permit(
  principal == Principal::"pdqaqryvzlsq",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"dispcfnvmsbk",
  action == Action::"oxehxgadwqvr",
  resource == Resource::"czrozycfjskx"
) when {
  true
};permit(
  principal == Principal::"pdqaqryvzlsq",
  action == Action::"gecxhbsbcexd",
  resource
) when {
  true
};forbid(
  principal == Principal::"rpsvssietntf",
  action == Action::"llnqeaclsamg",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"ulznxoseohpu"
) when {
  true
};forbid(
  principal,
  action == Action::"gkmzlzkyizur",
  resource == Resource::"xwhjixkfjnxs"
) when {
  true
};forbid(
  principal,
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"llnqeaclsamg",
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};forbid(
  principal == Principal::"dflbksifozhy",
  action,
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};forbid(
  principal == Principal::"xbuqbeudwgxh",
  action == Action::"zyxdtvryguyl",
  resource == Resource::"oldrrovawflz"
) when {
  true
};permit(
  principal == Principal::"pyhrmdcufcqx",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"ajbutxryzsra"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"jglopfkzivcy"
) when {
  true
};permit(
  principal == Principal::"xbuqbeudwgxh",
  action == Action::"kmbdwspkvtfg",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"kejhfvxakgif",
  resource
) when {
  true
};forbid(
  principal == Principal::"dflbksifozhy",
  action,
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"czrozycfjskx"
) when {
  true
};permit(
  principal,
  action == Action::"bmsqxkwwmxbd",
  resource == Resource::"qwttuibrbbgr"
) when {
  true
};permit(
  principal == Principal::"yvmdixfqccis",
  action == Action::"xenqqlcueghi",
  resource == Resource::"ajbutxryzsra"
) when {
  true
};forbid(
  principal,
  action == Action::"eznkoftfugqe",
  resource == Resource::"oqrbyaozcasi"
) when {
  true
};forbid(
  principal == Principal::"kwvjsetpsmlt",
  action,
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};permit(
  principal == Principal::"dflbksifozhy",
  action == Action::"xapzhjcbzdlc",
  resource == Resource::"pqwnanlakjop"
) when {
  true
};permit(
  principal == Principal::"jqocyhrsmqjt",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"pfjozsmouwdr",
  resource == Resource::"ulznxoseohpu"
) when {
  true
};permit(
  principal == Principal::"yvmdixfqccis",
  action == Action::"sdqpabgkumia",
  resource == Resource::"gqffhvppakdw"
) when {
  true
};forbid(
  principal == Principal::"uifdrmilqkbk",
  action == Action::"gkmzlzkyizur",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"xapzhjcbzdlc",
  resource
) when {
  true
};forbid(
  principal == Principal::"pyhrmdcufcqx",
  action == Action::"xenqqlcueghi",
  resource == Resource::"wthwwbztubhr"
) when {
  true
};permit(
  principal == Principal::"rgzdhgznrmmx",
  action,
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal,
  action == Action::"zyxdtvryguyl",
  resource == Resource::"forqvcikcjnd"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"jbxgvzkebjva"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"oqrbyaozcasi"
) when {
  true
};permit(
  principal,
  action == Action::"uggkhcwckerj",
  resource == Resource::"forqvcikcjnd"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"biwuwymeckvq"
) when {
  true
};permit(
  principal == Principal::"mziqzwabfbrh",
  action,
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};forbid(
  principal == Principal::"yvjjzrpmacol",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"yysewqkamtqj",
  resource
) when {
  true
};permit(
  principal == Principal::"mziqzwabfbrh",
  action == Action::"wjsugdswubof",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"nzvgzgtjqjen",
  resource
) when {
  true
};permit(
  principal == Principal::"qrpzhkydumww",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"jbxgvzkebjva"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"gisdxyeyrolr"
) when {
  true
};forbid(
  principal == Principal::"whavzicbxxlv",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"dispcfnvmsbk",
  action == Action::"wjsugdswubof",
  resource
) when {
  true
};forbid(
  principal == Principal::"jqocyhrsmqjt",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"zyxdtvryguyl",
  resource == Resource::"jglopfkzivcy"
) when {
  true
};forbid(
  principal == Principal::"jqocyhrsmqjt",
  action == Action::"adseqgfmvjbb",
  resource == Resource::"nwztsonbjwas"
) when {
  true
};permit(
  principal == Principal::"dispcfnvmsbk",
  action == Action::"xenqqlcueghi",
  resource == Resource::"qwttuibrbbgr"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};forbid(
  principal == Principal::"pdqaqryvzlsq",
  action,
  resource == Resource::"srxwbjqzxrgh"
) when {
  true
};forbid(
  principal,
  action == Action::"yypwsijfobaw",
  resource
) when {
  true
};forbid(
  principal == Principal::"xzdnnodrqapi",
  action == Action::"gbzjaithkydf",
  resource == Resource::"forqvcikcjnd"
) when {
  true
};forbid(
  principal,
  action == Action::"kmbdwspkvtfg",
  resource == Resource::"vavxdjglsofu"
) when {
  true
};forbid(
  principal == Principal::"bgtjiynturjo",
  action == Action::"nzvgzgtjqjen",
  resource
) when {
  true
};permit(
  principal == Principal::"mrlwamjjaiwr",
  action,
  resource == Resource::"czrozycfjskx"
) when {
  true
};forbid(
  principal == Principal::"yvjjzrpmacol",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"yecncgfardrl",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"oxehxgadwqvr",
  resource == Resource::"ajbutxryzsra"
) when {
  true
};permit(
  principal,
  action == Action::"oxehxgadwqvr",
  resource
) when {
  true
};permit(
  principal == Principal::"pyhrmdcufcqx",
  action == Action::"uggkhcwckerj",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"xwhjixkfjnxs"
) when {
  true
};forbid(
  principal == Principal::"xzdnnodrqapi",
  action,
  resource == Resource::"xwhjixkfjnxs"
) when {
  true
};permit(
  principal == Principal::"vqpwqtnuabqh",
  action == Action::"gkmzlzkyizur",
  resource
) when {
  true
};permit(
  principal == Principal::"uifdrmilqkbk",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"srxwbjqzxrgh"
) when {
  true
};forbid(
  principal == Principal::"pdqaqryvzlsq",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"eaphhdtuwgom",
  resource
) when {
  true
};permit(
  principal == Principal::"whavzicbxxlv",
  action,
  resource == Resource::"elxkfuidmbqq"
) when {
  true
};permit(
  principal,
  action == Action::"doqfseeyzrpi",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"pfjozsmouwdr",
  resource == Resource::"gqffhvppakdw"
) when {
  true
};permit(
  principal == Principal::"bgtjiynturjo",
  action == Action::"dqfvsmwvnxlj",
  resource == Resource::"ikpbtpdgplxh"
) when {
  true
};forbid(
  principal == Principal::"jqocyhrsmqjt",
  action == Action::"uggkhcwckerj",
  resource
) when {
  true
};permit(
  principal == Principal::"ofgyatrijmgo",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"uggkhcwckerj",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ikpbtpdgplxh"
) when {
  true
};permit(
  principal == Principal::"dflbksifozhy",
  action,
  resource == Resource::"dwftjhqwiake"
) when {
  true
};permit(
  principal == Principal::"zecopqcenfgq",
  action == Action::"wjsugdswubof",
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};permit(
  principal,
  action == Action::"cylquarfmrwe",
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal,
  action == Action::"kejhfvxakgif",
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal == Principal::"uifdrmilqkbk",
  action == Action::"wlsuxufpqtmr",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"eznkoftfugqe",
  resource == Resource::"inchvedkmfon"
) when {
  true
};permit(
  principal,
  action == Action::"eaphhdtuwgom",
  resource == Resource::"dwftjhqwiake"
) when {
  true
};permit(
  principal == Principal::"zjyrhpjscbbp",
  action == Action::"gkmzlzkyizur",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"pfjozsmouwdr",
  resource
) when {
  true
};permit(
  principal == Principal::"ssjclvttqfxe",
  action == Action::"yimrpeazjxlz",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"kmbdwspkvtfg",
  resource
) when {
  true
};permit(
  principal == Principal::"zjyrhpjscbbp",
  action == Action::"kejhfvxakgif",
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};permit(
  principal,
  action == Action::"wlsuxufpqtmr",
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};permit(
  principal == Principal::"ofgyatrijmgo",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"yvjjzrpmacol",
  action == Action::"pfjozsmouwdr",
  resource == Resource::"xokttubgjsye"
) when {
  true
};forbid(
  principal == Principal::"xzdnnodrqapi",
  action == Action::"pbklvwalhytz",
  resource == Resource::"xokttubgjsye"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};permit(
  principal == Principal::"qrpzhkydumww",
  action == Action::"kmbdwspkvtfg",
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};permit(
  principal,
  action == Action::"wegbeghgfeps",
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};forbid(
  principal == Principal::"rpsvssietntf",
  action == Action::"yypwsijfobaw",
  resource == Resource::"biwuwymeckvq"
) when {
  true
};forbid(
  principal,
  action == Action::"llnqeaclsamg",
  resource
) when {
  true
};forbid(
  principal == Principal::"whavzicbxxlv",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"wmddwgyhrjgx",
  action,
  resource == Resource::"czrozycfjskx"
) when {
  true
};forbid(
  principal == Principal::"zjyrhpjscbbp",
  action == Action::"sdqpabgkumia",
  resource == Resource::"vavxdjglsofu"
) when {
  true
};forbid(
  principal,
  action == Action::"xenqqlcueghi",
  resource
) when {
  true
};permit(
  principal == Principal::"dflbksifozhy",
  action == Action::"zyxdtvryguyl",
  resource == Resource::"srxwbjqzxrgh"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"qwttuibrbbgr"
) when {
  true
};permit(
  principal,
  action == Action::"wjsugdswubof",
  resource
) when {
  true
};permit(
  principal == Principal::"kchpgcobubqo",
  action,
  resource == Resource::"gqffhvppakdw"
) when {
  true
};forbid(
  principal,
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};forbid(
  principal == Principal::"pyhrmdcufcqx",
  action == Action::"kmbdwspkvtfg",
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};forbid(
  principal,
  action == Action::"kejhfvxakgif",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"xokttubgjsye"
) when {
  true
};permit(
  principal == Principal::"jneydhxtsaoc",
  action == Action::"doqfseeyzrpi",
  resource
) when {
  true
};forbid(
  principal == Principal::"kogrqztpluqo",
  action == Action::"yimrpeazjxlz",
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};permit(
  principal,
  action == Action::"yypwsijfobaw",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"wthwwbztubhr"
) when {
  true
};permit(
  principal,
  action == Action::"llnqeaclsamg",
  resource
) when {
  true
};forbid(
  principal == Principal::"mrlwamjjaiwr",
  action == Action::"yysewqkamtqj",
  resource
) when {
  true
};permit(
  principal == Principal::"pdqaqryvzlsq",
  action,
  resource == Resource::"oqrbyaozcasi"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ulznxoseohpu"
) when {
  true
};permit(
  principal == Principal::"pdqaqryvzlsq",
  action == Action::"zyxdtvryguyl",
  resource == Resource::"gqffhvppakdw"
) when {
  true
};forbid(
  principal == Principal::"dispcfnvmsbk",
  action == Action::"bmsqxkwwmxbd",
  resource
) when {
  true
};forbid(
  principal == Principal::"velciusvmoxg",
  action == Action::"uggkhcwckerj",
  resource
) when {
  true
};forbid(
  principal == Principal::"rgzdhgznrmmx",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"yvmdixfqccis",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"rgzdhgznrmmx",
  action == Action::"wjsugdswubof",
  resource
) when {
  true
};permit(
  principal == Principal::"kchpgcobubqo",
  action == Action::"wjsugdswubof",
  resource
) when {
  true
};permit(
  principal == Principal::"kchpgcobubqo",
  action == Action::"pfjozsmouwdr",
  resource
) when {
  true
};forbid(
  principal == Principal::"rpsvssietntf",
  action == Action::"xapzhjcbzdlc",
  resource == Resource::"czrozycfjskx"
) when {
  true
};permit(
  principal == Principal::"bgtjiynturjo",
  action == Action::"doqfseeyzrpi",
  resource
) when {
  true
};permit(
  principal == Principal::"jqocyhrsmqjt",
  action == Action::"pbklvwalhytz",
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};forbid(
  principal == Principal::"xzdnnodrqapi",
  action,
  resource == Resource::"xokttubgjsye"
) when {
  true
};forbid(
  principal == Principal::"jneydhxtsaoc",
  action == Action::"bmsqxkwwmxbd",
  resource == Resource::"gqffhvppakdw"
) when {
  true
};forbid(
  principal == Principal::"dflbksifozhy",
  action == Action::"yecncgfardrl",
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};permit(
  principal == Principal::"bgtjiynturjo",
  action,
  resource == Resource::"nwztsonbjwas"
) when {
  true
};permit(
  principal == Principal::"mrlwamjjaiwr",
  action,
  resource == Resource::"elxkfuidmbqq"
) when {
  true
};permit(
  principal == Principal::"ssjclvttqfxe",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"pdqaqryvzlsq",
  action == Action::"yypwsijfobaw",
  resource == Resource::"czrozycfjskx"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"elxkfuidmbqq"
) when {
  true
};permit(
  principal == Principal::"kogrqztpluqo",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};forbid(
  principal == Principal::"mrlwamjjaiwr",
  action,
  resource == Resource::"xwhjixkfjnxs"
) when {
  true
};permit(
  principal == Principal::"xzdnnodrqapi",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"zjyrhpjscbbp",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"vhsewusivvyz",
  action == Action::"drklrhusxiix",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"sdqpabgkumia",
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};permit(
  principal,
  action == Action::"cylquarfmrwe",
  resource == Resource::"czrozycfjskx"
) when {
  true
};forbid(
  principal == Principal::"dispcfnvmsbk",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"kogrqztpluqo",
  action == Action::"nzvgzgtjqjen",
  resource
) when {
  true
};forbid(
  principal == Principal::"whavzicbxxlv",
  action == Action::"drklrhusxiix",
  resource
) when {
  true
};permit(
  principal == Principal::"yvmdixfqccis",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"kwvjsetpsmlt",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"mziqzwabfbrh",
  action,
  resource == Resource::"czrozycfjskx"
) when {
  true
};forbid(
  principal == Principal::"vhsewusivvyz",
  action == Action::"eaphhdtuwgom",
  resource
) when {
  true
};forbid(
  principal == Principal::"xbuqbeudwgxh",
  action,
  resource == Resource::"dwftjhqwiake"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal,
  action == Action::"zyxdtvryguyl",
  resource
) when {
  true
};forbid(
  principal == Principal::"mrlwamjjaiwr",
  action == Action::"gkmzlzkyizur",
  resource
) when {
  true
};forbid(
  principal == Principal::"wmddwgyhrjgx",
  action,
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};forbid(
  principal,
  action == Action::"yecncgfardrl",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"srxwbjqzxrgh"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"oqrbyaozcasi"
) when {
  true
};permit(
  principal == Principal::"chrumrstfrtw",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"pdqaqryvzlsq",
  action == Action::"gkmzlzkyizur",
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};forbid(
  principal == Principal::"vhsewusivvyz",
  action == Action::"wjsugdswubof",
  resource == Resource::"xokttubgjsye"
) when {
  true
};forbid(
  principal,
  action == Action::"yypwsijfobaw",
  resource == Resource::"inchvedkmfon"
) when {
  true
};forbid(
  principal == Principal::"bgtjiynturjo",
  action,
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};permit(
  principal == Principal::"vhsewusivvyz",
  action,
  resource == Resource::"pqwnanlakjop"
) when {
  true
};permit(
  principal,
  action == Action::"kmbdwspkvtfg",
  resource == Resource::"ulznxoseohpu"
) when {
  true
};permit(
  principal,
  action == Action::"ykpsxanrepau",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"doqfseeyzrpi",
  resource == Resource::"nwztsonbjwas"
) when {
  true
};permit(
  principal == Principal::"vhsewusivvyz",
  action,
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};permit(
  principal,
  action == Action::"dqfvsmwvnxlj",
  resource == Resource::"ajbutxryzsra"
) when {
  true
};forbid(
  principal,
  action == Action::"wjsugdswubof",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"nzvgzgtjqjen",
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};forbid(
  principal == Principal::"vqpwqtnuabqh",
  action == Action::"gecxhbsbcexd",
  resource
) when {
  true
};permit(
  principal == Principal::"wmddwgyhrjgx",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"yvmdixfqccis",
  action,
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};permit(
  principal == Principal::"zjyrhpjscbbp",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"yvjjzrpmacol",
  action,
  resource == Resource::"styepjegwuco"
) when {
  true
};permit(
  principal == Principal::"ssjclvttqfxe",
  action,
  resource == Resource::"jglopfkzivcy"
) when {
  true
};permit(
  principal == Principal::"qrpzhkydumww",
  action == Action::"yypwsijfobaw",
  resource == Resource::"forqvcikcjnd"
) when {
  true
};permit(
  principal,
  action == Action::"sdqpabgkumia",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};permit(
  principal,
  action == Action::"wlsuxufpqtmr",
  resource == Resource::"wthwwbztubhr"
) when {
  true
};forbid(
  principal == Principal::"bgtjiynturjo",
  action == Action::"yimrpeazjxlz",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"ykpsxanrepau",
  resource == Resource::"forqvcikcjnd"
) when {
  true
};forbid(
  principal == Principal::"rgzdhgznrmmx",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"vqpwqtnuabqh",
  action == Action::"wegbeghgfeps",
  resource == Resource::"jbxgvzkebjva"
) when {
  true
};forbid(
  principal == Principal::"pdqaqryvzlsq",
  action == Action::"pbklvwalhytz",
  resource
) when {
  true
};permit(
  principal == Principal::"pdqaqryvzlsq",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"gecxhbsbcexd",
  resource
) when {
  true
};forbid(
  principal == Principal::"rgzdhgznrmmx",
  action,
  resource == Resource::"styepjegwuco"
) when {
  true
};permit(
  principal == Principal::"bgtjiynturjo",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"wmddwgyhrjgx",
  action == Action::"llnqeaclsamg",
  resource
) when {
  true
};forbid(
  principal == Principal::"kwvjsetpsmlt",
  action == Action::"bmsqxkwwmxbd",
  resource == Resource::"czrozycfjskx"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"biwuwymeckvq"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"ulznxoseohpu"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"biwuwymeckvq"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};permit(
  principal == Principal::"mziqzwabfbrh",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"rgzdhgznrmmx",
  action == Action::"llnqeaclsamg",
  resource == Resource::"qwttuibrbbgr"
) when {
  true
};permit(
  principal,
  action == Action::"llnqeaclsamg",
  resource
) when {
  true
};permit(
  principal == Principal::"yvjjzrpmacol",
  action == Action::"kejhfvxakgif",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"uggkhcwckerj",
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};permit(
  principal,
  action == Action::"nzvgzgtjqjen",
  resource == Resource::"srxwbjqzxrgh"
) when {
  true
};permit(
  principal == Principal::"dflbksifozhy",
  action == Action::"cylquarfmrwe",
  resource == Resource::"dwftjhqwiake"
) when {
  true
};forbid(
  principal == Principal::"uifdrmilqkbk",
  action,
  resource == Resource::"biwuwymeckvq"
) when {
  true
};permit(
  principal == Principal::"rpsvssietntf",
  action == Action::"gecxhbsbcexd",
  resource
) when {
  true
};forbid(
  principal == Principal::"kchpgcobubqo",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"vqpwqtnuabqh",
  action == Action::"bmsqxkwwmxbd",
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};permit(
  principal,
  action == Action::"adseqgfmvjbb",
  resource == Resource::"gqffhvppakdw"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};permit(
  principal,
  action == Action::"yypwsijfobaw",
  resource == Resource::"elxkfuidmbqq"
) when {
  true
};permit(
  principal == Principal::"wmddwgyhrjgx",
  action == Action::"nzvgzgtjqjen",
  resource == Resource::"ulznxoseohpu"
) when {
  true
};forbid(
  principal == Principal::"velciusvmoxg",
  action,
  resource == Resource::"pqwnanlakjop"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};forbid(
  principal,
  action == Action::"sdqpabgkumia",
  resource == Resource::"oqrbyaozcasi"
) when {
  true
};forbid(
  principal == Principal::"zecopqcenfgq",
  action == Action::"eznkoftfugqe",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"yypwsijfobaw",
  resource
) when {
  true
};permit(
  principal == Principal::"zjyrhpjscbbp",
  action == Action::"gbzjaithkydf",
  resource == Resource::"dwftjhqwiake"
) when {
  true
};permit(
  principal == Principal::"kwvjsetpsmlt",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"rpsvssietntf",
  action,
  resource == Resource::"ajbutxryzsra"
) when {
  true
};forbid(
  principal == Principal::"jqocyhrsmqjt",
  action == Action::"cylquarfmrwe",
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal,
  action == Action::"uadsypfdkadt",
  resource == Resource::"gisdxyeyrolr"
) when {
  true
};permit(
  principal == Principal::"vqpwqtnuabqh",
  action == Action::"xenqqlcueghi",
  resource
) when {
  true
};permit(
  principal == Principal::"kchpgcobubqo",
  action == Action::"sdqpabgkumia",
  resource
) when {
  true
};permit(
  principal == Principal::"uifdrmilqkbk",
  action == Action::"bmsqxkwwmxbd",
  resource
) when {
  true
};permit(
  principal == Principal::"mziqzwabfbrh",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"zecopqcenfgq",
  action == Action::"pfjozsmouwdr",
  resource == Resource::"forqvcikcjnd"
) when {
  true
};permit(
  principal == Principal::"xzdnnodrqapi",
  action == Action::"gecxhbsbcexd",
  resource == Resource::"pqwnanlakjop"
) when {
  true
};permit(
  principal == Principal::"xbuqbeudwgxh",
  action == Action::"yimrpeazjxlz",
  resource
) when {
  true
};permit(
  principal == Principal::"uifdrmilqkbk",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"jqocyhrsmqjt",
  action == Action::"pbklvwalhytz",
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};permit(
  principal,
  action == Action::"nzvgzgtjqjen",
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};forbid(
  principal,
  action == Action::"gecxhbsbcexd",
  resource
) when {
  true
};permit(
  principal == Principal::"ssjclvttqfxe",
  action == Action::"wegbeghgfeps",
  resource == Resource::"xwhjixkfjnxs"
) when {
  true
};forbid(
  principal == Principal::"xzdnnodrqapi",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"vqpwqtnuabqh",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"mziqzwabfbrh",
  action == Action::"nzvgzgtjqjen",
  resource == Resource::"ulznxoseohpu"
) when {
  true
};forbid(
  principal == Principal::"wmddwgyhrjgx",
  action,
  resource == Resource::"jglopfkzivcy"
) when {
  true
};permit(
  principal == Principal::"kchpgcobubqo",
  action == Action::"ykpsxanrepau",
  resource
) when {
  true
};forbid(
  principal == Principal::"qrpzhkydumww",
  action == Action::"drklrhusxiix",
  resource == Resource::"xwhjixkfjnxs"
) when {
  true
};permit(
  principal == Principal::"dflbksifozhy",
  action == Action::"kejhfvxakgif",
  resource
) when {
  true
};forbid(
  principal == Principal::"ssjclvttqfxe",
  action == Action::"bmsqxkwwmxbd",
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};permit(
  principal == Principal::"mrlwamjjaiwr",
  action == Action::"xenqqlcueghi",
  resource
) when {
  true
};permit(
  principal == Principal::"whavzicbxxlv",
  action,
  resource == Resource::"czrozycfjskx"
) when {
  true
};permit(
  principal == Principal::"jneydhxtsaoc",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"llnqeaclsamg",
  resource
) when {
  true
};permit(
  principal == Principal::"dispcfnvmsbk",
  action,
  resource == Resource::"drwyrjwaheeo"
) when {
  true
};forbid(
  principal,
  action == Action::"kejhfvxakgif",
  resource == Resource::"oldrrovawflz"
) when {
  true
};permit(
  principal == Principal::"vhsewusivvyz",
  action == Action::"drklrhusxiix",
  resource == Resource::"dwftjhqwiake"
) when {
  true
};forbid(
  principal,
  action == Action::"eznkoftfugqe",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"yimrpeazjxlz",
  resource
) when {
  true
};permit(
  principal == Principal::"yvjjzrpmacol",
  action == Action::"pfjozsmouwdr",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"wegbeghgfeps",
  resource
) when {
  true
};forbid(
  principal == Principal::"amvmeibzxmsx",
  action,
  resource == Resource::"ulznxoseohpu"
) when {
  true
};forbid(
  principal,
  action == Action::"doqfseeyzrpi",
  resource
) when {
  true
};forbid(
  principal == Principal::"rgzdhgznrmmx",
  action,
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};forbid(
  principal,
  action == Action::"yysewqkamtqj",
  resource
) when {
  true
};permit(
  principal == Principal::"velciusvmoxg",
  action,
  resource == Resource::"vavxdjglsofu"
) when {
  true
};forbid(
  principal == Principal::"vqpwqtnuabqh",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"kogrqztpluqo",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"ykpsxanrepau",
  resource
) when {
  true
};forbid(
  principal == Principal::"mrlwamjjaiwr",
  action,
  resource == Resource::"gisdxyeyrolr"
) when {
  true
};permit(
  principal,
  action == Action::"dqfvsmwvnxlj",
  resource == Resource::"drwyrjwaheeo"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};permit(
  principal == Principal::"yvjjzrpmacol",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"rgzdhgznrmmx",
  action == Action::"yimrpeazjxlz",
  resource
) when {
  true
};forbid(
  principal == Principal::"qrpzhkydumww",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"kwvjsetpsmlt",
  action,
  resource == Resource::"xtgcvhtqyjuf"
) when {
  true
};permit(
  principal == Principal::"mrlwamjjaiwr",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"rgzdhgznrmmx",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"uifdrmilqkbk",
  action,
  resource == Resource::"forqvcikcjnd"
) when {
  true
};permit(
  principal == Principal::"mziqzwabfbrh",
  action,
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};forbid(
  principal == Principal::"ssjclvttqfxe",
  action == Action::"pbklvwalhytz",
  resource == Resource::"oldrrovawflz"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};permit(
  principal,
  action == Action::"uggkhcwckerj",
  resource == Resource::"srxwbjqzxrgh"
) when {
  true
};forbid(
  principal == Principal::"ofgyatrijmgo",
  action == Action::"eaphhdtuwgom",
  resource == Resource::"xokttubgjsye"
) when {
  true
};permit(
  principal == Principal::"pyhrmdcufcqx",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"vhsewusivvyz",
  action == Action::"zyxdtvryguyl",
  resource
) when {
  true
};permit(
  principal == Principal::"uifdrmilqkbk",
  action == Action::"gecxhbsbcexd",
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};forbid(
  principal,
  action == Action::"ykpsxanrepau",
  resource
) when {
  true
};forbid(
  principal == Principal::"kwvjsetpsmlt",
  action,
  resource == Resource::"dwftjhqwiake"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};permit(
  principal,
  action == Action::"eznkoftfugqe",
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};permit(
  principal == Principal::"xbuqbeudwgxh",
  action,
  resource == Resource::"czrozycfjskx"
) when {
  true
};forbid(
  principal == Principal::"qrpzhkydumww",
  action,
  resource == Resource::"forqvcikcjnd"
) when {
  true
};forbid(
  principal == Principal::"bgtjiynturjo",
  action,
  resource == Resource::"ulznxoseohpu"
) when {
  true
};permit(
  principal == Principal::"amvmeibzxmsx",
  action,
  resource == Resource::"gqffhvppakdw"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"xtgcvhtqyjuf"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"wthwwbztubhr"
) when {
  true
};forbid(
  principal,
  action == Action::"wegbeghgfeps",
  resource == Resource::"oqrbyaozcasi"
) when {
  true
};permit(
  principal,
  action == Action::"gecxhbsbcexd",
  resource == Resource::"nwztsonbjwas"
) when {
  true
};forbid(
  principal,
  action == Action::"gecxhbsbcexd",
  resource == Resource::"srxwbjqzxrgh"
) when {
  true
};permit(
  principal == Principal::"ssjclvttqfxe",
  action == Action::"ykpsxanrepau",
  resource
) when {
  true
};permit(
  principal == Principal::"mziqzwabfbrh",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"xapzhjcbzdlc",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"gkmzlzkyizur",
  resource
) when {
  true
};permit(
  principal == Principal::"chrumrstfrtw",
  action == Action::"doqfseeyzrpi",
  resource == Resource::"gqffhvppakdw"
) when {
  true
};permit(
  principal == Principal::"ssjclvttqfxe",
  action == Action::"uggkhcwckerj",
  resource == Resource::"gqffhvppakdw"
) when {
  true
};permit(
  principal == Principal::"wmddwgyhrjgx",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"yvmdixfqccis",
  action == Action::"uggkhcwckerj",
  resource
) when {
  true
};forbid(
  principal == Principal::"xbuqbeudwgxh",
  action == Action::"pbklvwalhytz",
  resource
) when {
  true
};forbid(
  principal == Principal::"mrlwamjjaiwr",
  action == Action::"gecxhbsbcexd",
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};permit(
  principal == Principal::"rgzdhgznrmmx",
  action == Action::"doqfseeyzrpi",
  resource
) when {
  true
};permit(
  principal == Principal::"whavzicbxxlv",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"ssjclvttqfxe",
  action == Action::"drklrhusxiix",
  resource
) when {
  true
};permit(
  principal == Principal::"bgtjiynturjo",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"dflbksifozhy",
  action,
  resource == Resource::"wthwwbztubhr"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"xtgcvhtqyjuf"
) when {
  true
};forbid(
  principal,
  action == Action::"uggkhcwckerj",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"cylquarfmrwe",
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};forbid(
  principal == Principal::"kchpgcobubqo",
  action == Action::"zyxdtvryguyl",
  resource == Resource::"dwftjhqwiake"
) when {
  true
};permit(
  principal == Principal::"pdqaqryvzlsq",
  action == Action::"pfjozsmouwdr",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"zyxdtvryguyl",
  resource == Resource::"pqwnanlakjop"
) when {
  true
};permit(
  principal == Principal::"rgzdhgznrmmx",
  action == Action::"zyxdtvryguyl",
  resource
) when {
  true
};forbid(
  principal == Principal::"ofgyatrijmgo",
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};forbid(
  principal == Principal::"xzdnnodrqapi",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"yypwsijfobaw",
  resource == Resource::"styepjegwuco"
) when {
  true
};permit(
  principal,
  action == Action::"eznkoftfugqe",
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};forbid(
  principal,
  action == Action::"pfjozsmouwdr",
  resource
) when {
  true
};permit(
  principal == Principal::"kogrqztpluqo",
  action,
  resource == Resource::"xwhjixkfjnxs"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};permit(
  principal,
  action == Action::"yypwsijfobaw",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"xokttubgjsye"
) when {
  true
};permit(
  principal,
  action == Action::"eaphhdtuwgom",
  resource == Resource::"jbxgvzkebjva"
) when {
  true
};permit(
  principal,
  action == Action::"pbklvwalhytz",
  resource == Resource::"ulznxoseohpu"
) when {
  true
};permit(
  principal,
  action == Action::"kejhfvxakgif",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"gbzjaithkydf",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"yecncgfardrl",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"pbklvwalhytz",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"yimrpeazjxlz",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"wlsuxufpqtmr",
  resource == Resource::"gqffhvppakdw"
) when {
  true
};permit(
  principal == Principal::"pdqaqryvzlsq",
  action == Action::"uggkhcwckerj",
  resource == Resource::"xokttubgjsye"
) when {
  true
};forbid(
  principal == Principal::"pyhrmdcufcqx",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"gkmzlzkyizur",
  resource
) when {
  true
};permit(
  principal == Principal::"bgtjiynturjo",
  action == Action::"uadsypfdkadt",
  resource == Resource::"czrozycfjskx"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};forbid(
  principal,
  action == Action::"yypwsijfobaw",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"czrozycfjskx"
) when {
  true
};forbid(
  principal == Principal::"ofgyatrijmgo",
  action,
  resource == Resource::"biwuwymeckvq"
) when {
  true
};forbid(
  principal,
  action == Action::"yypwsijfobaw",
  resource == Resource::"jbxgvzkebjva"
) when {
  true
};permit(
  principal == Principal::"dflbksifozhy",
  action == Action::"kmbdwspkvtfg",
  resource
) when {
  true
};permit(
  principal == Principal::"rgzdhgznrmmx",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"kchpgcobubqo",
  action == Action::"adseqgfmvjbb",
  resource
) when {
  true
};permit(
  principal == Principal::"jneydhxtsaoc",
  action,
  resource == Resource::"jglopfkzivcy"
) when {
  true
};forbid(
  principal == Principal::"vqpwqtnuabqh",
  action == Action::"kejhfvxakgif",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"gecxhbsbcexd",
  resource
) when {
  true
};permit(
  principal == Principal::"chrumrstfrtw",
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};forbid(
  principal,
  action == Action::"yimrpeazjxlz",
  resource == Resource::"wthwwbztubhr"
) when {
  true
};forbid(
  principal == Principal::"zjyrhpjscbbp",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"whavzicbxxlv",
  action == Action::"dqfvsmwvnxlj",
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"pqwnanlakjop"
) when {
  true
};forbid(
  principal,
  action == Action::"gkmzlzkyizur",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"sdqpabgkumia",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"drwyrjwaheeo"
) when {
  true
};forbid(
  principal == Principal::"ofgyatrijmgo",
  action == Action::"wegbeghgfeps",
  resource
) when {
  true
};forbid(
  principal == Principal::"kogrqztpluqo",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"rgzdhgznrmmx",
  action == Action::"uggkhcwckerj",
  resource == Resource::"gisdxyeyrolr"
) when {
  true
};forbid(
  principal,
  action == Action::"kmbdwspkvtfg",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"llnqeaclsamg",
  resource == Resource::"czrozycfjskx"
) when {
  true
};permit(
  principal,
  action == Action::"yecncgfardrl",
  resource == Resource::"jglopfkzivcy"
) when {
  true
};permit(
  principal,
  action == Action::"uadsypfdkadt",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"drklrhusxiix",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};forbid(
  principal == Principal::"kogrqztpluqo",
  action == Action::"wjsugdswubof",
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};permit(
  principal == Principal::"dispcfnvmsbk",
  action == Action::"oxehxgadwqvr",
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};forbid(
  principal == Principal::"vqpwqtnuabqh",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"whavzicbxxlv",
  action == Action::"pfjozsmouwdr",
  resource == Resource::"jbxgvzkebjva"
) when {
  true
};permit(
  principal == Principal::"dispcfnvmsbk",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"xtgcvhtqyjuf"
) when {
  true
};permit(
  principal,
  action == Action::"eaphhdtuwgom",
  resource == Resource::"dwftjhqwiake"
) when {
  true
};permit(
  principal,
  action == Action::"pbklvwalhytz",
  resource
) when {
  true
};forbid(
  principal == Principal::"vhsewusivvyz",
  action == Action::"uggkhcwckerj",
  resource == Resource::"biwuwymeckvq"
) when {
  true
};forbid(
  principal == Principal::"chrumrstfrtw",
  action == Action::"uggkhcwckerj",
  resource == Resource::"elxkfuidmbqq"
) when {
  true
};forbid(
  principal == Principal::"amvmeibzxmsx",
  action == Action::"wegbeghgfeps",
  resource == Resource::"inchvedkmfon"
) when {
  true
};forbid(
  principal,
  action == Action::"ykpsxanrepau",
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};permit(
  principal == Principal::"yvjjzrpmacol",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"amvmeibzxmsx",
  action == Action::"zyxdtvryguyl",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"pbklvwalhytz",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ulznxoseohpu"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};forbid(
  principal,
  action == Action::"xapzhjcbzdlc",
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"srxwbjqzxrgh"
) when {
  true
};forbid(
  principal,
  action == Action::"yypwsijfobaw",
  resource
) when {
  true
};permit(
  principal == Principal::"whavzicbxxlv",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"mrlwamjjaiwr",
  action,
  resource == Resource::"xokttubgjsye"
) when {
  true
};permit(
  principal == Principal::"zecopqcenfgq",
  action == Action::"xapzhjcbzdlc",
  resource == Resource::"ajbutxryzsra"
) when {
  true
};permit(
  principal == Principal::"amvmeibzxmsx",
  action,
  resource == Resource::"pqwnanlakjop"
) when {
  true
};permit(
  principal,
  action == Action::"wegbeghgfeps",
  resource
) when {
  true
};forbid(
  principal == Principal::"ssjclvttqfxe",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"czrozycfjskx"
) when {
  true
};permit(
  principal,
  action == Action::"nzvgzgtjqjen",
  resource == Resource::"jbxgvzkebjva"
) when {
  true
};permit(
  principal == Principal::"kogrqztpluqo",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"yypwsijfobaw",
  resource == Resource::"elxkfuidmbqq"
) when {
  true
};forbid(
  principal == Principal::"mrlwamjjaiwr",
  action,
  resource == Resource::"qwttuibrbbgr"
) when {
  true
};forbid(
  principal == Principal::"clpwwnowcfxq",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"wmddwgyhrjgx",
  action == Action::"yysewqkamtqj",
  resource
) when {
  true
};permit(
  principal == Principal::"qrpzhkydumww",
  action == Action::"wlsuxufpqtmr",
  resource == Resource::"forqvcikcjnd"
) when {
  true
};forbid(
  principal == Principal::"zjyrhpjscbbp",
  action == Action::"xenqqlcueghi",
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};permit(
  principal == Principal::"pdqaqryvzlsq",
  action == Action::"zyxdtvryguyl",
  resource == Resource::"ajbutxryzsra"
) when {
  true
};permit(
  principal,
  action == Action::"xenqqlcueghi",
  resource == Resource::"qwttuibrbbgr"
) when {
  true
};forbid(
  principal,
  action == Action::"eaphhdtuwgom",
  resource
) when {
  true
};permit(
  principal == Principal::"zjyrhpjscbbp",
  action == Action::"gecxhbsbcexd",
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal == Principal::"yvjjzrpmacol",
  action == Action::"bmsqxkwwmxbd",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"uggkhcwckerj",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"yysewqkamtqj",
  resource
) when {
  true
};forbid(
  principal == Principal::"yvmdixfqccis",
  action == Action::"pfjozsmouwdr",
  resource == Resource::"styepjegwuco"
) when {
  true
};permit(
  principal == Principal::"jqocyhrsmqjt",
  action == Action::"kmbdwspkvtfg",
  resource == Resource::"oqrbyaozcasi"
) when {
  true
};permit(
  principal == Principal::"xbuqbeudwgxh",
  action == Action::"yypwsijfobaw",
  resource
) when {
  true
};permit(
  principal == Principal::"jqocyhrsmqjt",
  action,
  resource == Resource::"ajbutxryzsra"
) when {
  true
};permit(
  principal == Principal::"yvjjzrpmacol",
  action,
  resource == Resource::"ajbutxryzsra"
) when {
  true
};forbid(
  principal,
  action == Action::"yecncgfardrl",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"xapzhjcbzdlc",
  resource == Resource::"gqffhvppakdw"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"dwftjhqwiake"
) when {
  true
};forbid(
  principal == Principal::"xbuqbeudwgxh",
  action == Action::"yysewqkamtqj",
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};permit(
  principal == Principal::"jneydhxtsaoc",
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"jglopfkzivcy"
) when {
  true
};permit(
  principal,
  action == Action::"adseqgfmvjbb",
  resource == Resource::"oqrbyaozcasi"
) when {
  true
};permit(
  principal == Principal::"ofgyatrijmgo",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"vhsewusivvyz",
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal,
  action == Action::"oxehxgadwqvr",
  resource
) when {
  true
};permit(
  principal == Principal::"dispcfnvmsbk",
  action,
  resource == Resource::"xokttubgjsye"
) when {
  true
};forbid(
  principal == Principal::"mziqzwabfbrh",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"doqfseeyzrpi",
  resource == Resource::"oqrbyaozcasi"
) when {
  true
};permit(
  principal == Principal::"vhsewusivvyz",
  action,
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};permit(
  principal == Principal::"pyhrmdcufcqx",
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"yecncgfardrl",
  resource
) when {
  true
};forbid(
  principal == Principal::"ssjclvttqfxe",
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};forbid(
  principal == Principal::"vhsewusivvyz",
  action == Action::"xapzhjcbzdlc",
  resource == Resource::"jglopfkzivcy"
) when {
  true
};forbid(
  principal == Principal::"xzdnnodrqapi",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"dflbksifozhy",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"llnqeaclsamg",
  resource
) when {
  true
};forbid(
  principal == Principal::"mrlwamjjaiwr",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"xbuqbeudwgxh",
  action == Action::"doqfseeyzrpi",
  resource == Resource::"nwztsonbjwas"
) when {
  true
};permit(
  principal == Principal::"pyhrmdcufcqx",
  action == Action::"zyxdtvryguyl",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"jglopfkzivcy"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};forbid(
  principal,
  action == Action::"dqfvsmwvnxlj",
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};permit(
  principal,
  action == Action::"gbzjaithkydf",
  resource == Resource::"gqffhvppakdw"
) when {
  true
};permit(
  principal == Principal::"kchpgcobubqo",
  action,
  resource == Resource::"ajbutxryzsra"
) when {
  true
};forbid(
  principal == Principal::"mziqzwabfbrh",
  action == Action::"sdqpabgkumia",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ikpbtpdgplxh"
) when {
  true
};permit(
  principal == Principal::"dflbksifozhy",
  action == Action::"sdqpabgkumia",
  resource
) when {
  true
};permit(
  principal == Principal::"zecopqcenfgq",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"dispcfnvmsbk",
  action == Action::"yecncgfardrl",
  resource == Resource::"elxkfuidmbqq"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"wthwwbztubhr"
) when {
  true
};permit(
  principal == Principal::"uifdrmilqkbk",
  action == Action::"wjsugdswubof",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"pfjozsmouwdr",
  resource
) when {
  true
};forbid(
  principal == Principal::"ssjclvttqfxe",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"amvmeibzxmsx",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"rpsvssietntf",
  action == Action::"uggkhcwckerj",
  resource
) when {
  true
};forbid(
  principal == Principal::"yvmdixfqccis",
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};forbid(
  principal,
  action == Action::"llnqeaclsamg",
  resource == Resource::"biwuwymeckvq"
) when {
  true
};forbid(
  principal,
  action == Action::"doqfseeyzrpi",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal == Principal::"kogrqztpluqo",
  action == Action::"gkmzlzkyizur",
  resource
) when {
  true
};forbid(
  principal == Principal::"zjyrhpjscbbp",
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};permit(
  principal == Principal::"rpsvssietntf",
  action == Action::"gkmzlzkyizur",
  resource
) when {
  true
};permit(
  principal == Principal::"xbuqbeudwgxh",
  action == Action::"eznkoftfugqe",
  resource
) when {
  true
};forbid(
  principal == Principal::"ssjclvttqfxe",
  action == Action::"adseqgfmvjbb",
  resource == Resource::"qwttuibrbbgr"
) when {
  true
};forbid(
  principal == Principal::"xzdnnodrqapi",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"yysewqkamtqj",
  resource
) when {
  true
};permit(
  principal == Principal::"vhsewusivvyz",
  action == Action::"dqfvsmwvnxlj",
  resource
) when {
  true
};permit(
  principal == Principal::"kchpgcobubqo",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"zecopqcenfgq",
  action == Action::"oxehxgadwqvr",
  resource == Resource::"biwuwymeckvq"
) when {
  true
};permit(
  principal == Principal::"xbuqbeudwgxh",
  action,
  resource == Resource::"ajbutxryzsra"
) when {
  true
};forbid(
  principal,
  action == Action::"kejhfvxakgif",
  resource
) when {
  true
};forbid(
  principal == Principal::"jqocyhrsmqjt",
  action == Action::"pbklvwalhytz",
  resource == Resource::"dwftjhqwiake"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"pqwnanlakjop"
) when {
  true
};permit(
  principal == Principal::"mziqzwabfbrh",
  action,
  resource == Resource::"biwuwymeckvq"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};forbid(
  principal == Principal::"qrpzhkydumww",
  action == Action::"nzvgzgtjqjen",
  resource == Resource::"ajbutxryzsra"
) when {
  true
};forbid(
  principal == Principal::"uifdrmilqkbk",
  action == Action::"uggkhcwckerj",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"uggkhcwckerj",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"gkmzlzkyizur",
  resource == Resource::"xwhjixkfjnxs"
) when {
  true
};permit(
  principal == Principal::"jqocyhrsmqjt",
  action == Action::"yypwsijfobaw",
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};permit(
  principal,
  action == Action::"pfjozsmouwdr",
  resource
) when {
  true
};forbid(
  principal == Principal::"dflbksifozhy",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"eaphhdtuwgom",
  resource == Resource::"vavxdjglsofu"
) when {
  true
};permit(
  principal == Principal::"pyhrmdcufcqx",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"yecncgfardrl",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"gecxhbsbcexd",
  resource == Resource::"inchvedkmfon"
) when {
  true
};permit(
  principal,
  action == Action::"oxehxgadwqvr",
  resource == Resource::"biwuwymeckvq"
) when {
  true
};forbid(
  principal,
  action == Action::"adseqgfmvjbb",
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ajbutxryzsra"
) when {
  true
};permit(
  principal == Principal::"dispcfnvmsbk",
  action,
  resource == Resource::"drwyrjwaheeo"
) when {
  true
};permit(
  principal == Principal::"whavzicbxxlv",
  action,
  resource == Resource::"xokttubgjsye"
) when {
  true
};forbid(
  principal,
  action == Action::"zyxdtvryguyl",
  resource
) when {
  true
};permit(
  principal == Principal::"ssjclvttqfxe",
  action == Action::"zyxdtvryguyl",
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};forbid(
  principal,
  action == Action::"adseqgfmvjbb",
  resource
) when {
  true
};permit(
  principal == Principal::"mziqzwabfbrh",
  action == Action::"yecncgfardrl",
  resource == Resource::"pqwnanlakjop"
) when {
  true
};forbid(
  principal,
  action == Action::"kmbdwspkvtfg",
  resource
) when {
  true
};permit(
  principal == Principal::"zecopqcenfgq",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"drklrhusxiix",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"zyxdtvryguyl",
  resource == Resource::"srxwbjqzxrgh"
) when {
  true
};forbid(
  principal == Principal::"ofgyatrijmgo",
  action,
  resource == Resource::"wthwwbztubhr"
) when {
  true
};permit(
  principal == Principal::"yvjjzrpmacol",
  action == Action::"drklrhusxiix",
  resource
) when {
  true
};permit(
  principal == Principal::"zjyrhpjscbbp",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"bmsqxkwwmxbd",
  resource == Resource::"drwyrjwaheeo"
) when {
  true
};permit(
  principal == Principal::"xzdnnodrqapi",
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};permit(
  principal == Principal::"vqpwqtnuabqh",
  action,
  resource == Resource::"vavxdjglsofu"
) when {
  true
};forbid(
  principal == Principal::"jqocyhrsmqjt",
  action == Action::"drklrhusxiix",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"qwttuibrbbgr"
) when {
  true
};permit(
  principal == Principal::"whavzicbxxlv",
  action == Action::"ykpsxanrepau",
  resource == Resource::"ajbutxryzsra"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};permit(
  principal == Principal::"rpsvssietntf",
  action == Action::"wegbeghgfeps",
  resource == Resource::"srxwbjqzxrgh"
) when {
  true
};permit(
  principal == Principal::"rpsvssietntf",
  action == Action::"yysewqkamtqj",
  resource == Resource::"ajbutxryzsra"
) when {
  true
};forbid(
  principal,
  action == Action::"wlsuxufpqtmr",
  resource
) when {
  true
};permit(
  principal == Principal::"pyhrmdcufcqx",
  action,
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};permit(
  principal == Principal::"amvmeibzxmsx",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"pdqaqryvzlsq",
  action == Action::"bmsqxkwwmxbd",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"wlsuxufpqtmr",
  resource == Resource::"xwhjixkfjnxs"
) when {
  true
};permit(
  principal == Principal::"xbuqbeudwgxh",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};forbid(
  principal,
  action == Action::"yimrpeazjxlz",
  resource == Resource::"vavxdjglsofu"
) when {
  true
};forbid(
  principal,
  action == Action::"yimrpeazjxlz",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"wthwwbztubhr"
) when {
  true
};permit(
  principal,
  action == Action::"eaphhdtuwgom",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"eaphhdtuwgom",
  resource
) when {
  true
};forbid(
  principal == Principal::"vhsewusivvyz",
  action == Action::"eznkoftfugqe",
  resource == Resource::"inchvedkmfon"
) when {
  true
};forbid(
  principal == Principal::"mziqzwabfbrh",
  action,
  resource == Resource::"elxkfuidmbqq"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"gisdxyeyrolr"
) when {
  true
};permit(
  principal,
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};permit(
  principal == Principal::"ssjclvttqfxe",
  action == Action::"llnqeaclsamg",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"wlsuxufpqtmr",
  resource
) when {
  true
};forbid(
  principal == Principal::"chrumrstfrtw",
  action == Action::"xapzhjcbzdlc",
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};forbid(
  principal == Principal::"vhsewusivvyz",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"pdqaqryvzlsq",
  action == Action::"xapzhjcbzdlc",
  resource
) when {
  true
};permit(
  principal == Principal::"yvjjzrpmacol",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"qrpzhkydumww",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"drwyrjwaheeo"
) when {
  true
};forbid(
  principal == Principal::"mrlwamjjaiwr",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"jqocyhrsmqjt",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"jbxgvzkebjva"
) when {
  true
};permit(
  principal == Principal::"dispcfnvmsbk",
  action,
  resource == Resource::"vavxdjglsofu"
) when {
  true
};forbid(
  principal,
  action == Action::"yimrpeazjxlz",
  resource == Resource::"jglopfkzivcy"
) when {
  true
};permit(
  principal == Principal::"whavzicbxxlv",
  action == Action::"kmbdwspkvtfg",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"dqfvsmwvnxlj",
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};forbid(
  principal,
  action == Action::"pbklvwalhytz",
  resource == Resource::"ikpbtpdgplxh"
) when {
  true
};forbid(
  principal == Principal::"vqpwqtnuabqh",
  action == Action::"kejhfvxakgif",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"dqfvsmwvnxlj",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"doqfseeyzrpi",
  resource
) when {
  true
};permit(
  principal == Principal::"ofgyatrijmgo",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"pfjozsmouwdr",
  resource == Resource::"xwhjixkfjnxs"
) when {
  true
};forbid(
  principal == Principal::"dflbksifozhy",
  action == Action::"bmsqxkwwmxbd",
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};permit(
  principal,
  action == Action::"eaphhdtuwgom",
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};forbid(
  principal == Principal::"zjyrhpjscbbp",
  action,
  resource == Resource::"nwztsonbjwas"
) when {
  true
};forbid(
  principal == Principal::"kogrqztpluqo",
  action,
  resource == Resource::"xtgcvhtqyjuf"
) when {
  true
};permit(
  principal,
  action == Action::"oxehxgadwqvr",
  resource
) when {
  true
};forbid(
  principal == Principal::"rpsvssietntf",
  action == Action::"nzvgzgtjqjen",
  resource
) when {
  true
};permit(
  principal == Principal::"whavzicbxxlv",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"ssjclvttqfxe",
  action,
  resource == Resource::"oqrbyaozcasi"
) when {
  true
};forbid(
  principal == Principal::"dispcfnvmsbk",
  action == Action::"uggkhcwckerj",
  resource
) when {
  true
};permit(
  principal == Principal::"xbuqbeudwgxh",
  action,
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};forbid(
  principal == Principal::"chrumrstfrtw",
  action == Action::"wlsuxufpqtmr",
  resource == Resource::"ajbutxryzsra"
) when {
  true
};forbid(
  principal == Principal::"pdqaqryvzlsq",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"jqocyhrsmqjt",
  action,
  resource == Resource::"oqrbyaozcasi"
) when {
  true
};permit(
  principal == Principal::"mziqzwabfbrh",
  action == Action::"wlsuxufpqtmr",
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"nwztsonbjwas"
) when {
  true
};forbid(
  principal,
  action == Action::"dqfvsmwvnxlj",
  resource == Resource::"jbxgvzkebjva"
) when {
  true
};permit(
  principal,
  action == Action::"kmbdwspkvtfg",
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};forbid(
  principal,
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};permit(
  principal == Principal::"chrumrstfrtw",
  action == Action::"yimrpeazjxlz",
  resource
) when {
  true
};permit(
  principal == Principal::"whavzicbxxlv",
  action == Action::"eaphhdtuwgom",
  resource
) when {
  true
};permit(
  principal == Principal::"kogrqztpluqo",
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"kejhfvxakgif",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"drklrhusxiix",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"uggkhcwckerj",
  resource
) when {
  true
};permit(
  principal == Principal::"ofgyatrijmgo",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"nzvgzgtjqjen",
  resource
) when {
  true
};permit(
  principal == Principal::"vhsewusivvyz",
  action == Action::"wjsugdswubof",
  resource == Resource::"czrozycfjskx"
) when {
  true
};permit(
  principal,
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};permit(
  principal == Principal::"dispcfnvmsbk",
  action,
  resource == Resource::"inchvedkmfon"
) when {
  true
};permit(
  principal == Principal::"rpsvssietntf",
  action == Action::"eznkoftfugqe",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"uadsypfdkadt",
  resource
) when {
  true
};forbid(
  principal == Principal::"dispcfnvmsbk",
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};forbid(
  principal == Principal::"ofgyatrijmgo",
  action,
  resource == Resource::"wthwwbztubhr"
) when {
  true
};permit(
  principal == Principal::"kwvjsetpsmlt",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"vqpwqtnuabqh",
  action == Action::"yypwsijfobaw",
  resource == Resource::"qwttuibrbbgr"
) when {
  true
};permit(
  principal == Principal::"dispcfnvmsbk",
  action == Action::"drklrhusxiix",
  resource == Resource::"ulznxoseohpu"
) when {
  true
};permit(
  principal == Principal::"velciusvmoxg",
  action,
  resource == Resource::"biwuwymeckvq"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"inchvedkmfon"
) when {
  true
};forbid(
  principal == Principal::"qrpzhkydumww",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"cylquarfmrwe",
  resource == Resource::"pqwnanlakjop"
) when {
  true
};forbid(
  principal == Principal::"pyhrmdcufcqx",
  action,
  resource == Resource::"jglopfkzivcy"
) when {
  true
};forbid(
  principal == Principal::"clpwwnowcfxq",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"wmddwgyhrjgx",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"dflbksifozhy",
  action == Action::"wegbeghgfeps",
  resource == Resource::"gqffhvppakdw"
) when {
  true
};permit(
  principal,
  action == Action::"pfjozsmouwdr",
  resource == Resource::"oqrbyaozcasi"
) when {
  true
};permit(
  principal,
  action == Action::"xenqqlcueghi",
  resource == Resource::"forqvcikcjnd"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"xokttubgjsye"
) when {
  true
};forbid(
  principal,
  action == Action::"yimrpeazjxlz",
  resource
) when {
  true
};permit(
  principal == Principal::"chrumrstfrtw",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"yvmdixfqccis",
  action,
  resource == Resource::"srxwbjqzxrgh"
) when {
  true
};permit(
  principal == Principal::"mrlwamjjaiwr",
  action,
  resource == Resource::"forqvcikcjnd"
) when {
  true
};permit(
  principal,
  action == Action::"ykpsxanrepau",
  resource
) when {
  true
};permit(
  principal == Principal::"yvmdixfqccis",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"uadsypfdkadt",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal,
  action == Action::"xenqqlcueghi",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"oldrrovawflz"
) when {
  true
};permit(
  principal == Principal::"yvmdixfqccis",
  action,
  resource == Resource::"nwztsonbjwas"
) when {
  true
};forbid(
  principal == Principal::"zecopqcenfgq",
  action == Action::"yysewqkamtqj",
  resource
) when {
  true
};permit(
  principal == Principal::"yvmdixfqccis",
  action == Action::"gecxhbsbcexd",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"xokttubgjsye"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"gisdxyeyrolr"
) when {
  true
};forbid(
  principal == Principal::"dispcfnvmsbk",
  action == Action::"yysewqkamtqj",
  resource == Resource::"ikpbtpdgplxh"
) when {
  true
};forbid(
  principal,
  action == Action::"nzvgzgtjqjen",
  resource
) when {
  true
};forbid(
  principal == Principal::"ofgyatrijmgo",
  action == Action::"gbzjaithkydf",
  resource == Resource::"drwyrjwaheeo"
) when {
  true
};permit(
  principal == Principal::"mziqzwabfbrh",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"dqfvsmwvnxlj",
  resource
) when {
  true
};permit(
  principal == Principal::"qrpzhkydumww",
  action == Action::"pfjozsmouwdr",
  resource == Resource::"batjhvjfqpkc"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"tkwwyosyiusm"
) when {
  true
};permit(
  principal == Principal::"pdqaqryvzlsq",
  action,
  resource == Resource::"czrozycfjskx"
) when {
  true
};forbid(
  principal == Principal::"kwvjsetpsmlt",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"doqfseeyzrpi",
  resource == Resource::"czrozycfjskx"
) when {
  true
};permit(
  principal == Principal::"rgzdhgznrmmx",
  action == Action::"bmsqxkwwmxbd",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"gkmzlzkyizur",
  resource == Resource::"pqwnanlakjop"
) when {
  true
};permit(
  principal,
  action == Action::"pfjozsmouwdr",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"kejhfvxakgif",
  resource
) when {
  true
};permit(
  principal == Principal::"yvmdixfqccis",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"gbzjaithkydf",
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};forbid(
  principal == Principal::"pyhrmdcufcqx",
  action == Action::"yimrpeazjxlz",
  resource
) when {
  true
};forbid(
  principal == Principal::"chrumrstfrtw",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"gkmzlzkyizur",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"yysewqkamtqj",
  resource == Resource::"czrozycfjskx"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ulznxoseohpu"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"vavxdjglsofu"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"ikpbtpdgplxh"
) when {
  true
};forbid(
  principal,
  action == Action::"wjsugdswubof",
  resource == Resource::"pqwnanlakjop"
) when {
  true
};forbid(
  principal == Principal::"velciusvmoxg",
  action == Action::"xenqqlcueghi",
  resource
) when {
  true
};forbid(
  principal == Principal::"uifdrmilqkbk",
  action == Action::"eaphhdtuwgom",
  resource == Resource::"zjsemhuxihbu"
) when {
  true
};forbid(
  principal,
  action == Action::"pfjozsmouwdr",
  resource == Resource::"gisdxyeyrolr"
) when {
  true
};permit(
  principal,
  action == Action::"oxehxgadwqvr",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};permit(
  principal,
  action == Action::"eaphhdtuwgom",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"xenqqlcueghi",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"zyxdtvryguyl",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"drwyrjwaheeo"
) when {
  true
};forbid(
  principal == Principal::"wmddwgyhrjgx",
  action,
  resource == Resource::"pgpaxlbaozhf"
) when {
  true
};permit(
  principal,
  action == Action::"gkmzlzkyizur",
  resource == Resource::"ikpbtpdgplxh"
) when {
  true
};permit(
  principal,
  action == Action::"xenqqlcueghi",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"ykpsxanrepau",
  resource
) when {
  true
};permit(
  principal == Principal::"rpsvssietntf",
  action == Action::"xapzhjcbzdlc",
  resource
) when {
  true
};forbid(
  principal == Principal::"chrumrstfrtw",
  action,
  resource == Resource::"vavxdjglsofu"
) when {
  true
};forbid(
  principal,
  action == Action::"doqfseeyzrpi",
  resource
) when {
  true
};forbid(
  principal == Principal::"dispcfnvmsbk",
  action == Action::"gbzjaithkydf",
  resource == Resource::"pqwnanlakjop"
) when {
  true
};permit(
  principal,
  action == Action::"yypwsijfobaw",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"bmsqxkwwmxbd",
  resource == Resource::"czrozycfjskx"
) when {
  true
};forbid(
  principal,
  action == Action::"yimrpeazjxlz",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"cylquarfmrwe",
  resource
) when {
  true
};permit(
  principal == Principal::"amvmeibzxmsx",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"gkmzlzkyizur",
  resource == Resource::"dzhvepjeoqlq"
) when {
  true
};forbid(
  principal == Principal::"ssjclvttqfxe",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"wlsuxufpqtmr",
  resource == Resource::"vavxdjglsofu"
) when {
  true
};forbid(
  principal,
  action == Action::"yysewqkamtqj",
  resource == Resource::"srxwbjqzxrgh"
) when {
  true
};permit(
  principal == Principal::"yvjjzrpmacol",
  action,
  resource == Resource::"oqrbyaozcasi"
) when {
  true
};forbid(
  principal,
  action == Action::"gbzjaithkydf",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"wegbeghgfeps",
  resource == Resource::"xokttubgjsye"
) when {
  true
};forbid(
  principal,
  action == Action::"bmsqxkwwmxbd",
  resource
) when {
  true
};forbid(
  principal == Principal::"xbuqbeudwgxh",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"ofgyatrijmgo",
  action == Action::"adseqgfmvjbb",
  resource == Resource::"wthwwbztubhr"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"xokttubgjsye"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"vavxdjglsofu"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"nwztsonbjwas"
) when {
  true
};permit(
  principal,
  action == Action::"yecncgfardrl",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"vavxdjglsofu"
) when {
  true
};permit(
  principal == Principal::"whavzicbxxlv",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"jbxgvzkebjva"
) when {
  true
};permit(
  principal == Principal::"amvmeibzxmsx",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"dispcfnvmsbk",
  action == Action::"yecncgfardrl",
  resource == Resource::"styepjegwuco"
) when {
  true
};forbid(
  principal,
  action == Action::"doqfseeyzrpi",
  resource
) when {
  true
};forbid(
  principal == Principal::"dispcfnvmsbk",
  action == Action::"gbzjaithkydf",
  resource
) when {
  true
};forbid(
  principal == Principal::"vqpwqtnuabqh",
  action == Action::"wjsugdswubof",
  resource == Resource::"rnjujbtkhjlo"
) when {
  true
};forbid(
  principal,
  action == Action::"uadsypfdkadt",
  resource
) when {
  true
};permit(
  principal == Principal::"velciusvmoxg",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"forqvcikcjnd"
) when {
  true
};forbid(
  principal == Principal::"vhsewusivvyz",
  action == Action::"yysewqkamtqj",
  resource
) when {
  true
};