forbid(
  principal == Principal::"lbkmtgndiegs",
  action,
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};forbid(
  principal == Principal::"yfmfmxoxfosd",
  action == Action::"qsphwjsrislv",
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};forbid(
  principal == Principal::"qgnairntuguo",
  action == Action::"dllrwzhequoh",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"dwfrhuszemyk",
  resource == Resource::"smbssuhglplo"
) when {
  true
};forbid(
  principal,
  action == Action::"rfkjqajrgbyl",
  resource == Resource::"fbredeszwrzn"
) when {
  true
};permit(
  principal == Principal::"ekqfgrkxyiid",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"wnkxwledpjjl",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"zpdplhiwhfxe",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"vkvrohivjxad",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"zpdplhiwhfxe",
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};forbid(
  principal,
  action == Action::"dllrwzhequoh",
  resource == Resource::"wguuxqugfrql"
) when {
  true
};forbid(
  principal == Principal::"dnfnsnbevosf",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"kouqxvovaxiz",
  action,
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};forbid(
  principal == Principal::"euczuvcrhnyw",
  action == Action::"hcltmblyzyxf",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"qsphwjsrislv",
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal == Principal::"fykhjpzumdaa",
  action,
  resource == Resource::"mdocnzuopjvx"
) when {
  true
};forbid(
  principal,
  action == Action::"dllrwzhequoh",
  resource == Resource::"pxbjcjbxjwjp"
) when {
  true
};permit(
  principal == Principal::"hcpkmvhfiymn",
  action,
  resource == Resource::"ojegmylgdzap"
) when {
  true
};permit(
  principal == Principal::"fohhrlglkjwz",
  action == Action::"famgyptaffdm",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"atwmtdanenfv"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};permit(
  principal == Principal::"xpkryiciwzgf",
  action == Action::"hcltmblyzyxf",
  resource == Resource::"amemmojhemhz"
) when {
  true
};forbid(
  principal == Principal::"hcpkmvhfiymn",
  action == Action::"rhdwcsgghxwf",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};forbid(
  principal,
  action == Action::"hajgxmbrysdv",
  resource
) when {
  true
};permit(
  principal == Principal::"fohhrlglkjwz",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"seofhjtqtpdg",
  action == Action::"famgyptaffdm",
  resource == Resource::"ojegmylgdzap"
) when {
  true
};forbid(
  principal,
  action == Action::"gpwlgdwrkauq",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"vkvrohivjxad",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};forbid(
  principal,
  action == Action::"rhdwcsgghxwf",
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};forbid(
  principal == Principal::"fykhjpzumdaa",
  action,
  resource == Resource::"gjneumgbuhpb"
) when {
  true
};forbid(
  principal == Principal::"bckfogukcrqc",
  action,
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};permit(
  principal == Principal::"euczuvcrhnyw",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"lbkmtgndiegs",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"gjneumgbuhpb"
) when {
  true
};permit(
  principal == Principal::"dnfnsnbevosf",
  action,
  resource == Resource::"fbredeszwrzn"
) when {
  true
};permit(
  principal == Principal::"ycxzoipplruh",
  action,
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};forbid(
  principal == Principal::"fohhrlglkjwz",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"lbkmtgndiegs",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"atwmtdanenfv"
) when {
  true
};forbid(
  principal == Principal::"aagogabfkmox",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"cehgsohadlet",
  action == Action::"vyiqkkikgpmn",
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};permit(
  principal == Principal::"ekqfgrkxyiid",
  action == Action::"hjpqojifapdt",
  resource
) when {
  true
};permit(
  principal == Principal::"xpkryiciwzgf",
  action,
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};forbid(
  principal == Principal::"thgthwrcyish",
  action,
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal == Principal::"zyvbbulhwnwn",
  action == Action::"dwfrhuszemyk",
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};forbid(
  principal == Principal::"euczuvcrhnyw",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"uocqgzryuaak",
  resource == Resource::"wguuxqugfrql"
) when {
  true
};permit(
  principal == Principal::"cehgsohadlet",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"wwkvlqcrjgyy",
  action == Action::"hajgxmbrysdv",
  resource
) when {
  true
};permit(
  principal == Principal::"fkwlplfdaijq",
  action == Action::"fublzswlrebp",
  resource == Resource::"mdocnzuopjvx"
) when {
  true
};forbid(
  principal == Principal::"xpkryiciwzgf",
  action,
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};forbid(
  principal,
  action == Action::"vkvrohivjxad",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"hajgxmbrysdv",
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};permit(
  principal == Principal::"dnfnsnbevosf",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"lbkmtgndiegs",
  action,
  resource == Resource::"brucmhxiqwil"
) when {
  true
};permit(
  principal,
  action == Action::"rpubpuedyiug",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"famgyptaffdm",
  resource
) when {
  true
};permit(
  principal == Principal::"kouqxvovaxiz",
  action,
  resource == Resource::"amemmojhemhz"
) when {
  true
};permit(
  principal == Principal::"pagxgdwtmtqv",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"axolfruiaiqx",
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};forbid(
  principal == Principal::"fykhjpzumdaa",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"xpkryiciwzgf",
  action == Action::"zlsludhalojy",
  resource
) when {
  true
};forbid(
  principal == Principal::"qgnairntuguo",
  action == Action::"jowejrciproe",
  resource
) when {
  true
};forbid(
  principal == Principal::"aagogabfkmox",
  action == Action::"vkvrohivjxad",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"utjqmbyirkiy",
  resource == Resource::"smbssuhglplo"
) when {
  true
};forbid(
  principal == Principal::"vkktinyvlpgi",
  action,
  resource == Resource::"khdukfbxllxw"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ojegmylgdzap"
) when {
  true
};forbid(
  principal == Principal::"kouqxvovaxiz",
  action == Action::"qsphwjsrislv",
  resource
) when {
  true
};permit(
  principal == Principal::"cehgsohadlet",
  action == Action::"uocqgzryuaak",
  resource == Resource::"gjneumgbuhpb"
) when {
  true
};forbid(
  principal == Principal::"wwkvlqcrjgyy",
  action == Action::"cttpxcwfboar",
  resource
) when {
  true
};permit(
  principal == Principal::"imvcevihxbhs",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"uhikvtbavylh",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"ulfsjgvyislm",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"xqifgqptbljq",
  action == Action::"hajgxmbrysdv",
  resource
) when {
  true
};forbid(
  principal == Principal::"imvcevihxbhs",
  action == Action::"xssayeebuwhq",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"khdukfbxllxw"
) when {
  true
};forbid(
  principal,
  action == Action::"zpdplhiwhfxe",
  resource == Resource::"htdpuvkrildr"
) when {
  true
};forbid(
  principal == Principal::"iuwfronkotry",
  action == Action::"nzkbqfcwhofn",
  resource == Resource::"mdocnzuopjvx"
) when {
  true
};forbid(
  principal == Principal::"qgnairntuguo",
  action == Action::"nzkbqfcwhofn",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"hajgxmbrysdv",
  resource
) when {
  true
};permit(
  principal == Principal::"pagxgdwtmtqv",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"lbkmtgndiegs",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"fkwlplfdaijq",
  action == Action::"oyjsvzvxiikm",
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};forbid(
  principal,
  action == Action::"hajgxmbrysdv",
  resource
) when {
  true
};permit(
  principal == Principal::"pagxgdwtmtqv",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"hcltmblyzyxf",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"zpdplhiwhfxe",
  resource
) when {
  true
};forbid(
  principal == Principal::"ekqfgrkxyiid",
  action,
  resource == Resource::"uymaurgpenxx"
) when {
  true
};forbid(
  principal,
  action == Action::"fublzswlrebp",
  resource == Resource::"mbtgbwiwjoiy"
) when {
  true
};permit(
  principal,
  action == Action::"jedunopwhdab",
  resource == Resource::"smbssuhglplo"
) when {
  true
};forbid(
  principal == Principal::"wnkxwledpjjl",
  action == Action::"dwfrhuszemyk",
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};forbid(
  principal == Principal::"cehgsohadlet",
  action == Action::"uocqgzryuaak",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};permit(
  principal,
  action == Action::"oyjsvzvxiikm",
  resource
) when {
  true
};forbid(
  principal == Principal::"kouqxvovaxiz",
  action,
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};permit(
  principal == Principal::"rcptcuvbzswx",
  action == Action::"axolfruiaiqx",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"dllrwzhequoh",
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};forbid(
  principal,
  action == Action::"rpubpuedyiug",
  resource == Resource::"ojegmylgdzap"
) when {
  true
};permit(
  principal == Principal::"qgnairntuguo",
  action,
  resource == Resource::"uymaurgpenxx"
) when {
  true
};forbid(
  principal,
  action == Action::"famgyptaffdm",
  resource
) when {
  true
};forbid(
  principal == Principal::"vkktinyvlpgi",
  action,
  resource == Resource::"klqpkwgrazag"
) when {
  true
};forbid(
  principal == Principal::"lbkmtgndiegs",
  action == Action::"zlsludhalojy",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"khdukfbxllxw"
) when {
  true
};permit(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"fublzswlrebp",
  resource
) when {
  true
};permit(
  principal == Principal::"thgthwrcyish",
  action,
  resource == Resource::"khdukfbxllxw"
) when {
  true
};permit(
  principal,
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};forbid(
  principal == Principal::"fohhrlglkjwz",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"krpqlztqpgsk",
  action,
  resource == Resource::"hwatqlfsxohl"
) when {
  true
};permit(
  principal,
  action == Action::"utjqmbyirkiy",
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};permit(
  principal == Principal::"uhikvtbavylh",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"qsphwjsrislv",
  resource == Resource::"mbtgbwiwjoiy"
) when {
  true
};forbid(
  principal,
  action == Action::"vczrnqvzhuul",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"gpwlgdwrkauq",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};permit(
  principal == Principal::"imvcevihxbhs",
  action == Action::"jowejrciproe",
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal == Principal::"odofubfypovp",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"dllrwzhequoh",
  resource
) when {
  true
};permit(
  principal == Principal::"request",
  action == Action::"request",
  resource == Resource::"request"
) when {
  true
};forbid(
  principal == Principal::"seofhjtqtpdg",
  action,
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};forbid(
  principal == Principal::"syppxromuyqb",
  action,
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};forbid(
  principal,
  action == Action::"cttpxcwfboar",
  resource
) when {
  true
};permit(
  principal == Principal::"fkwlplfdaijq",
  action == Action::"xssayeebuwhq",
  resource
) when {
  true
};forbid(
  principal == Principal::"xpkryiciwzgf",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal == Principal::"odofubfypovp",
  action,
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};forbid(
  principal,
  action == Action::"rpubpuedyiug",
  resource == Resource::"smbssuhglplo"
) when {
  true
};permit(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"famgyptaffdm",
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};permit(
  principal == Principal::"xpkryiciwzgf",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"odofubfypovp",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"iuwfronkotry",
  action == Action::"jadypypnxafk",
  resource
) when {
  true
};forbid(
  principal == Principal::"iuwfronkotry",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"syppxromuyqb",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"odofubfypovp",
  action == Action::"oyjsvzvxiikm",
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};forbid(
  principal == Principal::"xpkryiciwzgf",
  action == Action::"hajgxmbrysdv",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"cttpxcwfboar",
  resource == Resource::"wguuxqugfrql"
) when {
  true
};forbid(
  principal,
  action == Action::"hjpqojifapdt",
  resource
) when {
  true
};forbid(
  principal == Principal::"hcpkmvhfiymn",
  action == Action::"vczrnqvzhuul",
  resource == Resource::"atwmtdanenfv"
) when {
  true
};forbid(
  principal == Principal::"krpqlztqpgsk",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"jedunopwhdab",
  resource == Resource::"tdhcfedimojq"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"gncgyolgqhrr"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};forbid(
  principal,
  action == Action::"hjpqojifapdt",
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};permit(
  principal,
  action == Action::"zpdplhiwhfxe",
  resource
) when {
  true
};forbid(
  principal == Principal::"aagogabfkmox",
  action == Action::"zpdplhiwhfxe",
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};permit(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"dwfrhuszemyk",
  resource
) when {
  true
};permit(
  principal == Principal::"yfmfmxoxfosd",
  action,
  resource == Resource::"atwmtdanenfv"
) when {
  true
};forbid(
  principal,
  action == Action::"xssayeebuwhq",
  resource == Resource::"mdocnzuopjvx"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};permit(
  principal == Principal::"odofubfypovp",
  action,
  resource == Resource::"amemmojhemhz"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ojegmylgdzap"
) when {
  true
};permit(
  principal,
  action == Action::"veyzqxfgmvow",
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};permit(
  principal == Principal::"thgthwrcyish",
  action,
  resource == Resource::"lputleedekcx"
) when {
  true
};forbid(
  principal == Principal::"rcptcuvbzswx",
  action,
  resource == Resource::"lputleedekcx"
) when {
  true
};forbid(
  principal,
  action == Action::"jadypypnxafk",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"jedunopwhdab",
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};forbid(
  principal == Principal::"ekqfgrkxyiid",
  action == Action::"jadypypnxafk",
  resource == Resource::"smbssuhglplo"
) when {
  true
};permit(
  principal == Principal::"uhikvtbavylh",
  action,
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};permit(
  principal == Principal::"bckfogukcrqc",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"qgnairntuguo",
  action,
  resource == Resource::"smbssuhglplo"
) when {
  true
};forbid(
  principal == Principal::"thgthwrcyish",
  action == Action::"hjpqojifapdt",
  resource == Resource::"fbredeszwrzn"
) when {
  true
};permit(
  principal,
  action == Action::"jadypypnxafk",
  resource
) when {
  true
};forbid(
  principal == Principal::"wwkvlqcrjgyy",
  action == Action::"fublzswlrebp",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"famgyptaffdm",
  resource == Resource::"uymaurgpenxx"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};permit(
  principal,
  action == Action::"famgyptaffdm",
  resource
) when {
  true
};forbid(
  principal == Principal::"uhikvtbavylh",
  action,
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"lputleedekcx"
) when {
  true
};forbid(
  principal == Principal::"xqifgqptbljq",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"dwfrhuszemyk",
  resource == Resource::"htdpuvkrildr"
) when {
  true
};permit(
  principal == Principal::"fykhjpzumdaa",
  action,
  resource == Resource::"klsqkshymqpk"
) when {
  true
};forbid(
  principal == Principal::"yfmfmxoxfosd",
  action == Action::"vyiqkkikgpmn",
  resource
) when {
  true
};forbid(
  principal == Principal::"imvcevihxbhs",
  action == Action::"uocqgzryuaak",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"fublzswlrebp",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"dwfrhuszemyk",
  resource == Resource::"lputleedekcx"
) when {
  true
};permit(
  principal == Principal::"kouqxvovaxiz",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"ekqfgrkxyiid",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"vkvrohivjxad",
  resource == Resource::"smbssuhglplo"
) when {
  true
};forbid(
  principal,
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};permit(
  principal == Principal::"yfmfmxoxfosd",
  action,
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};forbid(
  principal == Principal::"imvcevihxbhs",
  action == Action::"dllrwzhequoh",
  resource
) when {
  true
};permit(
  principal == Principal::"ekqfgrkxyiid",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"amemmojhemhz"
) when {
  true
};forbid(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"ayeusmztlcni",
  resource == Resource::"klsqkshymqpk"
) when {
  true
};permit(
  principal,
  action == Action::"jadypypnxafk",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"mbtgbwiwjoiy"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};permit(
  principal == Principal::"hcpkmvhfiymn",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"wnkxwledpjjl",
  action == Action::"cttpxcwfboar",
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};forbid(
  principal == Principal::"ulfsjgvyislm",
  action == Action::"syjregyoqldd",
  resource == Resource::"gncgyolgqhrr"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};forbid(
  principal == Principal::"fkwlplfdaijq",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"rfkjqajrgbyl",
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};permit(
  principal,
  action == Action::"fublzswlrebp",
  resource == Resource::"hwatqlfsxohl"
) when {
  true
};permit(
  principal == Principal::"zyvbbulhwnwn",
  action == Action::"cttpxcwfboar",
  resource
) when {
  true
};permit(
  principal == Principal::"yfmfmxoxfosd",
  action == Action::"zpdplhiwhfxe",
  resource == Resource::"khdukfbxllxw"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"amemmojhemhz"
) when {
  true
};permit(
  principal == Principal::"hcpkmvhfiymn",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"uymaurgpenxx"
) when {
  true
};forbid(
  principal,
  action == Action::"vczrnqvzhuul",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"qsphwjsrislv",
  resource == Resource::"uymaurgpenxx"
) when {
  true
};forbid(
  principal == Principal::"fykhjpzumdaa",
  action == Action::"qsphwjsrislv",
  resource == Resource::"tdhcfedimojq"
) when {
  true
};forbid(
  principal,
  action == Action::"oyjsvzvxiikm",
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};permit(
  principal == Principal::"euczuvcrhnyw",
  action == Action::"hcltmblyzyxf",
  resource
) when {
  true
};forbid(
  principal == Principal::"cehgsohadlet",
  action == Action::"veyzqxfgmvow",
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};forbid(
  principal,
  action == Action::"jadypypnxafk",
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};permit(
  principal == Principal::"dnfnsnbevosf",
  action == Action::"cttpxcwfboar",
  resource
) when {
  true
};forbid(
  principal == Principal::"wwkvlqcrjgyy",
  action == Action::"uocqgzryuaak",
  resource == Resource::"mbtgbwiwjoiy"
) when {
  true
};forbid(
  principal == Principal::"syppxromuyqb",
  action == Action::"qsphwjsrislv",
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"brucmhxiqwil"
) when {
  true
};forbid(
  principal == Principal::"iuwfronkotry",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"zyvbbulhwnwn",
  action == Action::"xssayeebuwhq",
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};forbid(
  principal == Principal::"dnfnsnbevosf",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"ayeusmztlcni",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ojegmylgdzap"
) when {
  true
};forbid(
  principal == Principal::"vkktinyvlpgi",
  action == Action::"vkvrohivjxad",
  resource
) when {
  true
};forbid(
  principal == Principal::"wnkxwledpjjl",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"cehgsohadlet",
  action,
  resource == Resource::"gncgyolgqhrr"
) when {
  true
};forbid(
  principal,
  action == Action::"utjqmbyirkiy",
  resource
) when {
  true
};forbid(
  principal == Principal::"seofhjtqtpdg",
  action,
  resource == Resource::"klsqkshymqpk"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"fbredeszwrzn"
) when {
  true
};forbid(
  principal == Principal::"xqifgqptbljq",
  action == Action::"nzkbqfcwhofn",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"axolfruiaiqx",
  resource
) when {
  true
};permit(
  principal == Principal::"seofhjtqtpdg",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"hjpqojifapdt",
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"gncgyolgqhrr"
) when {
  true
};permit(
  principal,
  action == Action::"dwfrhuszemyk",
  resource == Resource::"gncgyolgqhrr"
) when {
  true
};forbid(
  principal == Principal::"lbkmtgndiegs",
  action,
  resource == Resource::"pxbjcjbxjwjp"
) when {
  true
};forbid(
  principal == Principal::"bckfogukcrqc",
  action == Action::"uocqgzryuaak",
  resource
) when {
  true
};forbid(
  principal == Principal::"fohhrlglkjwz",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"ulfsjgvyislm",
  action == Action::"zlsludhalojy",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"jadypypnxafk",
  resource == Resource::"wguuxqugfrql"
) when {
  true
};permit(
  principal == Principal::"pagxgdwtmtqv",
  action == Action::"vczrnqvzhuul",
  resource
) when {
  true
};forbid(
  principal == Principal::"kouqxvovaxiz",
  action,
  resource == Resource::"gjneumgbuhpb"
) when {
  true
};forbid(
  principal,
  action == Action::"jadypypnxafk",
  resource
) when {
  true
};forbid(
  principal == Principal::"ulfsjgvyislm",
  action,
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};forbid(
  principal == Principal::"fkwlplfdaijq",
  action,
  resource == Resource::"uymaurgpenxx"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};permit(
  principal,
  action == Action::"hajgxmbrysdv",
  resource
) when {
  true
};permit(
  principal == Principal::"ekqfgrkxyiid",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"kouqxvovaxiz",
  action,
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};permit(
  principal == Principal::"odofubfypovp",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"smbssuhglplo"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"klqpkwgrazag"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};permit(
  principal,
  action == Action::"hcltmblyzyxf",
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};permit(
  principal,
  action == Action::"axolfruiaiqx",
  resource == Resource::"lputleedekcx"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};permit(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"hcltmblyzyxf",
  resource
) when {
  true
};forbid(
  principal == Principal::"fykhjpzumdaa",
  action == Action::"ayeusmztlcni",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"nzkbqfcwhofn",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"amemmojhemhz"
) when {
  true
};permit(
  principal == Principal::"wnkxwledpjjl",
  action == Action::"hcltmblyzyxf",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"htdpuvkrildr"
) when {
  true
};permit(
  principal == Principal::"xpkryiciwzgf",
  action == Action::"rhdwcsgghxwf",
  resource
) when {
  true
};permit(
  principal == Principal::"xpkryiciwzgf",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"qsphwjsrislv",
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};forbid(
  principal == Principal::"dnfnsnbevosf",
  action,
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};forbid(
  principal,
  action == Action::"axolfruiaiqx",
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};permit(
  principal == Principal::"rcptcuvbzswx",
  action == Action::"nzkbqfcwhofn",
  resource == Resource::"hwatqlfsxohl"
) when {
  true
};permit(
  principal == Principal::"ulfsjgvyislm",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};permit(
  principal == Principal::"kouqxvovaxiz",
  action == Action::"gpwlgdwrkauq",
  resource
) when {
  true
};forbid(
  principal == Principal::"krpqlztqpgsk",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};forbid(
  principal == Principal::"imvcevihxbhs",
  action == Action::"vczrnqvzhuul",
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"fbredeszwrzn"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"ojegmylgdzap"
) when {
  true
};permit(
  principal == Principal::"xpkryiciwzgf",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"fykhjpzumdaa",
  action == Action::"nzkbqfcwhofn",
  resource == Resource::"khdukfbxllxw"
) when {
  true
};forbid(
  principal == Principal::"fohhrlglkjwz",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"ekqfgrkxyiid",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"syppxromuyqb",
  action,
  resource == Resource::"hwatqlfsxohl"
) when {
  true
};permit(
  principal,
  action == Action::"ayeusmztlcni",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"dwfrhuszemyk",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"syjregyoqldd",
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal == Principal::"vkktinyvlpgi",
  action == Action::"nzkbqfcwhofn",
  resource == Resource::"htdpuvkrildr"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"wguuxqugfrql"
) when {
  true
};permit(
  principal,
  action == Action::"rpubpuedyiug",
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};permit(
  principal == Principal::"vkktinyvlpgi",
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};forbid(
  principal == Principal::"vkktinyvlpgi",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"ekqfgrkxyiid",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"xssayeebuwhq",
  resource == Resource::"khdukfbxllxw"
) when {
  true
};permit(
  principal,
  action == Action::"axolfruiaiqx",
  resource == Resource::"khdukfbxllxw"
) when {
  true
};forbid(
  principal,
  action == Action::"uocqgzryuaak",
  resource == Resource::"tdhcfedimojq"
) when {
  true
};permit(
  principal,
  action == Action::"dwfrhuszemyk",
  resource == Resource::"klsqkshymqpk"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"pxbjcjbxjwjp"
) when {
  true
};forbid(
  principal,
  action == Action::"wtgwbalgzsgr",
  resource == Resource::"mdocnzuopjvx"
) when {
  true
};permit(
  principal,
  action == Action::"dllrwzhequoh",
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};permit(
  principal == Principal::"vkktinyvlpgi",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"wnkxwledpjjl",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"qsphwjsrislv",
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};permit(
  principal == Principal::"zyvbbulhwnwn",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};forbid(
  principal,
  action == Action::"ayeusmztlcni",
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};permit(
  principal,
  action == Action::"vczrnqvzhuul",
  resource
) when {
  true
};forbid(
  principal == Principal::"lbkmtgndiegs",
  action == Action::"hjpqojifapdt",
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};permit(
  principal,
  action == Action::"jedunopwhdab",
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};permit(
  principal == Principal::"krpqlztqpgsk",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"hcpkmvhfiymn",
  action == Action::"vczrnqvzhuul",
  resource
) when {
  true
};permit(
  principal == Principal::"syppxromuyqb",
  action,
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};forbid(
  principal == Principal::"hcpkmvhfiymn",
  action == Action::"vczrnqvzhuul",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"gpwlgdwrkauq",
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};forbid(
  principal == Principal::"xqifgqptbljq",
  action == Action::"rfkjqajrgbyl",
  resource
) when {
  true
};forbid(
  principal == Principal::"wwkvlqcrjgyy",
  action == Action::"hajgxmbrysdv",
  resource == Resource::"brucmhxiqwil"
) when {
  true
};forbid(
  principal,
  action == Action::"cttpxcwfboar",
  resource
) when {
  true
};permit(
  principal == Principal::"wnkxwledpjjl",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"rfkjqajrgbyl",
  resource
) when {
  true
};permit(
  principal == Principal::"imvcevihxbhs",
  action == Action::"syjregyoqldd",
  resource
) when {
  true
};permit(
  principal == Principal::"cehgsohadlet",
  action,
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};permit(
  principal,
  action == Action::"xssayeebuwhq",
  resource
) when {
  true
};permit(
  principal == Principal::"krpqlztqpgsk",
  action,
  resource == Resource::"hwatqlfsxohl"
) when {
  true
};permit(
  principal,
  action == Action::"jowejrciproe",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"jadypypnxafk",
  resource == Resource::"htdpuvkrildr"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"khdukfbxllxw"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"fbredeszwrzn"
) when {
  true
};forbid(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"hcltmblyzyxf",
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};permit(
  principal == Principal::"ycxzoipplruh",
  action == Action::"hajgxmbrysdv",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"klsqkshymqpk"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"amemmojhemhz"
) when {
  true
};forbid(
  principal == Principal::"yfmfmxoxfosd",
  action == Action::"veyzqxfgmvow",
  resource == Resource::"fbredeszwrzn"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"atwmtdanenfv"
) when {
  true
};permit(
  principal == Principal::"aagogabfkmox",
  action == Action::"dllrwzhequoh",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"xssayeebuwhq",
  resource == Resource::"atwmtdanenfv"
) when {
  true
};forbid(
  principal == Principal::"aagogabfkmox",
  action == Action::"jadypypnxafk",
  resource
) when {
  true
};permit(
  principal == Principal::"zyvbbulhwnwn",
  action == Action::"dllrwzhequoh",
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal,
  action == Action::"rfkjqajrgbyl",
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};forbid(
  principal,
  action == Action::"vkvrohivjxad",
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};forbid(
  principal == Principal::"xpkryiciwzgf",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};permit(
  principal,
  action == Action::"fublzswlrebp",
  resource == Resource::"brucmhxiqwil"
) when {
  true
};permit(
  principal == Principal::"dnfnsnbevosf",
  action == Action::"rhdwcsgghxwf",
  resource == Resource::"htdpuvkrildr"
) when {
  true
};forbid(
  principal,
  action == Action::"rfkjqajrgbyl",
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};forbid(
  principal == Principal::"ekqfgrkxyiid",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"xssayeebuwhq",
  resource
) when {
  true
};forbid(
  principal == Principal::"uhikvtbavylh",
  action,
  resource == Resource::"wguuxqugfrql"
) when {
  true
};forbid(
  principal == Principal::"qgnairntuguo",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"uymaurgpenxx"
) when {
  true
};permit(
  principal == Principal::"uhikvtbavylh",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"uhikvtbavylh",
  action == Action::"syjregyoqldd",
  resource == Resource::"smbssuhglplo"
) when {
  true
};permit(
  principal == Principal::"wnkxwledpjjl",
  action,
  resource == Resource::"klsqkshymqpk"
) when {
  true
};forbid(
  principal,
  action == Action::"dllrwzhequoh",
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};permit(
  principal,
  action == Action::"jedunopwhdab",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"gncgyolgqhrr"
) when {
  true
};forbid(
  principal,
  action == Action::"cttpxcwfboar",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};permit(
  principal == Principal::"seofhjtqtpdg",
  action == Action::"gpwlgdwrkauq",
  resource
) when {
  true
};forbid(
  principal == Principal::"aagogabfkmox",
  action == Action::"axolfruiaiqx",
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};permit(
  principal == Principal::"bckfogukcrqc",
  action,
  resource == Resource::"hwatqlfsxohl"
) when {
  true
};permit(
  principal == Principal::"euczuvcrhnyw",
  action == Action::"zpdplhiwhfxe",
  resource == Resource::"uymaurgpenxx"
) when {
  true
};permit(
  principal == Principal::"yfmfmxoxfosd",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"ekqfgrkxyiid",
  action == Action::"xssayeebuwhq",
  resource
) when {
  true
};permit(
  principal == Principal::"aagogabfkmox",
  action,
  resource == Resource::"gjneumgbuhpb"
) when {
  true
};forbid(
  principal,
  action == Action::"zlsludhalojy",
  resource
) when {
  true
};permit(
  principal == Principal::"ekqfgrkxyiid",
  action == Action::"vyiqkkikgpmn",
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};permit(
  principal == Principal::"vkktinyvlpgi",
  action,
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};forbid(
  principal == Principal::"thgthwrcyish",
  action,
  resource == Resource::"gncgyolgqhrr"
) when {
  true
};forbid(
  principal,
  action == Action::"qsphwjsrislv",
  resource
) when {
  true
};forbid(
  principal == Principal::"odofubfypovp",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"klsqkshymqpk"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"atwmtdanenfv"
) when {
  true
};permit(
  principal == Principal::"yfmfmxoxfosd",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"ayeusmztlcni",
  resource == Resource::"khdukfbxllxw"
) when {
  true
};forbid(
  principal == Principal::"lbkmtgndiegs",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"uhikvtbavylh",
  action,
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};forbid(
  principal,
  action == Action::"wtgwbalgzsgr",
  resource
) when {
  true
};forbid(
  principal == Principal::"wnkxwledpjjl",
  action == Action::"jmgzsezvduzf",
  resource
) when {
  true
};forbid(
  principal == Principal::"fkwlplfdaijq",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"syppxromuyqb",
  action == Action::"ayeusmztlcni",
  resource == Resource::"uymaurgpenxx"
) when {
  true
};permit(
  principal == Principal::"yfmfmxoxfosd",
  action,
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};forbid(
  principal == Principal::"syppxromuyqb",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"fohhrlglkjwz",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"gncgyolgqhrr"
) when {
  true
};permit(
  principal == Principal::"pagxgdwtmtqv",
  action == Action::"dwfrhuszemyk",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"cttpxcwfboar",
  resource == Resource::"mdocnzuopjvx"
) when {
  true
};permit(
  principal == Principal::"bckfogukcrqc",
  action == Action::"jedunopwhdab",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"jowejrciproe",
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};permit(
  principal,
  action == Action::"utjqmbyirkiy",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};permit(
  principal,
  action == Action::"zlsludhalojy",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"khdukfbxllxw"
) when {
  true
};forbid(
  principal == Principal::"rcptcuvbzswx",
  action,
  resource == Resource::"mbtgbwiwjoiy"
) when {
  true
};permit(
  principal == Principal::"cehgsohadlet",
  action == Action::"hajgxmbrysdv",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal == Principal::"xpkryiciwzgf",
  action,
  resource == Resource::"klqpkwgrazag"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};forbid(
  principal == Principal::"qgnairntuguo",
  action,
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};forbid(
  principal == Principal::"seofhjtqtpdg",
  action == Action::"hcltmblyzyxf",
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};forbid(
  principal == Principal::"aagogabfkmox",
  action == Action::"utjqmbyirkiy",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};forbid(
  principal == Principal::"wwkvlqcrjgyy",
  action == Action::"famgyptaffdm",
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};forbid(
  principal == Principal::"fohhrlglkjwz",
  action == Action::"axolfruiaiqx",
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};permit(
  principal == Principal::"thgthwrcyish",
  action == Action::"cttpxcwfboar",
  resource == Resource::"klqpkwgrazag"
) when {
  true
};permit(
  principal == Principal::"pagxgdwtmtqv",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"pagxgdwtmtqv",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"dllrwzhequoh",
  resource
) when {
  true
};permit(
  principal == Principal::"wnkxwledpjjl",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"ayeusmztlcni",
  resource
) when {
  true
};permit(
  principal == Principal::"rcptcuvbzswx",
  action,
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};forbid(
  principal,
  action == Action::"hjpqojifapdt",
  resource == Resource::"fbredeszwrzn"
) when {
  true
};permit(
  principal,
  action == Action::"wtgwbalgzsgr",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"syjregyoqldd",
  resource
) when {
  true
};forbid(
  principal == Principal::"wwkvlqcrjgyy",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"fykhjpzumdaa",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"hjpqojifapdt",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"fbredeszwrzn"
) when {
  true
};forbid(
  principal == Principal::"ulfsjgvyislm",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"zyvbbulhwnwn",
  action == Action::"jowejrciproe",
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};forbid(
  principal == Principal::"thgthwrcyish",
  action,
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};permit(
  principal == Principal::"kouqxvovaxiz",
  action == Action::"zpdplhiwhfxe",
  resource == Resource::"klsqkshymqpk"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};permit(
  principal == Principal::"euczuvcrhnyw",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"nzkbqfcwhofn",
  resource
) when {
  true
};permit(
  principal == Principal::"xqifgqptbljq",
  action,
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};forbid(
  principal,
  action == Action::"famgyptaffdm",
  resource == Resource::"atwmtdanenfv"
) when {
  true
};permit(
  principal == Principal::"iuwfronkotry",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"ycxzoipplruh",
  action == Action::"zpdplhiwhfxe",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};forbid(
  principal == Principal::"vkktinyvlpgi",
  action == Action::"nzkbqfcwhofn",
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal == Principal::"uhikvtbavylh",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"kouqxvovaxiz",
  action == Action::"rhdwcsgghxwf",
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal == Principal::"seofhjtqtpdg",
  action == Action::"syjregyoqldd",
  resource == Resource::"khdukfbxllxw"
) when {
  true
};forbid(
  principal,
  action == Action::"hcltmblyzyxf",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"klqpkwgrazag"
) when {
  true
};forbid(
  principal == Principal::"fykhjpzumdaa",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"bckfogukcrqc",
  action == Action::"vkvrohivjxad",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"atwmtdanenfv"
) when {
  true
};permit(
  principal == Principal::"iuwfronkotry",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"ekqfgrkxyiid",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"euczuvcrhnyw",
  action,
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};permit(
  principal,
  action == Action::"xssayeebuwhq",
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal,
  action == Action::"hcltmblyzyxf",
  resource
) when {
  true
};permit(
  principal == Principal::"hcpkmvhfiymn",
  action == Action::"nzkbqfcwhofn",
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};forbid(
  principal,
  action == Action::"jadypypnxafk",
  resource
) when {
  true
};forbid(
  principal == Principal::"yfmfmxoxfosd",
  action,
  resource == Resource::"khdukfbxllxw"
) when {
  true
};forbid(
  principal == Principal::"uhikvtbavylh",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"fkwlplfdaijq",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"syppxromuyqb",
  action,
  resource == Resource::"amemmojhemhz"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"smbssuhglplo"
) when {
  true
};forbid(
  principal == Principal::"fohhrlglkjwz",
  action == Action::"hcltmblyzyxf",
  resource
) when {
  true
};forbid(
  principal == Principal::"vkktinyvlpgi",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"oyjsvzvxiikm",
  resource
) when {
  true
};permit(
  principal == Principal::"lbkmtgndiegs",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"jowejrciproe",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"rhdwcsgghxwf",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"xssayeebuwhq",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"ayeusmztlcni",
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};forbid(
  principal == Principal::"qgnairntuguo",
  action,
  resource == Resource::"amemmojhemhz"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"ojegmylgdzap"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};forbid(
  principal == Principal::"dnfnsnbevosf",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"cehgsohadlet",
  action == Action::"utjqmbyirkiy",
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};forbid(
  principal,
  action == Action::"jmgzsezvduzf",
  resource
) when {
  true
};forbid(
  principal == Principal::"pagxgdwtmtqv",
  action == Action::"rhdwcsgghxwf",
  resource
) when {
  true
};forbid(
  principal == Principal::"pagxgdwtmtqv",
  action == Action::"vyiqkkikgpmn",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"mdocnzuopjvx"
) when {
  true
};permit(
  principal == Principal::"ycxzoipplruh",
  action == Action::"cttpxcwfboar",
  resource == Resource::"tdhcfedimojq"
) when {
  true
};forbid(
  principal == Principal::"xpkryiciwzgf",
  action == Action::"syjregyoqldd",
  resource
) when {
  true
};permit(
  principal == Principal::"xpkryiciwzgf",
  action == Action::"famgyptaffdm",
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"uymaurgpenxx"
) when {
  true
};forbid(
  principal == Principal::"kouqxvovaxiz",
  action,
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};permit(
  principal == Principal::"hcpkmvhfiymn",
  action,
  resource == Resource::"smbssuhglplo"
) when {
  true
};forbid(
  principal,
  action == Action::"rhdwcsgghxwf",
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};permit(
  principal == Principal::"qgnairntuguo",
  action,
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};forbid(
  principal,
  action == Action::"jadypypnxafk",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"xssayeebuwhq",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"syjregyoqldd",
  resource == Resource::"fbredeszwrzn"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"ojegmylgdzap"
) when {
  true
};permit(
  principal,
  action == Action::"rhdwcsgghxwf",
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};permit(
  principal == Principal::"bckfogukcrqc",
  action == Action::"axolfruiaiqx",
  resource == Resource::"hwatqlfsxohl"
) when {
  true
};forbid(
  principal,
  action == Action::"syjregyoqldd",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"tdhcfedimojq"
) when {
  true
};forbid(
  principal == Principal::"bckfogukcrqc",
  action,
  resource == Resource::"smbssuhglplo"
) when {
  true
};forbid(
  principal == Principal::"lbkmtgndiegs",
  action == Action::"zpdplhiwhfxe",
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"mbtgbwiwjoiy"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"wguuxqugfrql"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"gncgyolgqhrr"
) when {
  true
};permit(
  principal == Principal::"bckfogukcrqc",
  action == Action::"syjregyoqldd",
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"klsqkshymqpk"
) when {
  true
};forbid(
  principal == Principal::"fohhrlglkjwz",
  action == Action::"rhdwcsgghxwf",
  resource
) when {
  true
};permit(
  principal == Principal::"pagxgdwtmtqv",
  action,
  resource == Resource::"pxbjcjbxjwjp"
) when {
  true
};forbid(
  principal == Principal::"fkwlplfdaijq",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"zyvbbulhwnwn",
  action == Action::"vkvrohivjxad",
  resource
) when {
  true
};permit(
  principal == Principal::"fykhjpzumdaa",
  action,
  resource == Resource::"ojegmylgdzap"
) when {
  true
};permit(
  principal,
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};permit(
  principal == Principal::"kouqxvovaxiz",
  action == Action::"xssayeebuwhq",
  resource
) when {
  true
};forbid(
  principal == Principal::"pagxgdwtmtqv",
  action,
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};forbid(
  principal == Principal::"bckfogukcrqc",
  action == Action::"qsphwjsrislv",
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};permit(
  principal,
  action == Action::"jedunopwhdab",
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};forbid(
  principal == Principal::"krpqlztqpgsk",
  action,
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};permit(
  principal == Principal::"aagogabfkmox",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"nzkbqfcwhofn",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"gjneumgbuhpb"
) when {
  true
};permit(
  principal,
  action == Action::"veyzqxfgmvow",
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};forbid(
  principal == Principal::"pagxgdwtmtqv",
  action,
  resource == Resource::"lputleedekcx"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"mbtgbwiwjoiy"
) when {
  true
};permit(
  principal == Principal::"wwkvlqcrjgyy",
  action,
  resource == Resource::"hwatqlfsxohl"
) when {
  true
};permit(
  principal,
  action == Action::"axolfruiaiqx",
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};forbid(
  principal == Principal::"cehgsohadlet",
  action,
  resource == Resource::"brucmhxiqwil"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"lputleedekcx"
) when {
  true
};permit(
  principal == Principal::"yfmfmxoxfosd",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"zyvbbulhwnwn",
  action,
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"pxbjcjbxjwjp"
) when {
  true
};permit(
  principal,
  action == Action::"syjregyoqldd",
  resource
) when {
  true
};forbid(
  principal == Principal::"imvcevihxbhs",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"kouqxvovaxiz",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"syppxromuyqb",
  action == Action::"jadypypnxafk",
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};forbid(
  principal == Principal::"uhikvtbavylh",
  action == Action::"utjqmbyirkiy",
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"klqpkwgrazag"
) when {
  true
};forbid(
  principal,
  action == Action::"jadypypnxafk",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"nzkbqfcwhofn",
  resource == Resource::"wguuxqugfrql"
) when {
  true
};forbid(
  principal == Principal::"cehgsohadlet",
  action == Action::"gpwlgdwrkauq",
  resource
) when {
  true
};forbid(
  principal == Principal::"qgnairntuguo",
  action == Action::"ayeusmztlcni",
  resource == Resource::"fbredeszwrzn"
) when {
  true
};forbid(
  principal == Principal::"ekqfgrkxyiid",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"xpkryiciwzgf",
  action == Action::"vczrnqvzhuul",
  resource == Resource::"uymaurgpenxx"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};forbid(
  principal == Principal::"kouqxvovaxiz",
  action == Action::"gpwlgdwrkauq",
  resource
) when {
  true
};permit(
  principal == Principal::"rcptcuvbzswx",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"uymaurgpenxx"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"klsqkshymqpk"
) when {
  true
};forbid(
  principal == Principal::"fohhrlglkjwz",
  action == Action::"hcltmblyzyxf",
  resource
) when {
  true
};permit(
  principal == Principal::"uhikvtbavylh",
  action == Action::"hjpqojifapdt",
  resource == Resource::"fbredeszwrzn"
) when {
  true
};forbid(
  principal == Principal::"fohhrlglkjwz",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"jowejrciproe",
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};permit(
  principal == Principal::"wwkvlqcrjgyy",
  action,
  resource == Resource::"tdhcfedimojq"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"lputleedekcx"
) when {
  true
};forbid(
  principal == Principal::"fkwlplfdaijq",
  action,
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};permit(
  principal == Principal::"fkwlplfdaijq",
  action,
  resource == Resource::"gjneumgbuhpb"
) when {
  true
};forbid(
  principal == Principal::"fykhjpzumdaa",
  action == Action::"hjpqojifapdt",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"hcltmblyzyxf",
  resource
) when {
  true
};permit(
  principal == Principal::"lbkmtgndiegs",
  action == Action::"oyjsvzvxiikm",
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};forbid(
  principal,
  action == Action::"nzkbqfcwhofn",
  resource
) when {
  true
};permit(
  principal == Principal::"wnkxwledpjjl",
  action == Action::"oyjsvzvxiikm",
  resource
) when {
  true
};permit(
  principal == Principal::"uhikvtbavylh",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"xpkryiciwzgf",
  action,
  resource == Resource::"mbtgbwiwjoiy"
) when {
  true
};forbid(
  principal == Principal::"odofubfypovp",
  action == Action::"cttpxcwfboar",
  resource == Resource::"khdukfbxllxw"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal,
  action == Action::"veyzqxfgmvow",
  resource == Resource::"hwatqlfsxohl"
) when {
  true
};permit(
  principal == Principal::"dnfnsnbevosf",
  action,
  resource == Resource::"smbssuhglplo"
) when {
  true
};forbid(
  principal == Principal::"cehgsohadlet",
  action,
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};forbid(
  principal,
  action == Action::"wtgwbalgzsgr",
  resource
) when {
  true
};forbid(
  principal == Principal::"iuwfronkotry",
  action == Action::"jowejrciproe",
  resource
) when {
  true
};forbid(
  principal == Principal::"cehgsohadlet",
  action == Action::"wtgwbalgzsgr",
  resource
) when {
  true
};permit(
  principal == Principal::"yfmfmxoxfosd",
  action,
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};forbid(
  principal,
  action == Action::"xssayeebuwhq",
  resource == Resource::"tdhcfedimojq"
) when {
  true
};permit(
  principal,
  action == Action::"cttpxcwfboar",
  resource
) when {
  true
};permit(
  principal == Principal::"xqifgqptbljq",
  action,
  resource == Resource::"gncgyolgqhrr"
) when {
  true
};forbid(
  principal == Principal::"imvcevihxbhs",
  action == Action::"jmgzsezvduzf",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"famgyptaffdm",
  resource
) when {
  true
};permit(
  principal == Principal::"syppxromuyqb",
  action,
  resource == Resource::"fbredeszwrzn"
) when {
  true
};permit(
  principal == Principal::"ulfsjgvyislm",
  action == Action::"hajgxmbrysdv",
  resource == Resource::"htdpuvkrildr"
) when {
  true
};forbid(
  principal == Principal::"euczuvcrhnyw",
  action == Action::"nzkbqfcwhofn",
  resource == Resource::"klsqkshymqpk"
) when {
  true
};forbid(
  principal,
  action == Action::"gpwlgdwrkauq",
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"smbssuhglplo"
) when {
  true
};forbid(
  principal,
  action == Action::"nzkbqfcwhofn",
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};permit(
  principal,
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"vczrnqvzhuul",
  resource
) when {
  true
};forbid(
  principal == Principal::"hcpkmvhfiymn",
  action,
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};forbid(
  principal == Principal::"kouqxvovaxiz",
  action == Action::"zpdplhiwhfxe",
  resource
) when {
  true
};forbid(
  principal == Principal::"fykhjpzumdaa",
  action,
  resource == Resource::"ojegmylgdzap"
) when {
  true
};forbid(
  principal,
  action == Action::"veyzqxfgmvow",
  resource == Resource::"wguuxqugfrql"
) when {
  true
};forbid(
  principal == Principal::"cehgsohadlet",
  action == Action::"qsphwjsrislv",
  resource
) when {
  true
};permit(
  principal == Principal::"iuwfronkotry",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"ekqfgrkxyiid",
  action,
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};forbid(
  principal == Principal::"zyvbbulhwnwn",
  action,
  resource == Resource::"lputleedekcx"
) when {
  true
};permit(
  principal,
  action == Action::"vyiqkkikgpmn",
  resource == Resource::"htdpuvkrildr"
) when {
  true
};forbid(
  principal == Principal::"pagxgdwtmtqv",
  action == Action::"wtgwbalgzsgr",
  resource == Resource::"tdhcfedimojq"
) when {
  true
};permit(
  principal,
  action == Action::"qsphwjsrislv",
  resource
) when {
  true
};permit(
  principal == Principal::"odofubfypovp",
  action == Action::"rfkjqajrgbyl",
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};forbid(
  principal,
  action == Action::"xssayeebuwhq",
  resource == Resource::"smbssuhglplo"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"hwatqlfsxohl"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"wguuxqugfrql"
) when {
  true
};forbid(
  principal,
  action == Action::"utjqmbyirkiy",
  resource == Resource::"brucmhxiqwil"
) when {
  true
};forbid(
  principal,
  action == Action::"syjregyoqldd",
  resource
) when {
  true
};permit(
  principal == Principal::"odofubfypovp",
  action == Action::"zpdplhiwhfxe",
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};permit(
  principal,
  action == Action::"oyjsvzvxiikm",
  resource == Resource::"amemmojhemhz"
) when {
  true
};permit(
  principal == Principal::"odofubfypovp",
  action == Action::"gpwlgdwrkauq",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"nzkbqfcwhofn",
  resource == Resource::"wguuxqugfrql"
) when {
  true
};permit(
  principal == Principal::"ycxzoipplruh",
  action == Action::"rpubpuedyiug",
  resource == Resource::"brucmhxiqwil"
) when {
  true
};forbid(
  principal == Principal::"bckfogukcrqc",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"iuwfronkotry",
  action == Action::"famgyptaffdm",
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};permit(
  principal,
  action == Action::"nzkbqfcwhofn",
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};permit(
  principal,
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};forbid(
  principal == Principal::"wnkxwledpjjl",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"pagxgdwtmtqv",
  action == Action::"ayeusmztlcni",
  resource == Resource::"uymaurgpenxx"
) when {
  true
};permit(
  principal == Principal::"fohhrlglkjwz",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"fkwlplfdaijq",
  action,
  resource == Resource::"klsqkshymqpk"
) when {
  true
};permit(
  principal == Principal::"cehgsohadlet",
  action == Action::"qsphwjsrislv",
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"pxbjcjbxjwjp"
) when {
  true
};forbid(
  principal == Principal::"wnkxwledpjjl",
  action == Action::"cttpxcwfboar",
  resource == Resource::"tdhcfedimojq"
) when {
  true
};forbid(
  principal == Principal::"wnkxwledpjjl",
  action == Action::"vczrnqvzhuul",
  resource == Resource::"gjneumgbuhpb"
) when {
  true
};permit(
  principal == Principal::"xpkryiciwzgf",
  action,
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};forbid(
  principal == Principal::"lbkmtgndiegs",
  action,
  resource == Resource::"klsqkshymqpk"
) when {
  true
};forbid(
  principal == Principal::"rcptcuvbzswx",
  action == Action::"axolfruiaiqx",
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};permit(
  principal == Principal::"dnfnsnbevosf",
  action,
  resource == Resource::"lputleedekcx"
) when {
  true
};forbid(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"jowejrciproe",
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};forbid(
  principal == Principal::"syppxromuyqb",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"mbtgbwiwjoiy"
) when {
  true
};forbid(
  principal == Principal::"fykhjpzumdaa",
  action == Action::"vyiqkkikgpmn",
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"lputleedekcx"
) when {
  true
};forbid(
  principal == Principal::"cehgsohadlet",
  action == Action::"jmgzsezvduzf",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"rpubpuedyiug",
  resource == Resource::"htdpuvkrildr"
) when {
  true
};permit(
  principal == Principal::"ekqfgrkxyiid",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"odofubfypovp",
  action,
  resource == Resource::"htdpuvkrildr"
) when {
  true
};permit(
  principal,
  action == Action::"nzkbqfcwhofn",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"jedunopwhdab",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"atwmtdanenfv"
) when {
  true
};permit(
  principal == Principal::"qgnairntuguo",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"syppxromuyqb",
  action == Action::"famgyptaffdm",
  resource == Resource::"amemmojhemhz"
) when {
  true
};forbid(
  principal == Principal::"odofubfypovp",
  action == Action::"rfkjqajrgbyl",
  resource
) when {
  true
};forbid(
  principal == Principal::"pagxgdwtmtqv",
  action == Action::"rhdwcsgghxwf",
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};permit(
  principal,
  action == Action::"utjqmbyirkiy",
  resource == Resource::"uymaurgpenxx"
) when {
  true
};permit(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"fublzswlrebp",
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};permit(
  principal == Principal::"euczuvcrhnyw",
  action == Action::"gpwlgdwrkauq",
  resource
) when {
  true
};forbid(
  principal == Principal::"seofhjtqtpdg",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};permit(
  principal,
  action == Action::"jadypypnxafk",
  resource == Resource::"klsqkshymqpk"
) when {
  true
};forbid(
  principal,
  action == Action::"syjregyoqldd",
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"htdpuvkrildr"
) when {
  true
};forbid(
  principal == Principal::"ycxzoipplruh",
  action,
  resource == Resource::"htdpuvkrildr"
) when {
  true
};forbid(
  principal == Principal::"xpkryiciwzgf",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"cehgsohadlet",
  action,
  resource == Resource::"atwmtdanenfv"
) when {
  true
};permit(
  principal,
  action == Action::"zlsludhalojy",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"axolfruiaiqx",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"xssayeebuwhq",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"rfkjqajrgbyl",
  resource == Resource::"uymaurgpenxx"
) when {
  true
};permit(
  principal == Principal::"fohhrlglkjwz",
  action == Action::"dllrwzhequoh",
  resource == Resource::"khdukfbxllxw"
) when {
  true
};forbid(
  principal,
  action == Action::"famgyptaffdm",
  resource == Resource::"mdocnzuopjvx"
) when {
  true
};forbid(
  principal == Principal::"seofhjtqtpdg",
  action,
  resource == Resource::"gjneumgbuhpb"
) when {
  true
};forbid(
  principal == Principal::"fkwlplfdaijq",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"wnkxwledpjjl",
  action,
  resource == Resource::"klqpkwgrazag"
) when {
  true
};permit(
  principal,
  action == Action::"hajgxmbrysdv",
  resource
) when {
  true
};permit(
  principal == Principal::"dnfnsnbevosf",
  action,
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};permit(
  principal == Principal::"pagxgdwtmtqv",
  action == Action::"hcltmblyzyxf",
  resource == Resource::"lputleedekcx"
) when {
  true
};permit(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"dllrwzhequoh",
  resource
) when {
  true
};forbid(
  principal == Principal::"fkwlplfdaijq",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"fohhrlglkjwz",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"iuwfronkotry",
  action,
  resource == Resource::"tdhcfedimojq"
) when {
  true
};permit(
  principal == Principal::"euczuvcrhnyw",
  action == Action::"syjregyoqldd",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"vczrnqvzhuul",
  resource
) when {
  true
};permit(
  principal == Principal::"wwkvlqcrjgyy",
  action,
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};forbid(
  principal,
  action == Action::"jedunopwhdab",
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};permit(
  principal == Principal::"dnfnsnbevosf",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"kouqxvovaxiz",
  action == Action::"axolfruiaiqx",
  resource == Resource::"lputleedekcx"
) when {
  true
};permit(
  principal,
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};permit(
  principal == Principal::"fohhrlglkjwz",
  action == Action::"rpubpuedyiug",
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};forbid(
  principal == Principal::"zyvbbulhwnwn",
  action == Action::"wtgwbalgzsgr",
  resource
) when {
  true
};permit(
  principal == Principal::"fohhrlglkjwz",
  action == Action::"hajgxmbrysdv",
  resource
) when {
  true
};forbid(
  principal == Principal::"aagogabfkmox",
  action == Action::"utjqmbyirkiy",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};forbid(
  principal == Principal::"qgnairntuguo",
  action,
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};forbid(
  principal == Principal::"seofhjtqtpdg",
  action == Action::"jedunopwhdab",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"gpwlgdwrkauq",
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};forbid(
  principal == Principal::"ekqfgrkxyiid",
  action == Action::"uocqgzryuaak",
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};forbid(
  principal,
  action == Action::"hcltmblyzyxf",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"rfkjqajrgbyl",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"hcltmblyzyxf",
  resource == Resource::"atwmtdanenfv"
) when {
  true
};forbid(
  principal == Principal::"cehgsohadlet",
  action == Action::"vyiqkkikgpmn",
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};forbid(
  principal,
  action == Action::"zlsludhalojy",
  resource == Resource::"mdocnzuopjvx"
) when {
  true
};forbid(
  principal == Principal::"lbkmtgndiegs",
  action,
  resource == Resource::"amemmojhemhz"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"htdpuvkrildr"
) when {
  true
};permit(
  principal,
  action == Action::"cttpxcwfboar",
  resource == Resource::"brucmhxiqwil"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"fbredeszwrzn"
) when {
  true
};forbid(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"hjpqojifapdt",
  resource == Resource::"ojegmylgdzap"
) when {
  true
};forbid(
  principal == Principal::"fohhrlglkjwz",
  action == Action::"zpdplhiwhfxe",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"jowejrciproe",
  resource == Resource::"ojegmylgdzap"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};forbid(
  principal,
  action == Action::"rpubpuedyiug",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"cttpxcwfboar",
  resource == Resource::"gjneumgbuhpb"
) when {
  true
};permit(
  principal,
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};forbid(
  principal == Principal::"qgnairntuguo",
  action == Action::"vyiqkkikgpmn",
  resource
) when {
  true
};permit(
  principal == Principal::"zyvbbulhwnwn",
  action,
  resource == Resource::"smbssuhglplo"
) when {
  true
};forbid(
  principal,
  action == Action::"gpwlgdwrkauq",
  resource
) when {
  true
};forbid(
  principal == Principal::"bckfogukcrqc",
  action == Action::"jowejrciproe",
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"wguuxqugfrql"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};forbid(
  principal == Principal::"fohhrlglkjwz",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"yfmfmxoxfosd",
  action == Action::"hcltmblyzyxf",
  resource == Resource::"ojegmylgdzap"
) when {
  true
};permit(
  principal,
  action == Action::"dwfrhuszemyk",
  resource == Resource::"htdpuvkrildr"
) when {
  true
};permit(
  principal == Principal::"xpkryiciwzgf",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"xpkryiciwzgf",
  action == Action::"vkvrohivjxad",
  resource == Resource::"wguuxqugfrql"
) when {
  true
};forbid(
  principal,
  action == Action::"axolfruiaiqx",
  resource
) when {
  true
};forbid(
  principal == Principal::"ekqfgrkxyiid",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};forbid(
  principal,
  action == Action::"jedunopwhdab",
  resource == Resource::"amemmojhemhz"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};permit(
  principal == Principal::"imvcevihxbhs",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal,
  action == Action::"vczrnqvzhuul",
  resource == Resource::"mbtgbwiwjoiy"
) when {
  true
};forbid(
  principal,
  action == Action::"vyiqkkikgpmn",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"oyjsvzvxiikm",
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};forbid(
  principal,
  action == Action::"vczrnqvzhuul",
  resource
) when {
  true
};permit(
  principal == Principal::"dnfnsnbevosf",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"ycxzoipplruh",
  action,
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};permit(
  principal == Principal::"thgthwrcyish",
  action,
  resource == Resource::"lputleedekcx"
) when {
  true
};forbid(
  principal,
  action == Action::"dwfrhuszemyk",
  resource
) when {
  true
};forbid(
  principal == Principal::"xpkryiciwzgf",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"jmgzsezvduzf",
  resource
) when {
  true
};permit(
  principal == Principal::"ulfsjgvyislm",
  action,
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};forbid(
  principal == Principal::"ycxzoipplruh",
  action == Action::"axolfruiaiqx",
  resource == Resource::"pxbjcjbxjwjp"
) when {
  true
};permit(
  principal == Principal::"xqifgqptbljq",
  action == Action::"nzkbqfcwhofn",
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};permit(
  principal,
  action == Action::"oyjsvzvxiikm",
  resource
) when {
  true
};permit(
  principal == Principal::"ekqfgrkxyiid",
  action,
  resource == Resource::"pxbjcjbxjwjp"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"uymaurgpenxx"
) when {
  true
};forbid(
  principal == Principal::"imvcevihxbhs",
  action,
  resource == Resource::"brucmhxiqwil"
) when {
  true
};forbid(
  principal,
  action == Action::"nzkbqfcwhofn",
  resource == Resource::"tdhcfedimojq"
) when {
  true
};forbid(
  principal,
  action == Action::"vkvrohivjxad",
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};forbid(
  principal,
  action == Action::"ayeusmztlcni",
  resource
) when {
  true
};forbid(
  principal == Principal::"cehgsohadlet",
  action == Action::"hcltmblyzyxf",
  resource
) when {
  true
};permit(
  principal == Principal::"zyvbbulhwnwn",
  action == Action::"hajgxmbrysdv",
  resource == Resource::"klqpkwgrazag"
) when {
  true
};permit(
  principal == Principal::"ycxzoipplruh",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"jedunopwhdab",
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};forbid(
  principal == Principal::"syppxromuyqb",
  action == Action::"vczrnqvzhuul",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"rfkjqajrgbyl",
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};permit(
  principal,
  action == Action::"rfkjqajrgbyl",
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};forbid(
  principal,
  action == Action::"fublzswlrebp",
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal == Principal::"aagogabfkmox",
  action == Action::"xssayeebuwhq",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"fublzswlrebp",
  resource
) when {
  true
};forbid(
  principal == Principal::"vkktinyvlpgi",
  action,
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"ojegmylgdzap"
) when {
  true
};forbid(
  principal,
  action == Action::"axolfruiaiqx",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"rhdwcsgghxwf",
  resource
) when {
  true
};permit(
  principal == Principal::"imvcevihxbhs",
  action,
  resource == Resource::"mbtgbwiwjoiy"
) when {
  true
};forbid(
  principal == Principal::"lbkmtgndiegs",
  action == Action::"rhdwcsgghxwf",
  resource == Resource::"brucmhxiqwil"
) when {
  true
};forbid(
  principal == Principal::"fohhrlglkjwz",
  action == Action::"vyiqkkikgpmn",
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};permit(
  principal,
  action == Action::"utjqmbyirkiy",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"uocqgzryuaak",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"fublzswlrebp",
  resource
) when {
  true
};forbid(
  principal == Principal::"wnkxwledpjjl",
  action == Action::"zlsludhalojy",
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};forbid(
  principal,
  action == Action::"fublzswlrebp",
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};forbid(
  principal,
  action == Action::"hcltmblyzyxf",
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};permit(
  principal == Principal::"ulfsjgvyislm",
  action,
  resource == Resource::"brucmhxiqwil"
) when {
  true
};permit(
  principal == Principal::"xpkryiciwzgf",
  action == Action::"rpubpuedyiug",
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};permit(
  principal == Principal::"aagogabfkmox",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"ycxzoipplruh",
  action,
  resource == Resource::"tdhcfedimojq"
) when {
  true
};permit(
  principal,
  action == Action::"oyjsvzvxiikm",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};permit(
  principal,
  action == Action::"nzkbqfcwhofn",
  resource
) when {
  true
};forbid(
  principal == Principal::"odofubfypovp",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"odofubfypovp",
  action,
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};forbid(
  principal,
  action == Action::"jmgzsezvduzf",
  resource
) when {
  true
};forbid(
  principal == Principal::"wwkvlqcrjgyy",
  action == Action::"rpubpuedyiug",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"hcltmblyzyxf",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"hajgxmbrysdv",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"uocqgzryuaak",
  resource == Resource::"htdpuvkrildr"
) when {
  true
};permit(
  principal == Principal::"thgthwrcyish",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"rcptcuvbzswx",
  action == Action::"oyjsvzvxiikm",
  resource == Resource::"gjneumgbuhpb"
) when {
  true
};permit(
  principal,
  action == Action::"cttpxcwfboar",
  resource
) when {
  true
};permit(
  principal == Principal::"xqifgqptbljq",
  action == Action::"vkvrohivjxad",
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};forbid(
  principal == Principal::"ekqfgrkxyiid",
  action == Action::"oyjsvzvxiikm",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"gncgyolgqhrr"
) when {
  true
};permit(
  principal,
  action == Action::"dwfrhuszemyk",
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};permit(
  principal == Principal::"wwkvlqcrjgyy",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"uocqgzryuaak",
  resource
) when {
  true
};forbid(
  principal == Principal::"fykhjpzumdaa",
  action,
  resource == Resource::"amemmojhemhz"
) when {
  true
};forbid(
  principal == Principal::"bckfogukcrqc",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"bckfogukcrqc",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"uhikvtbavylh",
  action == Action::"syjregyoqldd",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"jmgzsezvduzf",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"zpdplhiwhfxe",
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};forbid(
  principal == Principal::"zyvbbulhwnwn",
  action,
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};permit(
  principal,
  action == Action::"vkvrohivjxad",
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};forbid(
  principal,
  action == Action::"rpubpuedyiug",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"qsphwjsrislv",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"uocqgzryuaak",
  resource == Resource::"mdocnzuopjvx"
) when {
  true
};permit(
  principal == Principal::"wwkvlqcrjgyy",
  action,
  resource == Resource::"fbredeszwrzn"
) when {
  true
};permit(
  principal == Principal::"seofhjtqtpdg",
  action == Action::"jowejrciproe",
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};forbid(
  principal == Principal::"ulfsjgvyislm",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"bckfogukcrqc",
  action == Action::"syjregyoqldd",
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};forbid(
  principal,
  action == Action::"wtgwbalgzsgr",
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};permit(
  principal,
  action == Action::"utjqmbyirkiy",
  resource == Resource::"uymaurgpenxx"
) when {
  true
};permit(
  principal == Principal::"euczuvcrhnyw",
  action == Action::"axolfruiaiqx",
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};forbid(
  principal == Principal::"iuwfronkotry",
  action,
  resource == Resource::"wguuxqugfrql"
) when {
  true
};permit(
  principal == Principal::"pagxgdwtmtqv",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"klsqkshymqpk"
) when {
  true
};forbid(
  principal == Principal::"fykhjpzumdaa",
  action,
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};permit(
  principal,
  action == Action::"fublzswlrebp",
  resource == Resource::"wguuxqugfrql"
) when {
  true
};permit(
  principal == Principal::"ulfsjgvyislm",
  action == Action::"oyjsvzvxiikm",
  resource
) when {
  true
};forbid(
  principal == Principal::"odofubfypovp",
  action,
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal == Principal::"cehgsohadlet",
  action,
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};permit(
  principal == Principal::"xqifgqptbljq",
  action == Action::"zlsludhalojy",
  resource == Resource::"uymaurgpenxx"
) when {
  true
};permit(
  principal == Principal::"syppxromuyqb",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"vkktinyvlpgi",
  action == Action::"dwfrhuszemyk",
  resource
) when {
  true
};forbid(
  principal == Principal::"dnfnsnbevosf",
  action == Action::"axolfruiaiqx",
  resource
) when {
  true
};forbid(
  principal == Principal::"fkwlplfdaijq",
  action,
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};permit(
  principal == Principal::"aagogabfkmox",
  action == Action::"axolfruiaiqx",
  resource == Resource::"amemmojhemhz"
) when {
  true
};permit(
  principal == Principal::"rcptcuvbzswx",
  action,
  resource == Resource::"gncgyolgqhrr"
) when {
  true
};permit(
  principal == Principal::"wnkxwledpjjl",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"zpdplhiwhfxe",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"qsphwjsrislv",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"veyzqxfgmvow",
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};forbid(
  principal == Principal::"dnfnsnbevosf",
  action == Action::"zlsludhalojy",
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};forbid(
  principal,
  action == Action::"veyzqxfgmvow",
  resource == Resource::"fbredeszwrzn"
) when {
  true
};permit(
  principal == Principal::"rcptcuvbzswx",
  action == Action::"nzkbqfcwhofn",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"hjpqojifapdt",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"axolfruiaiqx",
  resource
) when {
  true
};forbid(
  principal == Principal::"rcptcuvbzswx",
  action,
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"pxbjcjbxjwjp"
) when {
  true
};forbid(
  principal == Principal::"euczuvcrhnyw",
  action,
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};forbid(
  principal,
  action == Action::"jowejrciproe",
  resource
) when {
  true
};forbid(
  principal == Principal::"vkktinyvlpgi",
  action,
  resource == Resource::"brucmhxiqwil"
) when {
  true
};forbid(
  principal,
  action == Action::"rhdwcsgghxwf",
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};forbid(
  principal == Principal::"qgnairntuguo",
  action == Action::"hjpqojifapdt",
  resource
) when {
  true
};forbid(
  principal == Principal::"ulfsjgvyislm",
  action == Action::"hajgxmbrysdv",
  resource == Resource::"brucmhxiqwil"
) when {
  true
};permit(
  principal == Principal::"qgnairntuguo",
  action == Action::"syjregyoqldd",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};forbid(
  principal == Principal::"thgthwrcyish",
  action,
  resource == Resource::"htdpuvkrildr"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"gjneumgbuhpb"
) when {
  true
};permit(
  principal == Principal::"rcptcuvbzswx",
  action,
  resource == Resource::"htdpuvkrildr"
) when {
  true
};permit(
  principal,
  action == Action::"fublzswlrebp",
  resource == Resource::"klsqkshymqpk"
) when {
  true
};forbid(
  principal == Principal::"hcpkmvhfiymn",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"euczuvcrhnyw",
  action == Action::"rpubpuedyiug",
  resource
) when {
  true
};permit(
  principal == Principal::"pagxgdwtmtqv",
  action,
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};forbid(
  principal,
  action == Action::"vkvrohivjxad",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"mdocnzuopjvx"
) when {
  true
};forbid(
  principal,
  action == Action::"oyjsvzvxiikm",
  resource == Resource::"amemmojhemhz"
) when {
  true
};forbid(
  principal == Principal::"wnkxwledpjjl",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"zlsludhalojy",
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};permit(
  principal == Principal::"xqifgqptbljq",
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};permit(
  principal == Principal::"fykhjpzumdaa",
  action,
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};forbid(
  principal == Principal::"ulfsjgvyislm",
  action == Action::"ayeusmztlcni",
  resource == Resource::"gjneumgbuhpb"
) when {
  true
};forbid(
  principal,
  action == Action::"vkvrohivjxad",
  resource
) when {
  true
};permit(
  principal == Principal::"dnfnsnbevosf",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"dnfnsnbevosf",
  action,
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};forbid(
  principal == Principal::"hcpkmvhfiymn",
  action == Action::"zlsludhalojy",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"gpwlgdwrkauq",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"syjregyoqldd",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"rfkjqajrgbyl",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"zlsludhalojy",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"famgyptaffdm",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"amemmojhemhz"
) when {
  true
};permit(
  principal,
  action == Action::"famgyptaffdm",
  resource == Resource::"ojegmylgdzap"
) when {
  true
};permit(
  principal == Principal::"fykhjpzumdaa",
  action == Action::"nzkbqfcwhofn",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"ayeusmztlcni",
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};forbid(
  principal == Principal::"fkwlplfdaijq",
  action == Action::"axolfruiaiqx",
  resource == Resource::"klqpkwgrazag"
) when {
  true
};permit(
  principal == Principal::"xpkryiciwzgf",
  action == Action::"syjregyoqldd",
  resource == Resource::"khdukfbxllxw"
) when {
  true
};permit(
  principal,
  action == Action::"utjqmbyirkiy",
  resource == Resource::"smbssuhglplo"
) when {
  true
};permit(
  principal == Principal::"qgnairntuguo",
  action,
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};forbid(
  principal,
  action == Action::"zlsludhalojy",
  resource
) when {
  true
};forbid(
  principal == Principal::"hcpkmvhfiymn",
  action == Action::"dwfrhuszemyk",
  resource == Resource::"pxbjcjbxjwjp"
) when {
  true
};permit(
  principal == Principal::"pagxgdwtmtqv",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"seofhjtqtpdg",
  action,
  resource == Resource::"fbredeszwrzn"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};permit(
  principal == Principal::"ycxzoipplruh",
  action == Action::"xssayeebuwhq",
  resource == Resource::"klqpkwgrazag"
) when {
  true
};permit(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"dllrwzhequoh",
  resource
) when {
  true
};permit(
  principal == Principal::"syppxromuyqb",
  action == Action::"jmgzsezvduzf",
  resource == Resource::"gncgyolgqhrr"
) when {
  true
};forbid(
  principal == Principal::"qgnairntuguo",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"ecaeaklnzgca"
) when {
  true
};permit(
  principal == Principal::"euczuvcrhnyw",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"rhdwcsgghxwf",
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};permit(
  principal == Principal::"odofubfypovp",
  action == Action::"gpwlgdwrkauq",
  resource
) when {
  true
};forbid(
  principal == Principal::"bckfogukcrqc",
  action == Action::"rfkjqajrgbyl",
  resource == Resource::"smbssuhglplo"
) when {
  true
};permit(
  principal == Principal::"ekqfgrkxyiid",
  action,
  resource == Resource::"smbssuhglplo"
) when {
  true
};permit(
  principal,
  action == Action::"dwfrhuszemyk",
  resource == Resource::"mdocnzuopjvx"
) when {
  true
};permit(
  principal == Principal::"xqifgqptbljq",
  action,
  resource == Resource::"gncgyolgqhrr"
) when {
  true
};forbid(
  principal == Principal::"wnkxwledpjjl",
  action,
  resource == Resource::"hwatqlfsxohl"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"yqtjozbtvufv"
) when {
  true
};forbid(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"jmgzsezvduzf",
  resource
) when {
  true
};permit(
  principal == Principal::"dnfnsnbevosf",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"wtgwbalgzsgr",
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};forbid(
  principal,
  action == Action::"dllrwzhequoh",
  resource
) when {
  true
};forbid(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"dllrwzhequoh",
  resource
) when {
  true
};permit(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"dllrwzhequoh",
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};permit(
  principal == Principal::"xpkryiciwzgf",
  action,
  resource == Resource::"gjneumgbuhpb"
) when {
  true
};permit(
  principal,
  action == Action::"vyiqkkikgpmn",
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};forbid(
  principal == Principal::"rcptcuvbzswx",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"ulfsjgvyislm",
  action == Action::"uocqgzryuaak",
  resource == Resource::"kyldadhdpfmg"
) when {
  true
};forbid(
  principal,
  action == Action::"ayeusmztlcni",
  resource
) when {
  true
};permit(
  principal == Principal::"imvcevihxbhs",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"ycxzoipplruh",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"hcpkmvhfiymn",
  action,
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};permit(
  principal == Principal::"wwkvlqcrjgyy",
  action,
  resource == Resource::"mdocnzuopjvx"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};permit(
  principal == Principal::"pagxgdwtmtqv",
  action == Action::"veyzqxfgmvow",
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};permit(
  principal == Principal::"lbkmtgndiegs",
  action == Action::"oyjsvzvxiikm",
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};forbid(
  principal,
  action == Action::"uocqgzryuaak",
  resource == Resource::"lputleedekcx"
) when {
  true
};permit(
  principal,
  action == Action::"syjregyoqldd",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"jadypypnxafk",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"xssayeebuwhq",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"brucmhxiqwil"
) when {
  true
};permit(
  principal,
  action == Action::"zlsludhalojy",
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"tdhcfedimojq"
) when {
  true
};permit(
  principal == Principal::"cehgsohadlet",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"ycxzoipplruh",
  action == Action::"xssayeebuwhq",
  resource == Resource::"fbredeszwrzn"
) when {
  true
};permit(
  principal,
  action == Action::"hjpqojifapdt",
  resource
) when {
  true
};forbid(
  principal == Principal::"lbkmtgndiegs",
  action == Action::"jadypypnxafk",
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};forbid(
  principal,
  action == Action::"vczrnqvzhuul",
  resource == Resource::"uymaurgpenxx"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"smbssuhglplo"
) when {
  true
};permit(
  principal,
  action == Action::"vczrnqvzhuul",
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"smbssuhglplo"
) when {
  true
};forbid(
  principal == Principal::"bckfogukcrqc",
  action,
  resource == Resource::"rqnltdgfjzob"
) when {
  true
};permit(
  principal == Principal::"xpkryiciwzgf",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};forbid(
  principal,
  action == Action::"dllrwzhequoh",
  resource
) when {
  true
};forbid(
  principal == Principal::"fykhjpzumdaa",
  action == Action::"zlsludhalojy",
  resource
) when {
  true
};permit(
  principal == Principal::"euczuvcrhnyw",
  action,
  resource == Resource::"hwatqlfsxohl"
) when {
  true
};forbid(
  principal == Principal::"hcpkmvhfiymn",
  action == Action::"uocqgzryuaak",
  resource == Resource::"ojegmylgdzap"
) when {
  true
};permit(
  principal == Principal::"hcpkmvhfiymn",
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"vkvrohivjxad",
  resource == Resource::"fbredeszwrzn"
) when {
  true
};forbid(
  principal == Principal::"imvcevihxbhs",
  action == Action::"rpubpuedyiug",
  resource
) when {
  true
};permit(
  principal == Principal::"aagogabfkmox",
  action == Action::"uocqgzryuaak",
  resource
) when {
  true
};permit(
  principal == Principal::"yfmfmxoxfosd",
  action == Action::"hajgxmbrysdv",
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};forbid(
  principal == Principal::"syppxromuyqb",
  action,
  resource == Resource::"smbssuhglplo"
) when {
  true
};forbid(
  principal == Principal::"fkwlplfdaijq",
  action,
  resource == Resource::"gncgyolgqhrr"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"smbssuhglplo"
) when {
  true
};forbid(
  principal,
  action == Action::"zpdplhiwhfxe",
  resource == Resource::"atwmtdanenfv"
) when {
  true
};permit(
  principal == Principal::"krpqlztqpgsk",
  action,
  resource == Resource::"klsqkshymqpk"
) when {
  true
};forbid(
  principal,
  action == Action::"ayeusmztlcni",
  resource == Resource::"mbtgbwiwjoiy"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};forbid(
  principal == Principal::"pagxgdwtmtqv",
  action,
  resource == Resource::"mdocnzuopjvx"
) when {
  true
};forbid(
  principal,
  action == Action::"vyiqkkikgpmn",
  resource == Resource::"gncgyolgqhrr"
) when {
  true
};forbid(
  principal == Principal::"yfmfmxoxfosd",
  action == Action::"dllrwzhequoh",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"famgyptaffdm",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"famgyptaffdm",
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};permit(
  principal == Principal::"pagxgdwtmtqv",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"bckfogukcrqc",
  action == Action::"zpdplhiwhfxe",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"dllrwzhequoh",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"jedunopwhdab",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};permit(
  principal == Principal::"seofhjtqtpdg",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"vyiqkkikgpmn",
  resource == Resource::"lputleedekcx"
) when {
  true
};forbid(
  principal == Principal::"pagxgdwtmtqv",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"khdukfbxllxw"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};forbid(
  principal == Principal::"seofhjtqtpdg",
  action == Action::"vyiqkkikgpmn",
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"oytvsrzadkeq"
) when {
  true
};forbid(
  principal == Principal::"rcptcuvbzswx",
  action == Action::"famgyptaffdm",
  resource == Resource::"aitbbxxnatxc"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"atwmtdanenfv"
) when {
  true
};forbid(
  principal == Principal::"fykhjpzumdaa",
  action == Action::"vkvrohivjxad",
  resource == Resource::"bagbcqkvhgqu"
) when {
  true
};permit(
  principal == Principal::"seofhjtqtpdg",
  action,
  resource == Resource::"hwatqlfsxohl"
) when {
  true
};forbid(
  principal == Principal::"hcpkmvhfiymn",
  action,
  resource == Resource::"rfcxnyqfinke"
) when {
  true
};permit(
  principal == Principal::"wwkvlqcrjgyy",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"syppxromuyqb",
  action == Action::"rhdwcsgghxwf",
  resource == Resource::"htdpuvkrildr"
) when {
  true
};forbid(
  principal == Principal::"dnfnsnbevosf",
  action == Action::"qsphwjsrislv",
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};permit(
  principal == Principal::"imvcevihxbhs",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"yfmfmxoxfosd",
  action,
  resource == Resource::"hwatqlfsxohl"
) when {
  true
};permit(
  principal == Principal::"fohhrlglkjwz",
  action == Action::"hjpqojifapdt",
  resource == Resource::"amemmojhemhz"
) when {
  true
};permit(
  principal == Principal::"vkktinyvlpgi",
  action,
  resource == Resource::"amemmojhemhz"
) when {
  true
};forbid(
  principal == Principal::"wwkvlqcrjgyy",
  action == Action::"vyiqkkikgpmn",
  resource
) when {
  true
};permit(
  principal == Principal::"lbkmtgndiegs",
  action == Action::"rfkjqajrgbyl",
  resource
) when {
  true
};forbid(
  principal == Principal::"thgthwrcyish",
  action,
  resource == Resource::"lputleedekcx"
) when {
  true
};permit(
  principal == Principal::"qgnairntuguo",
  action,
  resource == Resource::"rgyqkzvgghzg"
) when {
  true
};permit(
  principal,
  action == Action::"zpdplhiwhfxe",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"rfkjqajrgbyl",
  resource == Resource::"smbssuhglplo"
) when {
  true
};permit(
  principal == Principal::"ulfsjgvyislm",
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"zpdplhiwhfxe",
  resource
) when {
  true
};forbid(
  principal == Principal::"thgthwrcyish",
  action,
  resource == Resource::"htdpuvkrildr"
) when {
  true
};forbid(
  principal,
  action == Action::"hcltmblyzyxf",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"nzkbqfcwhofn",
  resource
) when {
  true
};permit(
  principal == Principal::"euczuvcrhnyw",
  action,
  resource
) when {
  true
};permit(
  principal,
  action == Action::"jmgzsezvduzf",
  resource == Resource::"pxbjcjbxjwjp"
) when {
  true
};permit(
  principal == Principal::"xqifgqptbljq",
  action == Action::"vkvrohivjxad",
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};permit(
  principal == Principal::"ulfsjgvyislm",
  action == Action::"hcltmblyzyxf",
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};forbid(
  principal == Principal::"yfmfmxoxfosd",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"iuwfronkotry",
  action == Action::"hjpqojifapdt",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};permit(
  principal == Principal::"euczuvcrhnyw",
  action,
  resource == Resource::"fbredeszwrzn"
) when {
  true
};forbid(
  principal == Principal::"qgnairntuguo",
  action,
  resource
) when {
  true
};permit(
  principal == Principal::"imvcevihxbhs",
  action == Action::"vkvrohivjxad",
  resource == Resource::"pxbjcjbxjwjp"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"fbredeszwrzn"
) when {
  true
};forbid(
  principal,
  action,
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"uymaurgpenxx"
) when {
  true
};permit(
  principal,
  action == Action::"vczrnqvzhuul",
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"hbwlxxgdilsl"
) when {
  true
};permit(
  principal,
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};forbid(
  principal == Principal::"krpqlztqpgsk",
  action == Action::"ayeusmztlcni",
  resource
) when {
  true
};permit(
  principal == Principal::"iuwfronkotry",
  action == Action::"dllrwzhequoh",
  resource
) when {
  true
};permit(
  principal == Principal::"ulfsjgvyislm",
  action,
  resource
) when {
  true
};permit(
  principal,
  action,
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};permit(
  principal == Principal::"vkktinyvlpgi",
  action == Action::"qsphwjsrislv",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"rhdwcsgghxwf",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"zpdplhiwhfxe",
  resource == Resource::"stlkfofxtpfq"
) when {
  true
};permit(
  principal == Principal::"seofhjtqtpdg",
  action,
  resource == Resource::"nrfcejrbmltz"
) when {
  true
};permit(
  principal == Principal::"wwkvlqcrjgyy",
  action,
  resource
) when {
  true
};forbid(
  principal == Principal::"aagogabfkmox",
  action,
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"veyzqxfgmvow",
  resource
) when {
  true
};permit(
  principal,
  action == Action::"vyiqkkikgpmn",
  resource
) when {
  true
};forbid(
  principal,
  action == Action::"jedunopwhdab",
  resource == Resource::"tdhcfedimojq"
) when {
  true
};permit(
  principal == Principal::"xpkryiciwzgf",
  action,
  resource
) when {
  true
};