name: Generate Coverage

on: pull_request

jobs:
  coverage_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup required dependencies
        run: |
          cargo install grcov
          rustup component add llvm-tools-preview
          mkdir -p target/coverage
      - name: Run tests
        run: >
          CARGO_INCREMENTAL=0
          RUSTFLAGS='-Cinstrument-coverage'
          LLVM_PROFILE_FILE='target/private/profraw/%p-%m.profraw'
          cargo test
      - name: Generate lcov report
        run: >
          grcov 'target/private/profraw/'
          -s '.'
          --binary-path 'target/debug/deps/'
          -t lcov
          --branch
          --ignore-not-existing
          -o 'target/coverage/lcov.info'
          --keep-only 'src/*'
          --excl-start '\#\[cfg\(test\)\]'
          --excl-stop '// GRCOV_BEGIN_COVERAGE'
          --excl-line '\#\[derive\('
      - name: Save PR number
        run: echo ${{ github.event.number }} > target/coverage/pr_num
      - uses: actions/upload-artifact@v3.1.3
        with:
          name: coverage-artifact
          path: target/coverage/
          retention-days: 1